### ISSUE TITLE
HTTPS segmentation fault, but HTTP will not.

### ISSUE THREAD

**Issue by Synmul** [libcpr/cpr#1016]
### Description

Thread 1 "xxxxxxxx.out" received signal SIGSEGV, Segmentation fault.
___pthread_rwlock_wrlock (rwlock=0x31) at ./nptl/pthread_rwlock_wrlock.c:26
Segmentation fault

ld-linux-x86-64.so.2
libhpsocket_d.so.5
libmysqlcppconn.so.7
libcpr.so.1
libstdc++.so.6
libgcc_s.so.1
libc.so.6
libm.so.6
libmysqlclient.so.21
libcurl.so.4
libssl.so.3
libcrypto.so.3
libresolv.so.2
libzstd.so.1
libidn2.so.0
libz.so.1
libunistring.so.2

### Example/How to Reproduce

cpr::Post(cpr::Url{ "https://xxx" }, cpr::Body{""}, cpr::Header{ {"content-type:","application/json;"} });

### Where did you get it from?

GitHub   cpr1.9.7

### Additional Context/Your Environment

- OS: ubuntu server
- Version:22.04

**Comment by COM8** [comment]
Could you please provide a complete, small application demonstrating your code and how you are compiling it since I can not reproduce it.

**Comment by Synmul** [comment]
> 您能否提供一个完整的小型应用程序来演示您的代码以及您如何编译它，因为我无法重现它。

thank you for your reply,I have found the cause and resolved the issue, all of my code that uses the libssl.so.3 library has encountered similar errors, this is not a bug caused by cpr
