### ISSUE TITLE
Question: Does cpr support ftp?

### ISSUE THREAD

**Issue by ottmar-zittlau** [libcpr/cpr#1030]
Hi,

I'm working on a project that uses ftplibpp (https://github.com/mkulke/ftplibpp) to up-/download files to/from a ftp-server.
Now we want to replace this by cpr, because we are already using it for other purposes.
Is it even possible to use it for interacting with ftp-servers?

Thanks and best regards
oz

**Comment by COM8** [comment]
No, not out of the box. We just support http(s)
