### ISSUE TITLE
Confused on something

### ISSUE THREAD

**Issue by bleriaf** [libcpr/cpr#1031]
i'm working on something which is using cpr as a library to do requests and it uses multi-threads but without the session being reused and i noticed something, cpr never calls curl_easy_cleanup on any of the session and i'm wondering if that is a normal behavior.

this is what i do basically;
i create a threadpool with for example 10 thread and i execute a function which every time it creates a new cpr::Session fill it with data and then do the request and then just return.

**Comment by COM8** [comment]
Sorry for the delayed response. I've been on vacation :)

In theory `curl_easy_cleanup` gets called when the `cpr::Session` and corresponding `cpr::Reponse` objects are destructed.
Ref: https://github.com/libcpr/cpr/blob/1ad1cd2daf138aefdcdb1c35d99608387d230ec1/cpr/curlholder.cpp#L28

In my small test case `curl_easy_cleanup` is called properly every time:
```c++
TEST(SessionGetTests, GetSessionDestructor) {
    {
        Url url{server->GetBaseUrl() + "/hello.html"};
        Session session;
        session.SetUrl(url);
        std::string expected_text{"Hello world!"};
        Response response = session.Get();
        EXPECT_EQ(expected_text, response.text);
        EXPECT_EQ(url, response.url);
        EXPECT_EQ(std::string{"text/html"}, response.header["content-type"]);
        EXPECT_EQ(200, response.status_code);
        EXPECT_EQ(ErrorCode::OK, response.error.code);
    }

    {
        Url url{server->GetBaseUrl() + "/hello.html"};
        Session session;
        session.SetUrl(url);
        std::string expected_text{"Hello world!"};
        Response response = session.Get();
        EXPECT_EQ(expected_text, response.text);
        EXPECT_EQ(url, response.url);
        EXPECT_EQ(std::string{"text/html"}, response.header["content-type"]);
        EXPECT_EQ(200, response.status_code);
        EXPECT_EQ(ErrorCode::OK, response.error.code);
    }
}
```

Can you provide an example for reproducing it?

**Comment by bleriaf** [comment]
well i guess it does because the program closes once it finishes doing both, what if you try doing this does the cleanup still get called?

```
int main() {
        Session session;
        session.SetUrl(cpr::Url{ "https://google.com" } );
        Response response = session.Get();
        printf( "ret: %s ", response.text.c_str( ) );

       while ( true ) {
              Sleep( 1000 );
       }
}
```

**Comment by COM8** [comment]
Your example is highly dependent on your compile optimisation level. You compiler might catch the while infinite loop and never call the destructors.

A better solution would be:
```c++
int main() {
        {
            Session session;
            session.SetUrl(cpr::Url{ "https://google.com" } );
            Response response = session.Get();
            printf( "ret: %s ", response.text.c_str( ) );
        }

       while ( true ) {
              Sleep( 1000 );
       }
}

```
