### ISSUE TITLE
13.2.0 gcc compiler, vcpkg and cpr: compilation error.

### ISSUE THREAD

**Issue by ezamosch** [libcpr/cpr#1034]
### Description

I can't compile small cpr example with gcc 13.2.0 compiler using vcpkg. What I did:
1. Wrote vcpkg manifest in project and installed necessery libs:
`vcpkg install
`
```
{
  "dependencies": [
    "cpr"
  ]
}
```

2. Made a small example of code and compiled it with command:
`g++ -std=c++17 index.cpp -o Invest-app -Iinclude -Ivcpkg_installed/x64-windows/include -L/vcpkg_installed/x64-windows/lib -lwsock32 -lws2_32`
```
#include <cpr/cpr.h>
#include "json.hpp"
int main(){

    cpr::Header headers = cpr::Header{
			{"Content-Type", "application/json"},
	};
    std::string baseApiUrl = "https://api.freecurrencyapi.com";
    std::string methodPath = "/v1/latest";

    nlohmann::json currenciesJson = nlohmann::json::parse(cpr::Get(
		baseApiUrl + methodPath,
		headers
	).text);
}

```
Compilation gives me this errors:
![image](https://github.com/libcpr/cpr/assets/48468561/3417ad90-a03f-41f9-bbfe-7cb7d1d6f351)

I provide screenshot because it shows that I get same errors in windows (right cmd window) and in gcc docker image (left terminal results in debian 12).

### Example/How to Reproduce

Same exact steps as in description.

### Where did you get it from?

vcpkg

### Additional Context/Your Environment

- OS: Windows 11, Debian 12

**Comment by ezamosch** [comment]
Btw if I install this library for vs studio compiler it works fine, so I get this problem only with gcc. Is there any solutions for this?

**Comment by COM8** [comment]
Try:

```c++
nlohmann::json currenciesJson = nlohmann::json::parse(cpr::Get(
		cpr::Url{baseApiUrl + methodPath},
		headers
	).text);
```

The compiler can not implicitly convert a string to an URL since there are multiple options. `cpr::Url` and `cpr::Body` are both basically wrappers around `std::string` so your compiler is not sure which one to take here.

**Comment by ezamosch** [comment]
@COM8 yes it worked, thanks! But now I faced another bunch of errors (left debian, right windows):
![image](https://github.com/libcpr/cpr/assets/48468561/38fda115-73a8-4276-8bfd-7e1c2f3218af)
![image](https://github.com/libcpr/cpr/assets/48468561/04cddae2-a847-4310-8b4d-041d4b5e9426)
Any ideas what is wrong?

**Comment by COM8** [comment]
You are not linking against cpr. Try adding `-lcpr` to your gcc invocation.

**Comment by ezamosch** [comment]
@COM8 Fabian, tyvm! It was my bad indeed (I forget how to properly link libs with gcc). Fixed that with this full command:
`g++ -std=c++17 index.cpp -o Cpp-service -Iinclude -I/usr/src/project-folder/vcpkg_installed/x64-linux/include -L/usr/src/project-folder/vcpkg_installed/x64-linux/lib -lcpr -lcurl -lz -lssl -lcrypto`
Please change it from bug to question :)

**Comment by ezamosch** [comment]
I was a bit hurry - it works in debian as I mentioned above, but in windows compilation I still get the same error:
`g++ -std=c++17 index.cpp -o Invest-app -Iinclude -Ivcpkg_installed/x64-windows/include -Lvcpkg_installed/x64-windows/lib -lcpr -lcurl -lzlib -lssl -lcrypto -lwsock32 -lws2_32`
![image](https://github.com/libcpr/cpr/assets/48468561/d05cb09c-8bd0-438f-8b22-b9c4f6dc8476)
That is what directory with libs contain on which I -L for search:
![image](https://github.com/libcpr/cpr/assets/48468561/8a918944-2290-459e-9ef7-3c57614b67cb)

**Comment by ezamosch** [comment]
I fixed this on Windows by compiling my vcpkg manifest with static triplets for mingw64 platform:
`vcpkg install --triplet=x64-mingw-static
`
after that finally compiled my program with that command:
`g++ -std=c++17 index.cpp -o Invest-app -Iinclude -Ivcpkg_installed/x64-mingw-static/include -Lvcpkg_installed/x64-mingw-static/lib -lcpr -lcurl -lzlib -lssl -lcrypto -lbcrypt -lcrypt32 -lpqxx -lpq -lwsock32 -lws2_32 `
