### ISSUE TITLE
cpr use system default curl?

### ISSUE THREAD

**Issue by bethebest0622** [libcpr/cpr#1043]
### Is your feature request related to a problem?

i am trying to use cpr in centos stream 8, with default curl.

My system curl is 8.2.1.

but without component http and https.

If i dont turn on `CPR_USE_SYSTEM_CURL`, cpr seems will compile a curl version, which will mess up.

![image](https://github.com/libcpr/cpr/assets/107900327/94dcb9de-0a1a-457b-a032-69fce985d7b6)

### Possible Solution

how can i set up cpr without install or complieing a new curl version?

**Comment by COM8** [comment]
I do not really get your question there. What I understand is you want to use cpr with your system curl, but without setting `CPR_USE_SYSTEM_CURL`?

**Comment by COM8** [comment]
Ah, then curl on your system is not properly configured to include the http and https components. How did you install libcurl on your system?

**Comment by COM8** [comment]
Did you install `libcurl-devel`?

**Comment by COM8** [comment]
What I did:

```bash
podman run -i -t quay.io/centos/centos:stream8 /bin/bash
```
To get a docker container with centos8 stream.

Then I build cpr and got the same error as you.
```bash
git clone https://github.com/libcpr/cpr.git
cd cpr
mkdir build && cd build
dnf install -y gcc clang cmake gdb git libcurl-devel openssl-devel
cmake .. -DCMAKE_BUILD_TYPE=Release -DCPR_USE_SYSTEM_CURL=ON -DCPR_BUILD_TESTS=ON -DCPR_BUILD_TESTS_SSL=ON -DCPR_ENABLE_SSL=ON
```

But this one can be fixed with the following patch:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5af3657..d41271c 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -173,7 +173,7 @@ endif()
 # Curl configuration
 if(CPR_USE_SYSTEM_CURL)
     if(CPR_ENABLE_SSL)
-        find_package(CURL COMPONENTS HTTP HTTPS)
+        find_package(CURL)
         if(CURL_FOUND)
             message(STATUS "Curl ${CURL_VERSION_STRING} found on this system.")
             # To be able to load certificates under Windows when using OpenSSL:
```

This patch should work since I still  had an too old version of curl installed (7.61.1).

**Comment by COM8** [comment]
Closing for no response.
