### ISSUE TITLE
Missing .dll when compile with CMake on Windows

### ISSUE THREAD

**Issue by caslama16** [libcpr/cpr#1049]
### Description

I have a CMake project, where I need to use cpr. I used same steps, as you mentioned but when the project was compiled and I ran it, the error said that cpr.dll was missing. What should I do?

### Example/How to Reproduce

1. Copy steps which should be used in CMake
2. Build the project
3. Run it

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

- OS: Windows
- Version: 3b15fa82ea74739b574d705fea44959b58142eb8

**Comment by COM8** [comment]
@caslama16 welcome!
Here is an end-to-end example for using cpr inside CMake: https://github.com/libcpr/example-cmake-fetch-content

If you still have problems with it, please consider sharing more information like the error log output, an example for me to reproduce, ...
Else I can only guess what is going wrong and I waste a lot of time.

**Comment by COM8** [comment]
Closing for no response.

**Comment by ZaytsNick** [comment]
![fc15c778-c836-471f-b297-c6d21e4b8b85](https://github.com/libcpr/cpr/assets/109246163/7478d08a-f813-4dc1-ad39-cda1025549ba)
trying to include the library cpr:
Code execution cannot continue because the system did not detect cpr.dll
https://github.com/ZaytsNick/dev-skillbox-module30.git

**Comment by nisooom** [comment]
yes i am having the same issue, plz reopen.

**Comment by COM8** [comment]
@nisooom these lines might help: https://github.com/libcpr/example-cmake-fetch-content/blob/d99dfed29be9e1e3e9100b5b5abd714f701f7fbe/CMakeLists.txt#L25-L28


Other than that, I can not help you if you do not provide context or a small example application for me to take a look at.
