### ISSUE TITLE
CURLcode curl_mime_filename converting argument 2 from value type to const char* not possible

### ISSUE THREAD

**Issue by chill0r** [libcpr/cpr#1051]
### Description

When trying to compile cpr on windows with the msvc compiler the build fails with the following errors:  
```
C2664 "CURLcode curl_mime_filename(curl_mimepart *, const char*)": Converting argument 2 from "const std::filesystem::path::value_type *" to "const char*" not possible
```

### Example/How to Reproduce

1. Create an new ```CMakeLists.txt``` with the following content:
```
cmake_minimum_required (VERSION 3.8)
set(CMAKE_CXX_STANDARD 17)
project(test)
add_library(test SHARED)
target_sources(test PUBLIC test.h PRIVATE test.cpp)
include(FetchContent)
FetchContent_Declare(cpr GIT_REPOSITORY https://github.com/libcpr/cpr.git)
FetchContent_MakeAvailable(cpr)
target_link_libraries(test PRIVATE cpr::cpr)
```
2. Try to compile on windows with Visual Studio 2022 CE (MSVC 14.39.33519)

### Possible Fix

The line in question is in ```session.cpp``` 958:
```
curl_mime_filename(mimePart, fs::path(file.filepath).filename().c_str());
```
after changing to
```
curl_mime_filename(mimePart, fs::path(file.filepath).filename().string().c_str());
```
it's working fine.

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

- OS: WIndows 10
- Version: 10.0.19045
- Compiler: MSVC 14.39.33519

**Comment by COM8** [comment]
@chill0r Thanks for reporting. Confirmed!
