### ISSUE TITLE
Session with different urls

### ISSUE THREAD

**Issue by a412h** [libcpr/cpr#1058]
This is not a bug of the library, only a question.
Let us say that I have to maintain a connection to two different urls (same base url, but two different endpoints) with a Session object. What is the recommended approach ?
Should I instantiate one session object, and change the url in the session object each time before a message is sent ? For example, with two different urls:
 ```
cpr::Session session;

session.SetUrl(cpr::Url{url1});
cpr::Response r1 = session.Post();

session.SetUrl(cpr::Url{url2});
cpr::Response r2 = session.Post();
```
Is that efficient ? What would be the recommended approach ?

**Comment by COM8** [comment]
Go with two sessions since that way you keep the session stats. Else every request would initiate a new SSL handshake, which is slow.

**Comment by a412h** [comment]
Thank you for the prompt and clear response.
