### ISSUE TITLE
Broken on Windows with HTTPS and Curl 8.8.0 (works with 8.6.0)

### ISSUE THREAD

**Issue by fhoenig** [libcpr/cpr#1068]
### Description

Windows version seems to not be compatible with curl 8.8.0. Build with nmake static lib x64 and with windows's sspi.

### Example/How to Reproduce

1. call `cpr::Response r = cpr::Get(cpr::Url{ "https://api.github.com/repos/whoshuu/cpr/contributors" });`
2. See error (`CURLE_BAD_FUNCTION_ARGUMENT`)

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

- OS: windows
- Version: 11

**Comment by COM8** [comment]
I discarded the update to curl 8.8.0 (https://github.com/libcpr/cpr/pull/1054) since it does not work with MbedTLS.

Please provide a detailed error log.

**Comment by COM8** [comment]
The CI at least worked for curl 8.8.0: https://github.com/libcpr/cpr/actions/runs/9225854129/job/25408143763

**Comment by COM8** [comment]
Closing for no response. Feel free to reopen in case it still persists.
