### ISSUE TITLE
put cpr into a cmake project and  error while loading shared libraries: libinih.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by carlwang99** [libcpr/cpr#1071]
### Description

 error while loading shared libraries: libinih.so: cannot open shared object file: No such file or directory

### Example/How to Reproduce

integrate cpr into a cmake project

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

- OS: centos
- Version:7

**Comment by COM8** [comment]
@carlwang99 thanks for reporting! centos7 is EOL and therefore we do not officially support it. Try installing `inih` (`dnf install inih`) although I don't think this is a cpr issue since we are not using it.
