### ISSUE TITLE
Response.GetCertInfos() is not const

### ISSUE THREAD

**Issue by askraskr** [libcpr/cpr#1073]
### Description

Since `Response.GetCertInfos() ` method is not `const`, we cannot use it with constant response objects.
for example, you we cannot pass a `Response` object to a function with the following signature:

```c++
nlohmann::json response_to_json(const cpr::Response &response)
{
   // .....
   for (size_t i{}; const auto &cert: response.GetCertInfos()) {
              // do something with cert
   }
   // .....
}
```

### Example/How to Reproduce

```c++
nlohmann::json response_to_json(const cpr::Response &response)
{
   // .....
   for (size_t i{}; const auto &cert: response.GetCertInfos()) {
              // do something with cert
   }
   // .....
}

int main() 
{
        auto response = cpr::Get(cpr::Url("https://www.google.com"),
	                         cpr::UserAgent("Mozilla")
	);
        auto json = response_to_json(response);
}
```

### Possible Fix

Since `GetCertInfos()` is not changing any data member of `Response`, it's better to make it `const`

```c++
namespace cpr {
///.... other stuff
class Response {
    ///.... other stuff
    std::vector<CertInfo> GetCertInfos() const;
    ///.... other stuff
};
} // namespace cpr
```

### Where did you get it from?

Other (specify in "Additional Context/Your Environment")

### Additional Context/Your Environment

- OS: All
- Version: Development

**Comment by COM8** [comment]
@askraskr thanks for reporting. Fixed in https://github.com/libcpr/cpr/pull/1076.
Can you please confirm it works now for you?

**Comment by askraskr** [comment]
@COM8  Yes, it works.
thanks
