### ISSUE TITLE
WriteCallback should take a string_view as argument instead of a std::string to avoid a copy

### ISSUE THREAD

**Issue by fdgStilla** [libcpr/cpr#1074]
### Is your feature request related to a problem?

My client application download huge files from a server using `Download(std::ofstream& file)`.
But I realized that no error was raised when the writing fails (in my case the disk was full).
So I switched to `Download(const WriteCallback& write)` to manage the iostream myself (using [this method](https://en.cppreference.com/w/cpp/io/basic_ios/exceptions) ) but I noticed that the data is copied to a string for each callback, so it was not equivalent to the previous code.

### Possible Solution

I suggest to use a `std::string_view` as argument instead of a `std::string` in the `WriteCallback`.

**Comment by COM8** [comment]
Agree! Fixed it here: https://github.com/libcpr/cpr/pull/1081

Could you please verify it works?

**Comment by fdgStilla** [comment]
It is not easy to test a custom branch, I am using the official conan package, but looks good to me thanks !
By the way I am looking forward to seeing the next release.
