### ISSUE TITLE
When is the time for threadpool creation?

### ISSUE THREAD

**Issue by carlwang99** [libcpr/cpr#1083]
### Description

i want to know when is the time for threadpool creation?
when i first call postasync, get async ... (async function)?

### Example/How to Reproduce

1. create threadpool not at first creating session, but at the first call of async functions?

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

- OS: ubuntu
- Version: 20.04

**Comment by carlwang99** [comment]
i could not understand when the startup function in async.h is called

**Comment by COM8** [comment]
The threadpool is started once the first async call is submitted (`cpr::Threadpool::Submit`). If you want to start it manually you can call `cpr::async::startup`.
