### ISSUE TITLE
Resolving linker errors with nuget package?

### ISSUE THREAD

**Issue by exdunn** [libcpr/cpr#1086]
Hi, can someone please help me get libcpr working with my project?

I've installed the nuget package and getting the following errors when I try compiling:

`1>MarketChecker.obj : error LNK2028: unresolved token (0A0010F7) "public: virtual __cdecl cpr::EncodedAuthentication::~EncodedAuthentication(void)" (??1EncodedAuthentication@cpr@@$$FUEAA@XZ) referenced in function "public: __cdecl std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class cpr::EncodedAuthentication>::~pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class cpr::EncodedAuthentication>(void)" (??1?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VEncodedAuthentication@cpr@@@std@@$$FQEAA@XZ)
1>MarketChecker.obj : error LNK2028: unresolved token (0A0010FC) "public: __cdecl cpr::Session::Session(void)" (??0Session@cpr@@$$FQEAA@XZ) referenced in function "class cpr::Response __cdecl cpr::Get<class cpr::Url>(class cpr::Url &&)" (??$Get@VUrl@cpr@@@cpr@@$$FYA?AVResponse@0@$$QEAVUrl@0@@Z)
1>MarketChecker.obj : error LNK2028: unresolved token (0A0010FE) "public: void __cdecl cpr::Session::SetOption(class cpr::Url const &)" (?SetOption@Session@cpr@@$$FQEAAXAEBVUrl@2@@Z) referenced in function "void __cdecl cpr::priv::set_option_internal<0,class cpr::Url>(class cpr::Session &,class cpr::Url &&)" (??$set_option_internal@$0A@VUrl@cpr@@@priv@cpr@@$$FYAXAEAVSession@1@$$QEAVUrl@1@@Z)
1>MarketChecker.obj : error LNK2028: unresolved token (0A0010FF) "public: class cpr::Response __cdecl cpr::Session::Get(void)" (?Get@Session@cpr@@$$FQEAA?AVResponse@2@XZ) referenced in function "class cpr::Response __cdecl cpr::Get<class cpr::Url>(class cpr::Url &&)" (??$Get@VUrl@cpr@@@cpr@@$$FYA?AVResponse@0@$$QEAVUrl@0@@Z)
1>MarketChecker.obj : error LNK2019: unresolved external symbol "public: void __cdecl cpr::Session::SetOption(class cpr::Url const &)" (?SetOption@Session@cpr@@$$FQEAAXAEBVUrl@2@@Z) referenced in function "void __cdecl cpr::priv::set_option_internal<0,class cpr::Url>(class cpr::Session &,class cpr::Url &&)" (??$set_option_internal@$0A@VUrl@cpr@@@priv@cpr@@$$FYAXAEAVSession@1@$$QEAVUrl@1@@Z)
1>MarketChecker.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl cpr::EncodedAuthentication::~EncodedAuthentication(void)" (??1EncodedAuthentication@cpr@@$$FUEAA@XZ) referenced in function "public: __cdecl std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class cpr::EncodedAuthentication>::~pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class cpr::EncodedAuthentication>(void)" (??1?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VEncodedAuthentication@cpr@@@std@@$$FQEAA@XZ)
1>MarketChecker.obj : error LNK2019: unresolved external symbol "public: __cdecl cpr::Session::Session(void)" (??0Session@cpr@@$$FQEAA@XZ) referenced in function "class cpr::Response __cdecl cpr::Get<class cpr::Url>(class cpr::Url &&)" (??$Get@VUrl@cpr@@@cpr@@$$FYA?AVResponse@0@$$QEAVUrl@0@@Z)
1>MarketChecker.obj : error LNK2019: unresolved external symbol "public: class cpr::Response __cdecl cpr::Session::Get(void)" (?Get@Session@cpr@@$$FQEAA?AVResponse@2@XZ) referenced in function "class cpr::Response __cdecl cpr::Get<class cpr::Url>(class cpr::Url &&)" (??$Get@VUrl@cpr@@@cpr@@$$FYA?AVResponse@0@$$QEAVUrl@0@@Z)
1>C:\Users\alexh\source\repos\Poecery\x64\Debug\Poecery.exe : fatal error LNK1120: 8 unresolved externals`

For reference my proj file is: https://github.com/exdunn/Poecery/blob/master/Poecery.vcxproj

**Comment by COM8** [comment]
@exdunn please use the issue template
