### ISSUE TITLE
Can't use CPR in my Visual Studio project

### ISSUE THREAD

**Issue by aidv** [libcpr/cpr#1099]
### Description

![image](https://github.com/user-attachments/assets/58e80954-d87f-4508-9bee-0de7e7e05a7c)

I am getting the error in the screenshot.

I have followed the CPR install instructions correctly.

Any ideas how to fix this?

### Example/How to Reproduce

N/A

### Where did you get it from?

vcpkg

### Additional Context/Your Environment

- OS: Windows
- Version: 11

**Comment by COM8** [comment]
Did you set the correct C++ standard? You need >=17.

**Comment by aidv** [comment]
> Did you set the correct C++ standard? You need >=17.

Maybe(?) Where do I set it? And for what do I set it? For the VStudio project or for the build of CPR?

**Comment by COM8** [comment]
I'm not a Windows user and I'm discouraged from using Visual Studio build in C++ dependency tracking. Instead I suggest using CMake in Visual Studio.

Here is an example:
https://github.com/libcpr/example-cmake-fetch-content

**Comment by aidv** [comment]
> I'm not a Windows user and I'm discouraging from using Visual Studio build in C++ dependency tracking. Instead I suggest using CMake in Visual Studio.
> 
> Here is an example: https://github.com/libcpr/example-cmake-fetch-content

I see. The project on my hands is using Visual Studio so I am a little bit restricted.

**Comment by COM8** [comment]
Closing this one as it is not directly related to cpr.
