### ISSUE TITLE
Static library - zlib.dll is created instead of zlib.lib

### ISSUE THREAD

**Issue by dmitri-fm** [libcpr/cpr#1107]
### Description

Zlib is built as static library, but the library has .dll extension

### Example/How to Reproduce

Configure/Generate with CMake as static library, open solution in Visual Studio
![s1](https://github.com/user-attachments/assets/4ffdb783-7b3b-4442-aafd-0516328c2df8)

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

- OS: Windows 10
- Version: https://github.com/libcpr/cpr/releases/tag/1.10.5

**Comment by COM8** [comment]
@vergol thanks for reporting. I will try to look into it as soon as possible.

**Comment by COM8** [comment]
Closing for no response
