### ISSUE TITLE
Why does cpr::Timeout has two chrono bases ctors?

### ISSUE THREAD

**Issue by Chrys4lisfag** [libcpr/cpr#1129]
Timeout(const std::chrono::milliseconds& duration) 
Timeout(const std::chrono::seconds& duration)

Due to we have implicitly specified two chrono types, doing this will lead to inability to select proper ctor as mins\hours etc is not implicitly specified:

`const cpr::Timeout timeout{ 5min };`

Shouldn't we just create only ms ctor as any chrono duration type would be automatically casted to input parameter type?

**Comment by laxerhd** [comment]
I would like to fix this issue

**Comment by laxerhd** [comment]
So, only removing the `Timeout(const std::chrono::seconds& duration)` ctr lead to some 
compilation issues regarding type mismatch errors. 
Even though chrono duration types would usually be implicitly convertible, it seems that this implicit conversion is not automatically applied during a constructor call. 
I am not that fluent in C++, but I have read that the C++ compiler does not perform implicit chaining of conversions when there is a need to convert a type (e.g. `std::chrono::seconds`) into another type (`std::chrono::milliseconds`) and then use it to match a constructor.
We could use a template constructor that accepts any std::chrono::duration type and then convert it directly to milliseconds.

```cpp
template <typename Rep, typename Period>
Timeout(const std::chrono::duration<Rep, Period>& duration)
    : ms{std::chrono::duration_cast<std::chrono::milliseconds>(duration)} {}
```

With this we could delete both the milliseconds and seconds ctr, with only the integer and the template ctr remaining.
What do you think?

**Comment by COM8** [comment]
@laxerhd thanks for looking into it! Yes, this sounds good. Would you like to create a PR for it?
