### ISSUE TITLE
Upgrading from 1.10.2 to 1.11.0 created large amounts of latency in API calls

### ISSUE THREAD

**Issue by honeysuckle1234** [libcpr/cpr#1133]
### Description

When upgrading from cpr 1.10.2 to 1.11.0, our cpr::PostAsync calls started showing a large amount of latency between being sent and being received, ~1 minute in most cases, but sometimes would be indefinitely delayed.

### Example/How to Reproduce

1. Create a call: `cpr::AsyncResponse response = cpr::PostAsync(cpr::Url{url}, cpr::Body{body}, headers);`
2. Wait for the request to come in: `response .wait_for(0ms) == std::future_status::timeout`
3. Observe the time for the message to be 'sent' to being 'received' by another service.

### Possible Fix

We downgraded back to 1.10.2, but installed Curl separately to upgrade that to 8.10.0.

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

- OS: Linux
- Version: 1.10.2
- Curl was not the issue, as using 8.10.0 worked fine in 1.10.2 and didn't produce latency.

**Comment by COM8** [comment]
@honeysuckle1234 thanks for reporting!
This could be related to this PR: https://github.com/libcpr/cpr/pull/1039

That's the only change I remember out of my had without looking too deep into the changes between 1.10.x and 1.11.0 related to async stuff.

Not sure if I will be able to, but I can try to look into it next weekend.

**Comment by COM8** [comment]
Closing for no response. Feel free to reopen in case this issue still persists.
