### ISSUE TITLE
How can I disable the automatic deflate feature?

### ISSUE THREAD

**Issue by Nullarity** [libcpr/cpr#1136]
Hi,
let's say I run this code:

```c++
auto r = cpr::Get ( cpr::Url { "https://jsonplaceholder.typicode.com/posts" },
				 cpr::AcceptEncoding { cpr::AcceptEncodingMethods::gzip } );
// Print response headers to verify compression
std::cout << "Content-Encoding: " << r.header [ "content-encoding" ] << "\n";
std::cout << "Response size: " << r.text.size () << " bytes\n";
std::cout << "First few characters: " << r.text.substr ( 0, 100 ) << "\n";
```
Then the output will be like this:
```
Content-Encoding: gzip
Response size: 27520 bytes
First few characters: [
  {
    "userId": 1,
    "id": 1,
    "title": "sunt aut facere repellat provident occaecati excep
```

The output indicates that the response was automatically deflated. Is there a way to disable this and receive the response in its original form?

Thank you!

**Comment by COM8** [comment]
Please try `AcceptEncodingMethods::disabled` e.g.:
```c++
cpr::Get(cpr::AcceptEncoding{AcceptEncodingMethods::disabled}, cpr::Url{"https://..."});
```

This does the following:
> Set [CURLOPT_ACCEPT_ENCODING](https://curl.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html) to NULL to explicitly disable it, which makes libcurl not send an Accept-Encoding: header and not decompress received contents automatically.

Source: https://curl.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html

**Comment by Nullarity** [comment]
I tried, but unfortunately, without specifying the gzip in the header, the service assumes that this is application/json and sends back the text data.

**Comment by COM8** [comment]
And if you manually add the `accept-encoding` header while providing the `cpr::AcceptEncoding{AcceptEncodingMethods::disabled}` option, this does not work?

**Comment by Nullarity** [comment]
> And if you manually add the `accept-encoding` header while providing the `cpr::AcceptEncoding{AcceptEncodingMethods::disabled}` option, this does not work?

Yes, it works:

```cpp
auto r = cpr::Get ( cpr::AcceptEncoding { 
  cpr::AcceptEncodingMethods::disabled },
  cpr::Header { { "Accept-Encoding", "gzip" } },
  cpr::Url { "https://jsonplaceholder.typicode.com/posts" } );

// Print response headers to verify compression
std::cout << "Content-Encoding: " << r.header [ "content-encoding" ] << "\n";
std::cout << "Response size: " << r.text.size () << " bytes\n";
std::cout << "First few characters: " << r.text.substr ( 0, 100 ) << "\n";
```
Then the output will be like this:
```
Content-Encoding: gzip
Response size: 7066 bytes
First few characters: �
```
Thank you!
So, feel free to close this issue if that behavior is by design.
