### ISSUE TITLE
`Improving Error Handling`: Missing PARTIAL_FILE and long `switch-case` refactoring

### ISSUE THREAD

**Issue by laxerhd** [libcpr/cpr#1140]
### Description

While taking a look at `error.h`, I noticed that the `ErrorCode` enum entry `PARTIAL_FILE` is not used in the `error.cpp` switch statement. Is this intended? 

I also wanted to ask if there was any specific reason for including `CURLE_OBSOLETE46` while not adding the other obsolete cURL error codes? Are the others related to unsupported protocols? 

`PARTIAL_FILE` and `CURLE_OBSOLETE46` were both added in this [commit](https://github.com/libcpr/cpr/pull/1110/commits/c698b9a2f5f457712973417b11b6ffb7ee6700f8) when adding better cpr error codes in september.

Additionally `error.cpp` looks kind of scarry with its 200-line `switch-case` statement. I was wondering if using an `unordered_map` instead of the `switch-case` statement might make the code a bit more readable and easier to maintain.

For example:
```cpp
static const std::unordered_map<std::int32_t, ErrorCode> curl_error_map = {
    {CURLE_OK, ErrorCode::OK},
    {CURLE_UNSUPPORTED_PROTOCOL, ErrorCode::UNSUPPORTED_PROTOCOL},
    // -- AND FOR ERROR CODES ONLY SUPPORTED IN SPECIFIC LIBCURL_VERSION --
#if LIBCURL_VERSION_NUM >= 0x074E00
    {CURLE_SETOPT_OPTION_SYNTAX, ErrorCode::SETOPT_OPTION_SYNTAX},
#endif
    ...
}
```

### Example/How to Reproduce

Files to take a look at: `error.cpp` and `error.h` as well as this [commit](https://github.com/libcpr/cpr/pull/1110/commits/c698b9a2f5f457712973417b11b6ffb7ee6700f8)

### Possible Fix

1. Adding `PARTIAL_FILE`-case to `error.cpp`
2. Include/Remove obsolete error codes for consistency
3. Refactor `errror.cpp` to use map instead of a `switch-case`

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

- OS: -
- Version: -

**Comment by COM8** [comment]
@laxerhd thanks for bringing this to my attention.

* `PARTIAL_FILE` you are right. This is missing. It should map to `CURLE_PARTIAL_FILE` which was added in curl [7.1](https://github.com/curl/curl/blob/acc73edce8c08e24ceadb4f46d2d812cf03fc6bb/docs/libcurl/symbols-in-versions#L288)
* `CURLE_OBSOLETE46` can be removed. There is no reason to include it.
* Map based approach: Yes! I really like this approach.

Would you like to create a PR for it?

**Comment by laxerhd** [comment]
Yeah, I can do that!
