### ISSUE TITLE
missing .h file:

### ISSUE THREAD

**Issue by Tina-1300** [libcpr/cpr#1141]
### Description

hello I had this problem when I tried the cpr code on your doc and I tried to find the missing .h but I don't know where to find it can you tell me where to find the library to install the stable version with this file because I compile everything manually under Windows and I couldn't find this file #include "cpr/cprver.h"

thanks in advance

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

- OS:Windows
- Version:

**Comment by COM8** [comment]
Welcome @Tina-1300!

`cprver.h` gets generated by CMake during configuration from the following file template:
https://github.com/libcpr/cpr/blob/master/cmake/cprver.h.in

Once generated, it is located inside `${cpr_BINARY_DIR}/cpr_generated_includes/cpr/cprver.h`. Ref: https://github.com/libcpr/cpr/blob/d3e278665e3ae02db29a21d813c75d64515b7db2/CMakeLists.txt#L5

**Comment by Tina-1300** [comment]
and if I am not cmake what can I do?

**Comment by COM8** [comment]
Manually copy/paste the file and fill out the variables or copy it from a CMake build/configure
