### ISSUE TITLE
Is `Session::GetSharedPtrFromThis` mistakenly marked as private?

### ISSUE THREAD

**Issue by epicbigcat** [libcpr/cpr#1145]
### Description

I noticed in #999 that `Session` is no longer movable/copyable. And it is recommended to use shared_ptr.

Session currently publicly inherits from `std::enable_shared_from_this<Session>`, so I can use `session->shared_from_this()`, but I noticed there is also a private function that provides the same functionality: `Session::GetSharedPtrFromThis()`.

Is this a bug?

### Example/How to Reproduce

See above :)

### Possible Fix

Mark `Session::GetSharedPtrFromThis()` as a public.

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

- OS: Linux
- Version: 1.11.0

**Comment by COM8** [comment]
@epicbigcat thanks for reporting! Fixed in #1148
