### ISSUE TITLE
Print raw http request

### ISSUE THREAD

**Issue by luz-arreola** [libcpr/cpr#1147]
### Is your feature request related to a problem?

I would like to print the raw http request.  This is very helpful for troubleshooting because you know exactly what request you sent.

### Possible Solution

In Boost.Beast, you create a request message and before sending it, you simply `std::cout << req;`

### Alternatives

No alternative tried.

**Comment by COM8** [comment]
@luz-arreola what you most likely want to use is [cpr::Interceptor](https://docs.libcpr.org/advanced-usage.html#interceptors).
