### ISSUE TITLE
How to build cpr with a custom libcurl library?

### ISSUE THREAD

**Issue by eaziz4** [libcpr/cpr#1149]
### Description

I want to specify the libcurl library when building cpr.  How can I do that?  I'm on mac right now for development, but production is on ubuntu

### Example/How to Reproduce

. 

### Possible Fix

.

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

.

**Comment by eaziz4** [comment]
for more context, I want to use https://github.com/lexiforest/curl-impersonate instead of the default curl

**Comment by COM8** [comment]
@eaziz4 thanks for your question here!
This is not supported directly. Buuuut you could try the following:
1. Create and install a custom [`FindCURL.cmake`](https://github.com/Kitware/CMake/blob/master/Modules/FindCURL.cmake) on your system
2. Set [`CPR_USE_SYSTEM_CURL`] during configuration (e.g. `cmake .. -DCPR_USE_SYSTEM_CURL=ON`).
