### ISSUE TITLE
HTTP2 support

### ISSUE THREAD

**Issue by thedrow** [libcpr/cpr#116]
Curl already supports HTTP2.
It'd be useful to have a client that automatically upgrades the connection to HTTP2 if the server supports it.

**Comment by edkimmel** [comment]
I'm surprised this isn't a feature already. It's very straightforward to set this up.

1) Make sure cURL is compiled with nghttp2 - that's how cURL provides support for http2.
2) Add `curl_easy_setopt(easyHandle, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_2TLS);` to session.cpp. (Can also use CURL_HTTP_VERSION_2_0 if https isn't supported yet)

**Comment by p0fi** [comment]
Yeah this lib should definitely support HTTP/2 +1 for this one!

**Comment by COM8** [comment]
Anybody would like to create a PR for this?

**Comment by mohsenomidi** [comment]
Dear @COM8,

Thanks for your awesome library, is there any estimation about the release this feature, this is very important for us, all our backends change the protocol to H2 and we can not use this library for those backends ?

**Comment by COM8** [comment]
@mohsenomidi done in #638.
Could you please validate the PR if it fulfills all your needs?

**Comment by mohsenomidi** [comment]
Thanks so much, it is great 👍❤️🙏
