### ISSUE TITLE
License compatibility with mongoose

### ISSUE THREAD

**Issue by furkanusta** [libcpr/cpr#134]
Hi, I've just find your library and was preparing to use. However, I have one small question:
This project uses mongoose (which is GPLv2), wouldn't it force this library to be released under GPL as well?

I am not a lawyer nor a professional on this issue. I just wanted to clarify a point in my mind.

or, would it be possible to use this library without mongoose? (It looks like only server.cpp uses this)

Similar question in [stackexchange](http://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l)

**Comment by whoshuu** [comment]
Interesting point. Yeah I think I'd need a license lawyer (or someone more experienced than me) to weigh in on this. The mongoose part is "distributed" with the repository insofar as the repository proper does include a subdirectory with mongoose code. The library produced by the project (libcpr.a or libcpr.so) would contain no part of the mongoose code, which is where the trickiness comes in and where it'd be nice to get someone with more expertise looking at this.

**Comment by whoshuu** [comment]
It looks like the pertinent part pointed out by the accepted answer is this:

>So if GPL-licensed code ever gets included in your project, for example via linking against a GPL'd library, you must also provide your whole project under the GPL.

but again, no user would link against a GPL-licensed library. The library produced is GPL free.

**Comment by whoshuu** [comment]
To make it even clearer, this line describes the entire contents of the library: https://github.com/whoshuu/cpr/blob/d866f5bcf525a26d737825b756c8db6be7c58272/cpr/CMakeLists.txt#L6.

**Comment by COM8** [comment]
Yes, in general we have to use a GPL compatible license for all the parts, that link against mongoose.
Since we use mongoose only for the tests, it is possible to distribute the "main" project as MIT and all the tests as GPL, since linking happens only in one direction CPR->Tests (MIP->GPL) which is fine.
I'd suggest we fix this for the 1.6.0 release.

**Comment by COM8** [comment]
As a reference: https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
