### ISSUE TITLE
urlEncode has issues when handling UTF8 string on windows systems

### ISSUE THREAD

**Issue by Xiangli-Zhao** [libcpr/cpr#164]
Thanks a lot for the excellent project.  This makes me easily for handling http request.
i've met a little problems when posting UTF8 strings to servers. here is my code snapshot.

int encodeChars(const char *from, char *to, UINT fromCode, UINT toCode) {
	int len = strlen(from);
	int wlen = MultiByteToWideChar(fromCode, 0, from, -1, NULL, 0);
	wchar_t *wscBuffer = new wchar_t[wlen];
	memset(wscBuffer, 0, sizeof(wchar_t)* wlen);
	MultiByteToWideChar(fromCode, 0, from, -1, wscBuffer, wlen);
	int tolen = WideCharToMultiByte(toCode, 0, wscBuffer, -1, NULL, 0, NULL, NULL);
	WideCharToMultiByte(toCode, 0, wscBuffer, -1, to, tolen, NULL, NULL);
	delete[]wscBuffer;
	return 1;
}
	char* content = R"(魔兽世界！)";
	char *urlContent = new char[strlen(content) * 3]{0};
	std::string send_str;
	encodeChars(content, urlContent, CP_ACP, CP_UTF8);
	send_str.append(urlContent);
	delete[]urlContent;
	auto r = cpr::Post(Url{ "http://myurl" }, Header{ { "Content-Type", "text/plain" } },
		cpr::Body{ send_str });

for my private fix, i've changed    f (std::isalnum(c)  to  std::isalnum((unsigned char)c) in util.cpp in line 69.
and thanks again for great jobs.

**Comment by dlee-libo** [comment]
Could you provide your output? I just tested your case on my computer, it turned out that the lib is correct.
On my computer:
R"(魔兽世界！)"   ===>  "%e9%ad%94%e5%85%bd%e4%b8%96%e7%95%8c%ef%bc%81"

**Comment by Xiangli-Zhao** [comment]
After convert to UTF8 using windows api, i got 
		[0]	-23 '?'	char
		[1]	-83 '?'	char
		[2]	-108 '?'	char
		[3]	-27 '?'	char
		[4]	-123 '?'	char
		[5]	-67 '?'	char
		[6]	-28 '?'	char
		[7]	-72 '?'	char
		[8]	-106 '?'	char
		[9]	-25 '?'	char
		[10]	-107 '?'	char
		[11]	-116 '?'	char
		[12]	-17 '?'	char
		[13]	-68 '?'	char
		[14]	-127 '?'	char
very interesting.
