### ISSUE TITLE
compress transfer failed

### ISSUE THREAD

**Issue by guifengcheng** [libcpr/cpr#211]
Get request with {"Accept-Encoding", "compress, gzip"} ， and nginx gzip on，cannot get the correct data. The reason is that CURLOPT_ACCEPT_ENCODING is not set.

**Comment by t0trader** [comment]
@guifengcheng please compile curl library with zlib

`#define HAVE_LIBZ 1
#define HAVE_ZLIB_H 1`

**Comment by rustyx** [comment]
Does not work.

[CURLOPT_ACCEPT_ENCODING](https://curl.haxx.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html) needs to be set before libcurl will send and _automatically uncompress_ Accept-Encoding (of course it needs to be built with zlib first).

If I pass `cpr::Header{{"Accept-Encoding", "compress, gzip"}` then I just get back gzipped data, which is not what I want.

**Comment by leviliangtw** [comment]
Now, `CURLOPT_ACCEPT_ENCODING` has already been set to "" for all built-in supported encodings and could be customized using `SetAcceptEncoding`. 

The following is an example to use `SetAcceptEncoding` and check the `Content-Encoding` in the header: 

```cpp
Url url{"https://www.example.com/"};
Session session;
session.SetUrl(url);
session.SetAcceptEncoding({{AcceptEncodingMethods::deflate, AcceptEncodingMethods::gzip, AcceptEncodingMethods::zlib}});
Response response = session.Get();

for (const auto& header : response.header) {
    std::cout << header.first << ":" << header.second << std::endl;
}

/*
Age:237159
Cache-Control:max-age=604800
Content-Encoding:gzip
Content-Length:648
Content-Type:text/html; charset=UTF-8
Date:Thu, 21 Jul 2022 17:32:33 GMT
Etag:"3147526947+gzip"
Expires:Thu, 28 Jul 2022 17:32:33 GMT
Last-Modified:Thu, 17 Oct 2019 07:18:26 GMT
Server:ECS (oxr/8328)
Vary:Accept-Encoding
X-Cache:HIT
*/
```

@COM8, I think this issue could be closed directly.

**Comment by COM8** [comment]
Agree. Thanks @leviliangtw .
