### ISSUE TITLE
Better Session::SetHeader() implementation

### ISSUE THREAD

**Issue by kaplomat** [libcpr/cpr#265]
Currently, `SetHeader()` method sets completely new HTTP header every time `cpr::Header` arg is set in `cpr::Post` (or whatever). If we set several different args like that, they will get overriden.

It would be nice to have a possibility to set headers from different sources, for example when injecting params and headers to the request by different helpers.

    template<class ...Ts>
    cpr::Response myPost(Ts&& ...ts) {
        return cpr::Post(
            std::forward<Ts>(ts)...,
            cpr::Header{ { "Authorization", "PuppyMaster" } });
    }
    
    auto resp = myPost(
        cpr::Url{ "http://service.com/puppies" },
        cpr::Header{ { "Content-Type", "application/json" } }
        cpr::Body{ myPuppy });

This code will make only "Injected: Header" header be sent, "Content-Type" header is ignored and the web service we invoke gets grumpy.

This can be easily fixed. I may prepare a PR next week if you want to be an expected behavior.

If the current behavior is expected, how else could I handle the issue? I.e. how can I inject request headers **easily**?

**Comment by simon-berger** [comment]
I intend to work on this issue within the next half year. Would be happy if I can be assigned to the issue
