### ISSUE TITLE
Is there a way to get the full URL for a request?

### ISSUE THREAD

**Issue by p0fi** [libcpr/cpr#270]
Hello,

is it possible to get the URL string including all added parameters with cpr?

If I construct a session like this e.g.

```c++
cpr::Session session;
auto url = cpr::Url{"http://www.httpbin.org/get"};
auto parameters = cpr::Parameters{{"hello", "world"}};
parameters.AddParameter({"hello2", "world2"});
session.SetOption(url);
session.SetOption(parameters);
```

Can I get a string like this `http://www.httpbin.org/get?hello=world&hello2=world2` somehow?

**Comment by 013ez** [comment]
I also need access for a request data (for using in my tests).

**Comment by Kumar-Kishan** [comment]
@p0fi 
`auto response = session.Get()`
`std::cout<< response.url`

This way you can get the url. But it requires you to make a call first.

**Comment by jungletek** [comment]
It's in the documentation, FYI: https://whoshuu.github.io/cpr/advanced-usage.html

See the first block of code that shows the public member variables of the Response object.

**Comment by n-bes** [comment]
Using a response object it's bad idea for unit-testing.

**Comment by xloem** [comment]
Glancing through the source it looks like the best remaining existing option for users here might be along the lines of `url + "?" + parameters.GetContent({})` which appears to be what cpr does internally.  Haven't tried it myself.

https://github.com/whoshuu/cpr/blob/ffe3f7ca261d15fd07b7790609e2597de35c851d/cpr/curl_container.cpp#L26

**Comment by COM8** [comment]
Yes, I can confirm this. there is currently nothing like a `cpr::Request` object stored in the `cpr::Response` object, containing such information.
This is something I'm already looking into and something I'd like to add in the future.

**Comment by COM8** [comment]
As far as I can see, there is also nothing in curl, which allows us to easily implement this. So I'm pushing this back.

**Comment by simon-berger** [comment]
I would like to have a look at that. Can you assign me to the issue?
