### ISSUE TITLE
Please make a NuGet package. That can help add your library to project easier

### ISSUE THREAD

**Issue by CODER591** [libcpr/cpr#297]

**Comment by SHRKV2** [comment]
Yes please.

**Comment by COM8** [comment]
Would you like to create a PR for this?
Since I do not know anything about how to create a NuGet package.

As an alternative I can suggest either to use [conan](https://conan.io/) or [vcpkg](https://github.com/whoshuu/cpr#building-cpr---using-vcpkg).

**Comment by CODER591** [comment]
I would take it into investigation.
Seems like this is possible to do.
Hope it will end with PR =)

**Comment by COM8** [comment]
Thanks!

**Comment by simon-berger** [comment]
Since there is no Nuget Packet yet (please correct me if I am wrong), I would like to work on it :)
