### ISSUE TITLE
homebrew version needs an share lib which contain cprConfig.cmake in it

### ISSUE THREAD

**Issue by cxwx** [libcpr/cpr#414]
the cprConfig.cmake should be install on `/usr/local/Cellar/cpr/1.5.0/lib/cmake/` or other similar path.
need to modify CMakeLists.txt to install the single file to the path.

**Comment by COM8** [comment]
Ping @KingKili .

**Comment by COM8** [comment]
I do not know anything about how to install files on macOS.
Are you able to provide a PR for this?

**Comment by cxwx** [comment]
I'm not sure the file if cpr-config.cmake should be install by hand.
I think if it could be install automatically by CMakeLists.txt
for example 
`https://github.com/root-project/veccore/blob/master/CMakeLists.txt`

```
write_basic_package_version_file(cmake/VecCoreConfigVersion.cmake
  VERSION ${VecCore_VERSION} COMPATIBILITY SameMajorVersion)

configure_package_config_file(cmake/VecCoreConfig.cmake.in cmake/VecCoreConfig.cmake
  INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX}
  INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}
  PATH_VARS CMAKE_INSTALL_INCLUDEDIR
)
```

I'm still learning about cmake.

**Comment by COM8** [comment]
@KingKili , what do you think about this?

**Comment by KingKili** [comment]
I need to read in my self on how to install those config files. But I don't think this should happen by hand. There was also #374 which tried to achieve this. Once I have time on spare I can give it a shot myself.

**Comment by COM8** [comment]
Closing this one, since this has been fixed: https://github.com/libcpr/cpr/blob/master/cpr-config.cmake
