### ISSUE TITLE
How could I use MBedTLS for SSL?

### ISSUE THREAD

**Issue by SeanOMik** [libcpr/cpr#420]
Is there a way I could use MBedTLS for curl? I tried to do this:
```cmake
set(USE_WINSSL OFF)
set(USE_OPENSSL OFF)
set(CMAKE_USE_WINSSL OFF)
set(CMAKE_USE_OPENSSL OFF)
set(CMAKE_USE_MBEDTLS ON)
```
But when I create a get request, I get no response with this error: `Cert verify failed: BADCERT_NOT_TRUSTED` 

Is there a way I could use MBedTLS with CPR?

**Comment by COM8** [comment]
Currently I do not think we support `MBedTLS`, only `OpenSSL` and `WinSSL`.
This should be possible to add through.

**Comment by SeanOMik** [comment]
Okay I'll just use WinSSL. I'm also having issues with OpenSSL on Linux, but I'll create a separate issue for it.

**Comment by COM8** [comment]
@KingKili do you have time to add `MBedTLS` support?

**Comment by COM8** [comment]
https://github.com/libcpr/cpr/pull/714 adds a mew option to enable Mbed TLS.
