### ISSUE TITLE
cpr-config.cmake for find_package

### ISSUE THREAD

**Issue by yairBAR-caja** [libcpr/cpr#455]
Hi,

I cannot find_package() cpr.
I saw the direction to use fetch_content(), but we would really prefer to use find_package() since were downloading a release and installing as a local lib.

i see you have a cpr-config.cmake but it is not being installed to /usr/local/lib/cmake and also the file itself does not point to the path where the header files are (/usr/local/include). 

Can you please add the ability to find_package() cpr? (right now im actually editing your files locally in-order for find_package() to work, which seems un-natural). 

-Yair

**Comment by COM8** [comment]
`fetch_content()` should be way to go.

The situation with `find_package()` is complicated right now.
I don't think it's working right now. @KingKili was playing around with it a bit but like I remember it never actually worked.
Also there was a PR aiming to introduce this to CPR but it stalled (#374).

Do you know more about the inner workings of `find_package()` and how to configure it correctly?

**Comment by COM8** [comment]
If so, would you like to create a PR with your changes for the `find_package()` configuration?

**Comment by yairBAR-caja** [comment]
Hi, thanks for the reply COM8, im no cmake expert, but i think the issue is that cpr-config.cmake is not being installed to /usr/local/lib/cmake/ which i think is the natural path for find_package() to look for a -config.cmake if it cant find the package in any other means.

I found [this article](https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/How-To-Find-Libraries#:~:text=The%20find_package()%20command%20will,found%2C%20it%20looks%20for%20Config.) on it :
**"The [find_package()](http://www.cmake.org/cmake/help/cmake-2-8-docs.html#command:find_package) command will look in the module path for Find.cmake, which is the typical way for finding libraries. First CMake checks all directories in ${CMAKE_MODULE_PATH}, then it looks in its own module directory <CMAKE_ROOT>/share/cmake-x.y/Modules/."

If no such file is found, it looks for Config.cmake or -config.cmake, which are supposed to be installed by libraries (but there are currently not yet many libraries which install them) and that don't do detection, but rather just contain hardcoded values for the installed library.** 

so it appears that cpr-config.cmake needs to be installed to /usr/local/lib/cmake/ and it needs to point the path to /usr/local/include/cpr and the cpr root library to /usr/local/lib.

I think the cpr-config.cmake should be something like:
"""
find_path(CPR_INCLUDE_DIR
          NAMES cpr.h
	  NAMES cpr/cpr.h
	  PATHS /usr/local/include/cpr)

find_library(CPR_LIBRARY
                   NAMES cpr
                   HINTS ${CPR_LIBRARY_ROOT}
		   NAMES cpr
		   PATHS 	/usr/local/lib)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(CPR REQUIRED_VARS CPR_LIBRARY CPR_INCLUDE_DIR)

if(CPR_FOUND)
    set(CPR_LIBRARIES ${CPR_LIBRARY})
    set(CPR_INCLUDE_DIRS ${CPR_INCLUDE_DIR})
endif()
"""

**Comment by yairBAR-caja** [comment]
Id make a PR but as im no where near being an expert i dont know how to make cpr install the-config.cmake file to /usr/local/lib/cmake/.

**Comment by yairBAR-caja** [comment]
ok it works but apparantly i was wrong about /usr/local/lib/cmake/ it is not the natural place for cmake to look.
however, find_package() works if i do the following:
i make the changes to the cpr-config.cmake (as i mentioned in the previous comment) and move it manually to /usr/local/lib/cmake and then in my project's cmakelists.txt i write the following.

set ( CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} /usr/local/lib/cmake)
find_package ( CPR REQUIRED )
include_directories ( ${CPR_INCLUDE_DIRS} )

and it works. i am able to compile and use cpr in my project.

**Comment by COM8** [comment]
OK.
Perhaps @KingKili has some time later this month to sort this out.
If not, I will try to read in it a fix it.

**Comment by yairBAR-caja** [comment]
Thanks COM8 :+1:

**Comment by tusooa** [comment]
Just in case, I have been using this Findcpr.cmake https://gitlab.com/kazv/libkazv/-/blob/servant/cmake/Findcpr.cmake with no problem.

**Comment by COM8** [comment]
Done in #645.
