### ISSUE TITLE
Feature request: Expose version information via preprocessor macros

### ISSUE THREAD

**Issue by mikedld** [libcpr/cpr#457]
Given that the upcoming v1.6.0 brings some API changes (and there obviously have been such changes in the past), it would be nice if there was a way to check for library version in downstream C++ code that uses it w/o manually defining the macros and/or checking whether this or that class has this or that method or field or whatever.

**Comment by COM8** [comment]
Well, the existing API should stay the same. Even when adding features like #288, this should not change the API.
The plan for all the upcoming C++17/20 features is to make them optional (at least for the near future). You can read more about this [here](https://github.com/whoshuu/cpr/issues/382#issuecomment-633873017).

**Comment by COM8** [comment]
But all in all, I think exposed version macros are a good idea.

**Comment by mikedld** [comment]
I was actually talking in terms of #443 which changes `Parameters` interface (exposed `content` field and `AddParameter` method before, `GetContent` and `Add` methods after). I'm using it to sign the query parameters by creating a `Parameters` variable and adding another parameter at the end containing the signature based on all the parameters (excluding the signature itself), i.e. value stored in `content` (and now returned by `GetContent`).
