### ISSUE TITLE
Loading certificates from buffer

### ISSUE THREAD

**Issue by Eran-YT** [libcpr/cpr#483]
Hi,
I wanted to load certificates from a buffer instead of from a file, CURL seems to be able to do it, but I couldn't find any way to do it with CPR.
Is there any way to do this?

**Comment by COM8** [comment]
No, there is currently no way to do this.

**Comment by alysondeives** [comment]
I can work on this

**Comment by simon-berger** [comment]
If the issue has not yet been resolved elsewhere, I would like to work on it.

**Comment by COM8** [comment]
As far as I'm aware, it's currently only possible to load ssl-key blobs.
