### ISSUE TITLE
Multithreaded download support!

### ISSUE THREAD

**Issue by cathaysia** [libcpr/cpr#501]
Hi, wherther multithreaded download be considered or not? Or cpr has this fuction already?
In some occasion, multithreaded download is very important.

**Comment by COM8** [comment]
Currently there is no way to do this in CPR, but this would be a nice feature.
Any chance you'd like to create a PR for this?

**Comment by cathaysia** [comment]
Although I like it, sure. But I don't have the  experience of developing libcurl. I'm afraid I don't have the ability to do this. Maybe I can do it next time.
________________________________

**Comment by cnSchwarzer** [comment]
I think this is out of the cpr's duty, this is an application level design, probably what cpr can do is to provide an API for download in an buffer not return in the resp.text.

**Comment by ishansheth** [comment]
Hi, I am using cpr to download the file from server and i get the whole file content as HTTP response body in resp.text. The type of this is std::string and i write this string in the file. what would be the limit of the size of the file that i can download from the server?

**Comment by tomaszewskip** [comment]
Hi, I have a patch, which adds `AsyncResponse DownloadAsync(std::string local_path, Ts... ts)` to the CPR 1.6.2. I would like to share it, but I do not see any option to attach a patch file (nor plain text) here.

**Comment by KingKili** [comment]
Cool, can you create a PR with your changes?

**Comment by COM8** [comment]
@tomaszewskip https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request might help. Let us know if you need help with that.

**Comment by tomaszewskip** [comment]
Please see PR: https://github.com/libcpr/cpr/pull/698
