### ISSUE TITLE
Reserve space beforehand for large download

### ISSUE THREAD

**Issue by Rockybilly** [libcpr/cpr#530]
Greetings,

It would appear currently, the response body is returned using a std::string but no reserving space method is provided to the calling application.

If a large download is requested, this would cause many unnecessary reallocs and memmove's, that would decrease the performance of this program.

It is true that in stuff like chunked encoding, the size cannot be known before the download, but there should be an option for this if the caller does not have any memory issues and just wants performance.

    std::string response_string;
    std::string header_string;
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, cpr::util::writeFunction);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response_string);
    curl_easy_setopt(curl, CURLOPT_HEADERDATA, &header_string);

If I am not mistaken, this is where the stuff happens. It would be beneficial, if the response_string was reservable.

**Comment by COM8** [comment]
Yes, this would be a nice addition.
Would you like to create a PR for this?

**Comment by jsouquie** [comment]
Following the merge of PR #533, it is now easy to implement this feature.

As we discussed previously in #533, it would be exposed through a method of the Session class. Something like `void Session::ReserveResponseText(size_t capacity)`.

One additional decision to make: should the user be required to call this method before each request, or should the capacity  be "sticky" and apply to all requests made using this session (this implies that the capacity has to be stored as a member of Session) ? I have a slight preference for making it not sticky.

Please tell me if that design and naming is OK with you, and I'll create the PR.

```cpp
cpr::Session session;
for (  ... )
{
    session.SetUrl(url);
    session.ReserveResponseText(256*1024); // not sticky: must be called for each iteration
    std::string result = session.Get().text;
}
```

**Comment by COM8** [comment]
@jsouquie I also agree with you. Making it sticky, does make sense.
Things we also have to think about is, what happens in case we receive more than the reserved amount of data?
I think we should handle this by increasing the buffer (or let it `std::string` handle if we use `std::string::reserve`).
Never the less we should print something to `std::err` in case this happens and `cpr::Debug` is enabled.

Besides that `ReserveResponseText` sounds good to me.

**Comment by Rockybilly** [comment]
I recently switched to another http library (for my production purposes), but I still want to contribute, as a suggestion, after a meaningful space is reserved for the response body, letting `std::string` handle it is a more viable option. It's mostly a problem when it starts at default reserved and gets built up from there. For example if `std::string` starts with reserved space of 10 bytes. If the `realloc `algorithm is x2 each time, this would cause much `realloc`s (for example for a body of 100 kb). But if you, start it with like 10 kb (as a guess from the client), much less `realloc`s would be needed. Even this is a gain, and could be improved with better guesses.

Not to deviate too much from the subject, but I didn't want to open a new issue. But the main issue of my use case with cpr is, a new connection is opened each time when I made a request. My prod case couldn't afford this (among some other things). Just out of curiosity, how do you avoid this with cpr ? You use a session object, with each request you apply a new `session.SetUrl(url); ` ?

**Comment by COM8** [comment]
In general as long as the session object exists, the session will be kept alive.
Also in case you are performing a lot of different requests try using `session.SetUrl(url);` since curl can reuse existing connection (in case the URL does not change) and resources.

**Comment by zydxhs** [comment]
@Rockybilly To see PR https://github.com/whoshuu/cpr/pull/599, does it help you?
