### ISSUE TITLE
performance improvement curl_multi_perform and multiplexing

### ISSUE THREAD

**Issue by EMHussain** [libcpr/cpr#556]
libcurl support `curl_multi_perform `for asynchronous requests and also offers `curl_multi_fdset` to extract **fd_sets** to handle concurrent requests efficiently. As well as libcurl support **multiplexing and http/2** protocol to reusing a single connection to one server for multiple http requests to improve **performance** of requests-heavy applications. 
I am not able to find some thing like this in cpr or may be I missed that. Please inform if cpr is providing such functionality or cpr not providing it could be good new feature.

**Comment by COM8** [comment]
Currently cpr does not support this. But I agree. This would be a nice addition.
Would you like to create a PR for this?

**Comment by EMHussain** [comment]
Yes I will try to create a PR

**Comment by EMHussain** [comment]
@COM8 To achieve  `curl_multi_perform` i want to add like 

 cpr::MultiPerform mp;
 cpr::Session session1;
 session1.SetUrl(url);
 session1.SetHeader(header);
 mp.addMulti(session1);

 cpr::Session session2;
 session2.SetUrl(url);
 session2.SetHeader(header);
 mp.addMulti(session2);
 
 std::vector<Response> res = mp.GetMulti();
 
 would it be a good option or we can a better choice/design to perform `curl_multi_perform`

**Comment by COM8** [comment]
> @COM8 To achieve `curl_multi_perform` i want to add like
> 
> ```
> cpr::MultiPerform mp;
> cpr::Session session1;
> session1.SetUrl(url);
> session1.SetHeader(header);
> mp.AddMulti(session1);
> 
> cpr::Session session2;
> session2.SetUrl(url);
> session2.SetHeader(header);
> mp.AddMulti(session2);
> 
> std::vector<Response> res = mp.GetMulti();
> ```
> 
> would it be a good option or we can find a better choice/design to add `curl_multi_perform`

Looks good to me.

**Comment by simon-berger** [comment]
There was no PR for the issue yet, right? If so, I would be happy to work on it and create one.

**Comment by leviliangtw** [comment]
@COM8 @simon-berger 
Hi, I noticed this issue might cover another issue #154. 
Since Simon has already created a great PR, I suggested that you could link them together.

**Comment by COM8** [comment]
Agree. Thanks @leviliangtw !
