### ISSUE TITLE
Upload multiple files

### ISSUE THREAD

**Issue by DeerMaximum** [libcpr/cpr#563]
Hi,
it is possible to upload multiple files in the same multipart field?

Like this
```c++
cpr::Multipart data = cpr::Multipart{
            {"files" , MULTIPLEFILES}
    };
```

**Comment by leviliangtw** [comment]
@COM8, the PR [#793](https://github.com/libcpr/cpr/pull/793) is ready for this issue.

**Comment by leviliangtw** [comment]
@COM8 I created a doc PR [#29](https://github.com/libcpr/docs/pull/29) for this issue.
