### ISSUE TITLE
could not support gcc 4.8.2

### ISSUE THREAD

**Issue by ugenehan** [libcpr/cpr#578]
error:fucntion 'cpr::Authentication& cpr::Authentication::operator=(cpr::Authentication&&)' defaulted on its first declaration with an exception-specification that differs from the implicit declaration 'cpr::Authentication& cpr::Authentication::operator=(cpr::Authentication&&)'
Authentication& operator=(Authentication&& old) noexcept = default;

**Comment by COM8** [comment]
In case you are able to create a PR and a CI run for it. Sure.

**Comment by csflyer** [comment]
same error.

**Comment by COM8** [comment]
This issue will be closed since we new require a cpp17 compatible compiler for all versions of cpr >= 1.10.0.

More details: https://github.com/libcpr/cpr/releases/tag/1.9.0
