### ISSUE TITLE
Canot use File or Buffer convienince classes in a Post Body

### ISSUE THREAD

**Issue by RoryO** [libcpr/cpr#581]
This is a continuation of #212 . That issue states to use an http form. However, when working with APIs there is a use case for a post body with raw binary data, specified by `application/octet-stream`. For example, the [Microsoft Cognitive Services](https://westcentralus.dev.cognitive.microsoft.com/docs/services/computer-vision-v3-ga/operations/56f91f2e778daf14a499f21b) states:

> Request body
> Input passed within the POST body. Supported input methods: raw image binary or image URL. 

Explicitly stating that the post body is either an image url, when using `application/json` or the raw image data when using `application/octet-stream`. In this case it would be convenient to do

```c++
Response r = Post(Url(base_url),
                  Header({
                    {"Ocp-Apim-Subscription-Key", api_key},
                    {"Content-Type", "application/octet-stream"}
                  }),
                  Body(File("test.jpg")));
```
However, the template for Post does not accept a File or a Buffer. Instead, you have to read the file into memory manually and use the pointer and size in the Body constructor. This works perfectly fine

```
char *data = 0;
int handle = 0;
handle = open("test.jpg", O_RDONLY);
assert(handle != 0);
struct stat s = {};
fstat(handle, &s);
size = s.st_size;
data = static_cast<char *>(malloc(s.st_size));
read(handle, data, s.st_size);
assert(data);
close(handle);

Response r = Post(Url(base_url),
                  Header({
                    {"Ocp-Apim-Subscription-Key", api_key},
                    {"Content-Type", "application/octet-stream"}
                  }),
                  Body(data, s.st_size));

```

Since passing a raw pointer to the Body constructor works in this case, and there are real world use cases for raw binary data in a post request, I suggest the template to Body can also accept the File and Buffer convenience classes like Multipart does.

**Comment by COM8** [comment]
Yes, sure. Sounds reasonable.
Would you like to create a PR for this?

**Comment by RoryO** [comment]
Sure, I’ll take a stab at it.

**Comment by leviliangtw** [comment]
I'd like to take this issue.

**Comment by KingKili** [comment]
Sure go ahead. Just let me know when PR is ready. Thanks in advance!

**Comment by leviliangtw** [comment]
@KingKili @COM8 I created a new PR[#763](https://github.com/libcpr/cpr/pull/763).
