### ISSUE TITLE
Unable to find mechanism which is equivalent of CURL option `--location-trusted`

### ISSUE THREAD

**Issue by rahul-naik1** [libcpr/cpr#610]
I am not able to find the `--location-trusted` in code. I would like to pass the AUTH header to redirected location.
With this option, we can pass this information to redirected host, otherwise it's failing with unauthorsed error.

I found that `CURLOPT_UNRESTRICTED_AUTH` CURL option is to specify that. I didn't find this flag in the code.

Can you please help me with this?

Following is the sample CURL command which I am using
```
curl -i -X PUT http://host/url  \
  -H  "Authorization: <token>" \
  -L --location-trusted
```

**Comment by COM8** [comment]
Currently there is no build in support for this (https://curl.se/libcurl/c/CURLOPT_UNRESTRICTED_AUTH.html)

BUT, there currently exists a more or less undocumented way you can access curl directly:
https://github.com/whoshuu/cpr/blob/63bfcc6292bba06f9806994ee5474baadff48254/test/session_tests.cpp#L877-L899
Just make sure you link against curl for this :)
