### ISSUE TITLE
Any plan to support thread pool to instead of the std::async ?

### ISSUE THREAD

**Issue by portsip** [libcpr/cpr#633]
Since the std::async will cause massive threads...

**Comment by COM8** [comment]
What exactly do you mean with that?

**Comment by portsip** [comment]
> What exactly do you mean with that?

I see the CPR using std::async to implement the asynchronous call, but the std::async will lunch a new thread for each call, therefore, it may cause the application to create massive threads in the busy application.

**Comment by COM8** [comment]
Ah, OK.
No there are currently no plans to add a thread pool for `std::async` calls right now. 

But is this really a problem? Since for it to take affect you have to run at least a couple hundred request in a short amount of time.
Or do you have a concrete example for this?

**Comment by portsip** [comment]
> Ah, OK.
> No there are currently no plans to add a thread pool for `std::async` calls right now.
> 
> But is this really a problem? Since for it to take affect you have to run at least a couple hundred request in a short amount of time.
> Or do you have a concrete example for this?

In our application, we will use it to send about 3000 - 5000 requests/per second.

**Comment by COM8** [comment]
Ok, I see 😅.
Then this is definitely a problem.

Would you like to create a PR for this?

**Comment by portsip** [comment]
> Ok, I see 😅.
> Then this is definitely a problem.
> 
> Would you like to create a PR for this?

Will later, not this moment, thanks for the answer. :)

**Comment by mohsenomidi** [comment]
As far as I understood in the implementation inside the`std::async` the `curl_easy_init` function calls per thread and this is expensive function (Time overhead for initializing), and made the library slow and in the other hand creating large amount of threads based on requests made heavy load on the os and it is not good for enterprise environments.

I study on current implemented thread pools and the best implementation is the boost `boost::asio` I tried to use this library with pure libcurl, but on write callback functions it had strange behavior. and did not succeed.

**Comment by COM8** [comment]
Fixed by: https://github.com/ithewei/cpr/commit/d0c2f42f3d9a5d8c718c3eba2bd114d1603c4006
