### ISSUE TITLE
Mocking CPR

### ISSUE THREAD

**Issue by Leon0402** [libcpr/cpr#635]
Hi, 

I do have some code with cpr requests and I wonder how to test that code best.  Obviously I could run a fake server, but I think even better would be to have a Mock, so I can just configure what cpr should return without it actually making a request. 

I wonder if cpr provides any hooks for this or if this is a feature that could be supported?

**Comment by COM8** [comment]
CPR currently does not offer such an interface.
Since we rely so heavily on curl, it might make sense to see if curl offers something like this.
