### ISSUE TITLE
HTTP bad response exceptions

### ISSUE THREAD

**Issue by sixdenip** [libcpr/cpr#640]
**Is your feature request related to a problem? Please describe.**
When having to process a response of a request, it can be painful and repetitive to do a switch-case on all the possible code returned by a given API just to throw exceptions. 

**Describe the solution you'd like**
Having the equivalent of Python's Requests [raise_for_status()](https://docs.python-requests.org/en/latest/api/#requests.Response.raise_for_status) as class method of response with an Exception class, could be a solution that also follows this library philosophy.

Cheers and thanks for your work.

**Comment by COM8** [comment]
Good idea.
Any chance, you would like to create a PR for it?

**Comment by sixdenip** [comment]
Submitted PR #641

**Comment by COM8** [comment]
Closing this one since no response and missing interest in this feature.
