### ISSUE TITLE
No .a or .so in cpr/lib

### ISSUE THREAD

**Issue by AnassHmida** [libcpr/cpr#643]
Good morning 
im new to the cpr library and i wanted to link it to my tizen wasm project ,i cloned the library and build it using these commands :

```
cd cpr && mkdir build && cd build && cmake ..
make
sudo make install
```

then when i want to import the library , i used the c++ linker > library , i added the cpr/build/lib path ( -L ) and called cpr in my (-l ) , it  shows me an error saying 

wasm-ld: error: unknown file type: /Users/macOs/cpr/build/lib/libcpr.dylib

my question is why is there no .so or .a libraries generated ?? 

i appriacte any help

**Comment by AnassHmida** [comment]
When i remove the c++ library linker only c++ compiler > include ,

this error shows up

```
 wasm-ld: error: ./src/helloworld.o: undefined symbol: cpr::Session::Session()
wasm-ld: error: ./src/helloworld.o: undefined symbol: cpr::Session::Get()
wasm-ld: error: ./src/helloworld.o: undefined symbol: cpr::Session::~Session()
wasm-ld: error: ./src/helloworld.o: undefined symbol: cpr::Session::SetOption(cpr::Url const&)
```

im lost tbh

**Comment by KingKili** [comment]
> my question is why is there no .so or .a libraries generated ??

Reading your report, I assume you are running macOS, and it seems like you built cpr natively. Therefore, a dylib is built.
In order to link against cpr you must build it for WebAssembly, usually this is done using a toolchain. Generally I'd recommend including it a CMake Subproject.

**Comment by AnassHmida** [comment]
> > my question is why is there no .so or .a libraries generated ??
> 
> Reading your report, I assume you are running macOS, and it seems like you built cpr natively. Therefore, a dylib is built.
> In order to link against cpr you must build it for WebAssembly, usually this is done using a toolchain. Generally I'd recommend including it a CMake Subproject.

You are correct , im using MacOs.
as i mentioned , im new to all c++ oriented things , can you please provide me with a source that can help build the library using toolchain ? im lost.

**Comment by KingKili** [comment]
Unfortunately not really, usually you have some kind of CMake toolchain file in your WASM toolchain. 
This file will then be refereed during the configuration phase of CMake e.g. `cmake .. -DCMAKE_TOOLCHAIN_FILE=path/to/file`.
As a little pointer here are the corresponding [CMake Docs](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling).

**Comment by AnassHmida** [comment]
> Unfortunately not really, usually you have some kind of CMake toolchain file in your WASM toolchain.
> This file will then be refereed during the configuration phase of CMake e.g. `cmake .. -DCMAKE_TOOLCHAIN_FILE=path/to/file`.
> As a little pointer here are the corresponding [CMake Docs](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling).

Thank you for setting me on the right path , i highly appreciate it KING.

**Comment by KingKili** [comment]
No Problem
