### ISSUE TITLE
Serialize requests for later

### ISSUE THREAD

**Issue by nahall** [libcpr/cpr#667]
**Is your feature request related to a problem? Please describe.**
I have an application where it would be useful to build the entire HTTP request, including POST data, but not submit it right away, but rather serialize the request and save to disk so it can be submitted later.

**Describe the solution you'd like**
Serialization support in cpr would be useful. If there is currently a way to do this, please let me know!

**Describe alternatives you've considered**
It looks like curl_formget is built with this in mind but looks like it is deprecated.

**Comment by COM8** [comment]
Since this is nothing we can do, I will close this one for now.
