### ISSUE TITLE
Docker / CMake

### ISSUE THREAD

**Issue by FryingDutch** [libcpr/cpr#672]
Hi,

Im trying to use CPR in one of my existing projects, and have trouble getting to link it statically.
Since I am using docker multistage, i prefer to end up with one file at the end. On which all dependencies have been statically linked. 

However, I have trouble statically linking the libraries, and therefore get the errors:
#13 16.64 main.cpp:(.text.startup+0x1516): undefined reference to `cpr::Session::Session()'
#13 16.64 /usr/bin/ld: main.cpp:(.text.startup+0x1521): undefined reference to `cpr::Session::SetOption(cpr::Url const&)'
#13 16.64 /usr/bin/ld: main.cpp:(.text.startup+0x1531): undefined reference to `cpr::Session::Get()'
#13 16.64 /usr/bin/ld: main.cpp:(.text.startup+0x1539): undefined reference to `cpr::Session::~Session()'

The linking of the includes files is succesfull.
If you want to see my current state I have a small project set up for testing (https://github.com/FryingDutch/EW_LibraryHub).

Your help would be much appreciated.

**Comment by KingKili** [comment]
You forgot to a `target_link_library(fileServer PUBLIC cpr::cpr)` [CMakeLists](https://github.com/FryingDutch/EW_LibraryHub/blob/main/src/CMakeLists.txt). Also I can not see where you add cpr, if this is also missing either add a `fetch_content`, or a `find_package`.
I think this is no issue of cpr, therefore I will close it. But if you need further assistance, just answer this message, and I will happily further assist you.

**Comment by FryingDutch** [comment]
Actually I dont use it as documented. I am building CPR in my [DockerFile](https://github.com/FryingDutch/EW_LibraryHub/blob/main/Dockerfile). And this is ment for when I dont build using fetch content, since I wanna seperate the building of my own CMake from that of cpr. In the production stage the program I am building shouldnt have any .dll dependencies, therefore I wanna link cpr statically. However, I am able to link the headers, trough CMake, I am not able to link the libraries, and then see the OP for the errors I get. 

The issue is that if I

**Comment by KingKili** [comment]
Nethertheless your are required to tell CMake, to link against CPR.
The most simple solution I can think of ,is using the install target in the docket file. Than should be able to `find_package` CPR. If this works you than should be able to link against `cpr::cpr`.
