### ISSUE TITLE
Is there a chat room here somewhere to discuss issues?

### ISSUE THREAD

**Issue by bokket** [libcpr/cpr#673]
Hi.I am very interested in this library. It feels like there are several futures worth discussing, where can I find a place to discuss with committers? For example, `Matrix, discord, slack, telegram`, which I don't seem to see in the introduction...
Looking forward to your reply,thanks.

**Comment by KingKili** [comment]
Great Idea! I'd probably prefer something which is linked somehow to GitHub, but have nothing specific in mind.
Has anyone some experiences with such platforms?

**Comment by bokket** [comment]
I use all four frequently to connect with the open source community, and in general a table might roughly summarize them.

<!DOCTYPE html><meta http-equiv="content-type" content="text/html; charset=utf-8"><figure class="md-table-fig" cid="n2" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

  | Matrix | Discord | Slack | Telegram
-- | -- | -- | -- | --
Free | Y | Y | Y | Y
Save message limit | N | ? | Y | N
Maximum number of people | ? | ? | Y | N
Thread | N | N | Y | N
Github notifications | Y | Y | Y | Y
Channel | N | Y | Y | N

</figure><br class="Apple-interchange-newline">


In general, the `slack` paid version has more features and responds better to github; `Discord, matrix` free features are very average;`telegram` is suitable for timely communication. Of course, if more simple, in `gitter` is also a good choice!

**Comment by KingKili** [comment]
Thanks for the the nice overview. I think gitter fits best to what I have in mind. @COM8  what is your take?

**Comment by KingKili** [comment]
After a thorough discussion with COM8 we decided to opt for [gitter](https://gitter.im/libcpr/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link). Thanks again for the great idea!
