### ISSUE TITLE
Response encoding

### ISSUE THREAD

**Issue by ShellarFX** [libcpr/cpr#678]
I make a request for a site using this code, the site is in Russian.

```
#include <cpr/cpr.h>

cpr::Session session;

session.SetUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36");
session.SetTimeout(4000);
session.SetHeader({ {"content-type", "text/plain; charset=utf-8;"} });
session.SetUrl("url");

cpr::Response r = session.Get();
std::cout << r.text << std::endl;
```

The problem is that the Russian letters are not specified correctly.  The console encoding is CP1251, i.e.  if you manually specify Russian letters for printing to the console, then everything is displayed as it should.  What is the problem?

![D5C18D56-CBF3-4EF5-9BB1-48B770546630](https://user-images.githubusercontent.com/47797922/140662105-969d7be1-27cd-4fda-a950-ff1d49d4b416.png)

**Comment by COM8** [comment]
This could be because by c++ not having proper `utf-8` support for `std::string` and therefore `std::cout`.
You might need to interpret your text your self. https://stackoverflow.com/a/50407375
What version of c++ do you use?

**Comment by COM8** [comment]
And you are using `CP1251` as encoding for your terminal, but you request the text as `utf-8`.

**Comment by ShellarFX** [comment]
Thanks! I have solved this problem. I'm using C++20
