### ISSUE TITLE
Building as static library doesn't include libssl and libcrypto

### ISSUE THREAD

**Issue by feedhandler** [libcpr/cpr#679]
Hi, thanks for creating this library, it's really great.

When I build as a static library, like this
```
cmake -DBUILD_SHARED_LIBS=OFF
```
it works OK, and creates libcpr.a, libcurl-d.a, and libz.a

However, when I try to build my app using those static libs, I get linker errors about undefined references to functions from libcrypto and libssl. 

Is there a way to bundle those two libs together with the three that are currently generated?

**Comment by KingKili** [comment]
Sorry for the late responce, I was quiet busy lately. 

You are right, we always use the system curl on your system, therefore it will not be built static. But you can also try setting `OPENSSL_USE_STATIC_LIBS=True` see [cmake docs](https://cmake.org/cmake/help/latest/module/FindOpenSSL.html).
Let me know if this already helps.

**Comment by feedhandler** [comment]
Thanks. Unfortunately adding that flag gives another error:

```
-- Automatically detecting SSL backend.
-- Detecting SSL backend...
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found version "1.0.2k")
CMake Error at CMakeLists.txt:81 (message):
  No valid SSL backend found! Please install OpenSSL or disable SSL by
  setting CPR_ENABLE_SSL to OFF.
```

I'm not able to change the machine libs, so I guess I will have to use the shared build.

Thanks
