### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by daixtrose** [libcpr/cpr#680]
## Description

The following  rather innocent code that once used to work stopped working a few weeks ago:

```c++
cpr::Url url{ "https://api.github.com/graphql" };
cpr::Bearer bearer{ programOptions.gitHubAccessToken };

cpr::Body body{ query }; // ommited, since irrelevant
cpr::Response response = cpr::Post(url, bearer, body);

fmt::print(
    "- status_code: '{}'\n- error: '{}'\n",
    response.status_code,
    response.error.message);
```

## Expected Behavior

A response containing useful data 

## Actual Behavior

This code yields

```
- status_code: '0'
- error: 'SSL certificate problem: unable to get local issuer certificate'
```

In a crosscheck I can reach the GitHub server with a bash shell script, so something else must be wrong. Any idea?

## Possible Fix

-

## Steps to Reproduce

See code above.

## Context

I am trying to use code that used to work before. 

## Your Environment

* Version used: Checked with master and v1.6.2
* Where did you get it from: clone from github
* Operating System and version: WSL2 (Ubuntu 20.04) on Windows Host.
* Link to a small example: n.a.

**Comment by KingKili** [comment]
Can you please try the latest cpr Version from master, since we fixed a SSL issue.
If this does not do the trick, I would recommend you to use system curl as a workaround for now, `CPR_FORCE_USE_SYSTEM_CURL=ON`

**Comment by daixtrose** [comment]
Many thanks! The update fixed it. Is a new release planned?

**Comment by KingKili** [comment]
> Many thanks! The update fixed it. Is a new release planned?
Should be, and will be!

**Comment by daixtrose** [comment]
Sorry, folks. I pulled the latest updates from `master` today and now the error is back. Could you please check again?

**Comment by daixtrose** [comment]
The error seems to stem from a tainted build. It seems CMake does not correctly recognize the update of cpr. Deleting everything in `build` and a complete rebuild fixes the issue again. Sorry for the noise, I should have checked before reopening.

**Comment by gerardcarbo** [comment]
Using the master branch we still are experiencing the error: 'SSL certificate problem: unable to get local issuer certificate' in a POST with body https request. Configuring CPR_FORCE_USE_SYSTEM_CURL=ON solved the problem.
