### ISSUE TITLE
Can't static link visual studio 2019

### ISSUE THREAD

**Issue by vende11s** [libcpr/cpr#681]
I can't compile statically due to this error:
![image](https://user-images.githubusercontent.com/74505994/142781252-4d6a59e6-bc25-4211-ade3-76d8cd58d2c8.png)
Anyone knows how to repair it?

**Comment by KingKili** [comment]
How did you include cpr?

**Comment by vende11s** [comment]
#include<cpr/cpr.h>

**Comment by KingKili** [comment]
Sorry I worded my question wrong.
How did you install cpr (conan, vcpg, ...).
Did you specify in install method that you want to build cpr statically?

**Comment by vende11s** [comment]
I've used vcpkg without specifying anything, just commands from readme

**Comment by vende11s** [comment]
I didn't see #361 before, after that i've got these errors:
![image](https://user-images.githubusercontent.com/74505994/142913702-05b2b539-e5dc-40b6-a866-bff5536d6fd1.png)
Then I added `CURL_DISABLE_LDAP;CURL_STATICLIB;` to preprocessor definitions and 
` libcurl.lib;ws2_32.lib;winmm.lib;wldap32.lib;Crypt32.Lib;` to Linker->Input->Additional dependencies
That was the answer, thanks for help!
