### ISSUE TITLE
Segmentation fault on cpr::Parameters construction

### ISSUE THREAD

**Issue by mfouesneau** [libcpr/cpr#685]
```c++
cpr::Parameters parameters = cpr::Parameters{{"hello", "world"}, {"stay", "cool"}};
```
```
received signal SIGSEGV, Segmentation fault.
0x00007f0bf1bd09ed in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
```

## Description

I can use cpr with a complete URL, even manually adding the parameters. However, using `Parameters` would make it easier.

I get a segmentation fault at the construction.

## Your Environment

* Version used: 1.6.2 (from conan repository)
* Where did you get it from (e.g. conan, vcpkg, master, ...): conan
* Operating System and version: linux ubuntu
* Link to a small example:

**Comment by COM8** [comment]
Thanks for reporting. Could you please provide a minimal example project, where this Segmentation fault happens?

**Comment by mfouesneau** [comment]
The project is minimal
```c++
#include <iostream>
#include <exception>
#include <stdexcept>
#include <cpr/cpr.h>
int main(){

cpr::Parameters parameters = cpr::Parameters{{"hello", "world"}, {"stay", "cool"}};  // Seg fault

...
return 0;
}

**Comment by COM8** [comment]
Could you please provide a minimal example with your build system since I can not reproduce it.

**Comment by mfouesneau** [comment]
This is a messy project https://github.com/mfouesneau/blackbodystars
but you can see the [src/cpr_test.cpp](https://github.com/mfouesneau/blackbodystars/blob/main/src/cpr_test.cpp)

My best guess is that I must be missing a linked library but I do not see which one.

**Comment by COM8** [comment]
Thanks! I will have a look at it tomorrow.

**Comment by COM8** [comment]
OK, I was able to reproduce this error. It looks like something is broken with the conan package. @KingKili do you have time to update the conan package to 1.7.0?

**Comment by COM8** [comment]
Like mentioned here: https://github.com/libcpr/cpr#building-cpr---using-conan

Please try adding `add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)` to your CMakeLists.txt

**Comment by mfouesneau** [comment]
Thanks! Since I was getting seg fault, I did not expect this was the issue.
