### ISSUE TITLE
(0xC0000135) error, using example code

### ISSUE THREAD

**Issue by spralja** [libcpr/cpr#693]
I'm getting this error code when attempting to run the example code provided in the README: 
```
#include <cpr/cpr.h>

int main(int argc, char** argv) {
    cpr::Response r = cpr::Get(cpr::Url{"https://api.github.com/repos/whoshuu/cpr/contributors"},
                               cpr::Authentication{"user", "pass"},
                               cpr::Parameters{{"anon", "true"}, {"key", "value"}});
    r.status_code;                  // 200
    r.header["content-type"];       // application/json; charset=utf-8
    r.text;                         // JSON text string
}
```

CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.20)
project(api_test_2)

set(CMAKE_CXX_STANDARD 14)

add_executable(api_test_2 main.cpp)

include(FetchContent)
FetchContent_Declare(cpr GIT_REPOSITORY https://github.com/libcpr/cpr.git GIT_TAG 67e12da316754ff3c6c91b50aafb2658438f3c1e) # the commit hash for 1.7.0
FetchContent_MakeAvailable(cpr)

target_link_libraries(api_test_2 PRIVATE cpr::cpr)
```

But when I attempt to run a I am prompted by a return value (0xC0000135)

**Comment by COM8** [comment]
Is the main returning `0xC0000135)`? What OS are you running on?

**Comment by KingKili** [comment]
We are missing the return value for main in the example. Thanks, I will fix it!

**Comment by COM8** [comment]
> We are missing the return value for main in the example. Thanks, I will fix it!

But in theory then the compiler should automatically insert `return 0;` if nothing else goes wrong.

**Comment by spralja** [comment]
> Is the main returning `0xC0000135)`? What OS are you running on?

Yes; I am using Windows.

The problem is not the missing return statement.

This code produces the same invalid return value (the execution is terminated without executing the print statement):

```
#include <cpr/cpr.h>
#include <iostream>

int main(int argc, char** argv) {
    const cpr::Url URL{"https://api.github.com/repos/whoshuu/cpr/contributors"};
    std::cout << URL << std::endl;
    

    cpr::Response r = cpr::Get(cpr::Url{"https://api.github.com/repos/whoshuu/cpr/contributors"},
                               cpr::Authentication{"user", "pass"},
                               cpr::Parameters{{"anon", "true"}, {"key", "value"}});

    return 0;
}
```

Whereas, this code run's normally:

```
#include <cpr/cpr.h>
#include <iostream>

int main(int argc, char** argv) {
    const cpr::Url URL{"https://api.github.com/repos/whoshuu/cpr/contributors"};
    std::cout << URL << std::endl;


    
    return 0;
}
```
```
https://api.github.com/repos/whoshuu/cpr/contributors

Process finished with exit code 0
```

**Comment by georgeanderson** [comment]
@spralja Have you tested with another endpoint that doesn't require authentication?

**Comment by COM8** [comment]
@spralja Could you please try building this example project as I'm not able to reproduce your issues on Windows.
https://github.com/libcpr/example-cmake-fetch-content

**Comment by MaritimeMartin** [comment]
``` cpp
#include <iostream>
#include <cpr/cpr.h>

int main() {
    std::cout << "Hello, World!" << std::endl;
    cpr::Url url = cpr::Url{"http://www.httpbin.org/get"};
    // cpr::Response r = cpr::Get(url);

    std::cout << "Done" << std::endl;
    return 0;
}
```

When uncommenting the Get line it throws.
`Process finished with exit code -1073741515 (0xC0000135)`

**Comment by COM8** [comment]
@MaritimeMartin how do you build cpr?
Did you try building this example: https://github.com/libcpr/example-cmake-fetch-content

**Comment by spralja** [comment]
The provided example does work.

**Comment by COM8** [comment]
Hmmm... This is not the result I would have hoped for 😂😂.
Now it gets interresting. Probably next weekend I will have time to have a look at this again in detail.

**Comment by COM8** [comment]
OK, probably found the cause. Try adding this to your CMakeLists.txt:
```cmake
if(WIN32) # Install dlls in the same directory as the executable on Windows
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
endif()
```

On Windows you need to specify that CMake places the libraries inside the same dir like the executable if linking dynamically.
Or you could specify the lib paths when executing.

**Comment by spralja** [comment]
Yes, that seemed to be the problem. Thanks
