### ISSUE TITLE
can't find system curl

### ISSUE THREAD

**Issue by christk1** [libcpr/cpr#694]
I tried to enable system curl with ```CPR_FORCE_USE_SYSTEM_CURL=ON```  by building using cmake but I get the following error:
```
CMake Error at build/_deps/cpr-src/CMakeLists.txt:159 (message):
  Curl not found on this system.  To use the build in version set
  CPR_FORCE_USE_SYSTEM_CURL to OFF.
```
I am using ubuntu 21.04 and curl is installed in my system:
```
curl 7.80.0 (x86_64-pc-linux-gnu) libcurl/7.80.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 zstd/1.4.4 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3 libgsasl/1.8.1 OpenLDAP/2.4.49
Release-Date: 2021-11-10
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp curl 7.80.0 (x86_64-pc-linux-gnu) libcurl/7.80.0 Opecurl 7.80.0 (x86_64-pc-linux-gnu) libcurl/7.80.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 zstd/1.4.4 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3 libgsasl/1.8.1 OpenLDAP/2.4.49
```
I need to enable system curl because I am using smtp which is not supported by the curl installed along with cpr.
Is there any way of enabling smtp or use the system curl?

**Comment by COM8** [comment]
How did you install `libcurl` since this looks like you are missing the developer package for it?
Please try: `sudo apt install libcurlpp-dev`

Is there a specific reason you need SMTP for? I'm asking since if its general enough we could enable it for the build in version as well.

**Comment by christk1** [comment]
libcurl is preinstalled with the distro. I am using SMTP to send emails using simple curl functions

**Comment by COM8** [comment]
But why would you then use cpr for it? We do not provide any explicit interface for SMTP in libcurl.

**Comment by christk1** [comment]
I used cpr in my entire project for sending requests. I used native curl for emails as cpr does not support email sending.
I forked the repo and enabled smtp and other features of libcurl in the building process so my issue is fixed. Thanks for your support
