### ISSUE TITLE
add option to statically compile cpr (+dependencies)

### ISSUE THREAD

**Issue by shakfu** [libcpr/cpr#695]
The current option compiles the libcpr to a shared library. 

May I suggest an additional option to statically compile cpr.

Thanks

**Comment by KingKili** [comment]
I suppose [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html) is what you are looking for.
Please let me know if it does not work for you.

**Comment by shakfu** [comment]
Actually, I'm only getting `.dylib` (shared) libraries from the regular cmake compilation, I was looking for statically compiled libraries: with the `.a` suffix.

**Comment by KingKili** [comment]
Have set `BUILD_SHARED_LIBS` to false?
E.g. `cmake .. -DBUILD_SHARED_LIBS=FALSE`

**Comment by shakfu** [comment]
Thanks @KingKili . 👍 

That worked nicely. It's good to know in general (I just started using cmake).

**Comment by KingKili** [comment]
No problem, everyone starts at some point.
