### ISSUE TITLE
cpr.h includes a cpr/cprver.h which doesn't exist

### ISSUE THREAD

**Issue by shakfu** [libcpr/cpr#697]
Just tried to compile cpr and it gave an error because `cpr.h` includes a header `cpr/cprver.h`, but it doesn't exist in the source tree.

**Comment by KingKili** [comment]
cprver.h is generate by CMake and placed into the build directory. Usually CMake does take care to set the required include flags. But since you are facing issues, how did you build cpr?

**Comment by shakfu** [comment]
Thanks for the clarification. You are right. My bad.

It was a little confusing because the cmake bid also creates an `include` directory which was empty and I missed, somehow, the `cpr_generated_includes` directory which contains `cpr/cprver.h`

**Comment by KingKili** [comment]
Great, to hear that I could help.
