### ISSUE TITLE
Interface of Session object doesn't provide Async methods

### ISSUE THREAD

**Issue by bobjansen** [libcpr/cpr#70]
Currently it is not possible to call *Async or *Callback methods on the session object. I believe that this, combined with issue #69, makes it impossible to do write async code in combination with SSL keepalive in a practical way.

**Comment by binarytrails** [comment]
Is it still the case?

**Comment by jaskinn** [comment]
Yes. :(

**Comment by COM8** [comment]
Anybody here would like to create a PR for this?

**Comment by simon-berger** [comment]
I would like to take this issue and create a PR :)
