### ISSUE TITLE
How to set http proxies?

### ISSUE THREAD

**Issue by loganbaby** [libcpr/cpr#703]
How to set http proxies? Where can I find the documentation?

**Comment by loganbaby** [comment]
Can I do it like that?<br>
cpr::Post(cpr::Url(site), cpr::UserAgent{{__getRandomUserAgent()}},
                  cpr::Proxies{{"203.13.32.106", site}});

**Comment by COM8** [comment]
This might help: https://docs.libcpr.org/advanced-usage.html#using-proxies
