### ISSUE TITLE
Empty response text and status code 0 at example code

### ISSUE THREAD

**Issue by Pxddyk45** [libcpr/cpr#709]
## Code
```
#include <cpr/cpr.h>
#include <iostream>

int main(int argc, char** argv) {
    cpr::Response r = cpr::Get(cpr::Url{"https://api.github.com/repos/whoshuu/cpr/contributors"},
                      cpr::Authentication{"user", "pass"},
                      cpr::Parameters{{"anon", "true"}, {"key", "value"}});
    std::cout << r.status_code << std::endl << r.text;
    return 0;
}
```

## Expected Behavior
It should print the status code and the response body

## Actual Behavior
It prints 0

## Your Environment

* Where did you get it from (e.g. conan, vcpkg, master, ...): master
* Operating System and version: MacOS 12.1 
*  Build System: g++/clang++

**Comment by LilPidgey** [comment]
This is a vcpkg issue I believe.
Check https://github.com/libcpr/cpr/issues/704 and https://github.com/microsoft/vcpkg/issues/23417

**Comment by COM8** [comment]
What happens if you add the following:
```
std::cout << "Error Code: " << static_cast<int>(r.error.code) << '\n';
std::cout << "Error Message: " << r.error.message << '\n';
```

To me this looks like curl can not find certificates.

**Comment by Pxddyk45** [comment]
@LilPidgey i got it from master and not from vcpkg

**Comment by Pxddyk45** [comment]
@COM8 
```
0
Error Code: 4
Error Message: 
```

**Comment by COM8** [comment]
Error Code 4 is `INTERNAL_ERROR` reported by curl. Could you please provide a minimal example, where I can reproduce your issue?

**Comment by Pxddyk45** [comment]
> Error Code 4 is `INTERNAL_ERROR` reported by curl. Could you please provide a minimal example, where I can reproduce your issue?

curl --version: 
```
curl 7.77.0 (x86_64-apple-darwin21.0) libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0
Release-Date: 2021-05-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```
Code:
```
#include <cpr/cpr.h>
#include <iostream>

int main(int argc, char **argv)
{
    cpr::Response r = cpr::Get(cpr::Url{"https://api.github.com/repos/whoshuu/cpr/contributors"},
                               cpr::Authentication{"user", "pass"},
                               cpr::Parameters{{"anon", "true"}, {"key", "value"}});

    std::cout << r.status_code << std::endl;
    std::cout << "Error Code: " << static_cast<int>(r.error.code) << '\n';
    std::cout << "Error Message: " << r.error.message << '\n';
    return 0;
}
```

**Comment by COM8** [comment]
And how do you build your project? Please provide a link to either a repository or a zip file containing the example with your build system and instructions since I can not reproduce this.

**Comment by Pxddyk45** [comment]
> And how do you build your project? Please provide a link to either a repository or a zip file containing the example with your build system and instructions since I can not reproduce this.

https://workupload.com/start/u8QbEwypMp9

**Comment by COM8** [comment]
I can't compile your code since your are using dynamic libs which are not portable.
Any reason you do not use a build system like CMake.
Here is an example: https://github.com/libcpr/example-cmake-fetch-content

**Comment by HideakiAtsuyo** [comment]
Need to update vcpkg => https://github.com/microsoft/vcpkg/pull/23984

**Comment by COM8** [comment]
@Pxddyk45 Did you solve this issue? Do you need further help with that?

**Comment by Pxddyk45** [comment]
> @Pxddyk45 Did you solve this issue? Do you need further help with that?

no, still couldn't fix it, and i dont think i can fix it

**Comment by COM8** [comment]
https://github.com/curl/curl/issues/8741

**Comment by HpLightcorner** [comment]
#730 possible duplicate (using CMake build)

**Comment by Pxddyk45** [comment]
no it gives me segfault
