### ISSUE TITLE
Some questions about cpr

### ISSUE THREAD

**Issue by quorpz** [libcpr/cpr#710]
Hello, i have some questions about the library:
1. It works with socks4/socks5 proxies?
2. It works with multi-threading?

**Comment by COM8** [comment]
1. Yes: https://github.com/libcpr/cpr/issues/461
2. Yes, you can make parallel requests

**Comment by quorpz** [comment]
> 1. Yes: [Supporting Tor And Socks5 #461](https://github.com/libcpr/cpr/issues/461)
> 2. Yes, you can make parallel requests

and it works with socks4?

**Comment by COM8** [comment]
I guess so, since curl supports it too. Otherwise please let me know and I will have a look at it :)
