### ISSUE TITLE
Unable to CMAKE a project using libcpr on Ubuntu 20 using CLion

### ISSUE THREAD

**Issue by evanerwee** [libcpr/cpr#718]
Absolutely any help is welcome. I have been trying for a week, still no go.

######### Linux Distro ############

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

######### IDE ############
CLion 2021.3.4
Build #CL-213.7172.20, built on March 14, 2022
Licensed to Evan Erwee
Subscription is active until August 3, 2022.
Runtime version: 11.0.14.1+1-b1751.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.13.0-37-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 4
Registry:
    run.processes.with.pty=TRUE
    ide.balloon.shadow.size=0
    clang.parameter.info=true

Non-Bundled Plugins:
    ski.chrzanow.foldableprojectview (1.1.1)
    org.toml.lang (213.5744.224)
    lermitage.intellij.extra.icons (2022.1.1)
    com.vermouthx.idea (1.13.1)
    Key Promoter X (2021.3)
    mobi.hsz.idea.gitignore (4.3.0)
    org.rust.lang (0.4.166.4486-213)
    com.cherryleafroad.rust.playground (2.1.4-stable)
    artsiomch.cmake (213.1.5)
    artsiomch.cmake.plus (213.1.7)
    com.github.ArtsiomCh.NestedBracketsColorer (0.6.0)
    aws.toolkit (1.41-213)

Current Desktop: ubuntu:GNOME

######### Issue ############
```
===================[ Build | all | Debug ]=====================================
/snap/clion/184/bin/cmake/linux/bin/cmake --build /home/eerwee/repo/iamok/cmake-build-debug --target all
[193/212] Linking C shared library _deps/curl-build/lib/libcurl-d.so
FAILED: _deps/curl-build/lib/libcurl-d.so 
: && /usr/bin/cc -fPIC -pedantic -Wall -W -Wpointer-arith -Wwrite-strings -Wunused -Wshadow -Winline -Wnested-externs -Wmissing-declarations -Wmissing-prototypes -Wfloat-equal -Wsign-compare -Wundef -Wendif-labels -Wstrict-prototypes -Wdeclaration-after-statement -Wstrict-aliasing=3 -Wcast-align -Wtype-limits -Wold-style-declaration -Wmissing-parameter-type -Wempty-body -Wclobbered -Wignored-qualifiers -Wconversion -Wvla -Wdouble-promotion -Wno-long-long -Wno-multichar -Wno-format-nonliteral -Wno-sign-conversion -Wno-system-headers -g   -shared -Wl,-soname,libcurl-d.so -o _deps/curl-build/lib/libcurl-d.so _deps/curl-build/lib/CMakeFiles/libcurl.dir/altsvc.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/amigaos.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/asyn-ares.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/asyn-thread.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/base64.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/bufref.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/c-hyper.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/conncache.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/connect.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/content_encoding.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/cookie.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_addrinfo.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_ctype.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_des.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_endian.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_fnmatch.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_get_line.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_gethostname.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_gssapi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_memrchr.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_multibyte.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_ntlm_core.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_ntlm_wb.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_path.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_range.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_rtmp.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_sasl.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_sspi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_threads.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/dict.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/doh.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/dotdot.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/dynbuf.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/easy.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/easygetopt.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/easyoptions.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/escape.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/file.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/fileinfo.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/formdata.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/ftp.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/ftplistparser.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/getenv.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/getinfo.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/gopher.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/h2h3.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/hash.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/hmac.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/hostasyn.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/hostip.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/hostip4.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/hostip6.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/hostsyn.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/hsts.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/http.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/http2.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/http_chunks.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/http_digest.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/http_negotiate.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/http_ntlm.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/http_proxy.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/http_aws_sigv4.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/idn_win32.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/if2ip.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/imap.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/inet_ntop.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/inet_pton.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/krb5.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/ldap.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/llist.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/md4.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/md5.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/memdebug.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/mime.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/mprintf.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/mqtt.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/multi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/netrc.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/nonblock.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/openldap.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/parsedate.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/pingpong.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/pop3.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/progress.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/psl.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/rand.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/rename.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/rtsp.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/select.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/sendf.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/setopt.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/sha256.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/share.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/slist.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/smb.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/smtp.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/socketpair.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/socks.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/socks_gssapi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/socks_sspi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/speedcheck.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/splay.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/strcase.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/strdup.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/strerror.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/strtok.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/strtoofft.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/system_win32.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/telnet.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/tftp.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/timeval.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/transfer.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/url.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/urlapi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/version.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/version_win32.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/warnless.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/wildcard.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/cleartext.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/cram.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/digest.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/digest_sspi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/gsasl.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/krb5_gssapi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/krb5_sspi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/ntlm.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/ntlm_sspi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/oauth2.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/spnego_gssapi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/spnego_sspi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/vauth.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/bearssl.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/gskit.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/gtls.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/hostcheck.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/keylog.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/mbedtls.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/mbedtls_threadlock.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/nss.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/openssl.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/rustls.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/schannel.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/schannel_verify.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/sectransp.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/vtls.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/wolfssl.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/x509asn1.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vquic/ngtcp2.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vquic/quiche.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vquic/vquic.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vssh/libssh.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vssh/libssh2.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vssh/wolfssh.c.o  -Wl,-rpath,/usr/local/lib/x86_64-linux-gnu:  -ldl  -lpthread  /usr/lib/x86_64-linux-gnu/libssl.so  /usr/lib/x86_64-linux-gnu/libcrypto.so  /usr/local/lib/x86_64-linux-gnu/libz.so  /usr/local/lib/x86_64-linux-gnu/libssh2.a && :
/usr/bin/ld: /usr/local/lib/x86_64-linux-gnu/libssh2.a(sftp.c.o): relocation R_X86_64_PC32 against symbol `libssh2_sftp_dtor' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
[198/212] Building CXX object _deps/cpr-build/cpr/CMakeFiles/cpr.dir/cookies.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by evanerwee** [comment]
When compiling libcpr the issue remain. 

====================[ Build | all | Release ]===================================
/snap/clion/184/bin/cmake/linux/bin/cmake --build /home/eerwee/repo/cpr/cmake-build-release --target all
[197/211] Linking C shared library lib/libcurl.so
FAILED: lib/libcurl.so 
: && /usr/bin/cc -fPIC -pedantic -Wall -W -Wpointer-arith -Wwrite-strings -Wunused -Wshadow -Winline -Wnested-externs -Wmissing-declarations -Wmissing-prototypes -Wfloat-equal -Wsign-compare -Wundef -Wendif-labels -Wstrict-prototypes -Wdeclaration-after-statement -Wstrict-aliasing=3 -Wcast-align -Wtype-limits -Wold-style-declaration -Wmissing-parameter-type -Wempty-body -Wclobbered -Wignored-qualifiers -Wconversion -Wvla -Wdouble-promotion -Wno-long-long -Wno-multichar -Wno-format-nonliteral -Wno-sign-conversion -Wno-system-headers -O3 -DNDEBUG   -shared -Wl,-soname,libcurl.so -o lib/libcurl.so _deps/curl-build/lib/CMakeFiles/libcurl.dir/altsvc.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/amigaos.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/asyn-ares.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/asyn-thread.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/base64.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/bufref.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/c-hyper.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/conncache.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/connect.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/content_encoding.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/cookie.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_addrinfo.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_ctype.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_des.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_endian.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_fnmatch.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_get_line.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_gethostname.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_gssapi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_memrchr.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_multibyte.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_ntlm_core.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_ntlm_wb.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_path.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_range.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_rtmp.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_sasl.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_sspi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/curl_threads.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/dict.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/doh.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/dotdot.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/dynbuf.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/easy.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/easygetopt.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/easyoptions.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/escape.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/file.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/fileinfo.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/formdata.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/ftp.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/ftplistparser.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/getenv.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/getinfo.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/gopher.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/hash.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/hmac.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/hostasyn.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/hostcheck.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/hostip.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/hostip4.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/hostip6.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/hostsyn.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/hsts.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/http.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/http2.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/http_chunks.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/http_digest.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/http_negotiate.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/http_ntlm.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/http_proxy.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/http_aws_sigv4.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/idn_win32.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/if2ip.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/imap.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/inet_ntop.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/inet_pton.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/krb5.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/ldap.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/llist.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/md4.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/md5.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/memdebug.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/mime.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/mprintf.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/mqtt.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/multi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/netrc.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/non-ascii.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/nonblock.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/openldap.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/parsedate.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/pingpong.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/pop3.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/progress.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/psl.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/rand.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/rename.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/rtsp.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/select.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/sendf.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/setopt.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/sha256.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/share.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/slist.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/smb.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/smtp.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/socketpair.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/socks.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/socks_gssapi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/socks_sspi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/speedcheck.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/splay.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/strcase.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/strdup.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/strerror.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/strtok.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/strtoofft.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/system_win32.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/telnet.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/tftp.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/timeval.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/transfer.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/url.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/urlapi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/version.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/version_win32.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/warnless.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/wildcard.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/x509asn1.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/cleartext.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/cram.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/digest.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/digest_sspi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/gsasl.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/krb5_gssapi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/krb5_sspi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/ntlm.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/ntlm_sspi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/oauth2.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/spnego_gssapi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/spnego_sspi.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vauth/vauth.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/bearssl.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/gskit.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/gtls.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/keylog.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/mbedtls.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/mbedtls_threadlock.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/mesalink.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/nss.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/openssl.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/rustls.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/schannel.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/schannel_verify.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/sectransp.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/vtls.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vtls/wolfssl.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vquic/ngtcp2.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vquic/quiche.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vquic/vquic.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vssh/libssh.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vssh/libssh2.c.o _deps/curl-build/lib/CMakeFiles/libcurl.dir/vssh/wolfssh.c.o  -Wl,-rpath,/usr/local/lib/x86_64-linux-gnu:  -ldl  -lpthread  /usr/lib/x86_64-linux-gnu/libssl.so  /usr/lib/x86_64-linux-gnu/libcrypto.so  /usr/local/lib/x86_64-linux-gnu/libz.so  /usr/local/lib/libssh2.a && :
/usr/bin/ld: /usr/local/lib/libssh2.a(agent.c.o): relocation R_X86_64_PC32 against symbol `agent_ops_unix' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
[202/211] Building CXX object cpr/CMakeFiles/cpr.dir/session.cpp.o
ninja: build stopped: subcommand failed.

**Comment by COM8** [comment]
Could you please provide an example project where I can reproduce this?
I suggest you try using your system curl. Try configuring CMake with: `-DCPR_FORCE_USE_SYSTEM_CURL=ON`

**Comment by evanerwee** [comment]
Thank you, that helped. I am good now.
