### ISSUE TITLE
Add Interception  just like okhttp?

### ISSUE THREAD

**Issue by sornian** [libcpr/cpr#719]
build a client to manager request for change request/response  
for example 
we can use Interception to encrypt/decrypt body or add baseurl ,add public header

this is okhttp demo

```
public class TestInterceptor implements Interceptor {
    @Override
    public Response intercept(Chain chain) throws IOException {
 
        return null;
    }
}

OkHttpClient build = new OkHttpClient.Builder()
                .addInterceptor(new TestInterceptor())
                .build();
   

```

**Comment by COM8** [comment]
Sounds like an interresting feature, but I'd say it has a rather low priority for us since it would require restructuring large parts of cpr.
**But** you are always welcome to create a PR for that.

**Comment by simon-berger** [comment]
I would like to work on this issue and hopefully create a pull request in the next few weeks.
Can someone assign me to it?
