### ISSUE TITLE
Still Not Working

### ISSUE THREAD

**Issue by HideakiAtsuyo** [libcpr/cpr#721]
For Full Content see => Issue #720 

Even after the Pull Request [vcpkg#23984](https://github.com/microsoft/vcpkg/pull/23984) I updated vcpkg it still doesn't work.

No more details because everything is in the Issue #720 

![](https://i.imgur.com/6IPzdoX.png)

**Comment by HideakiAtsuyo** [comment]
@COM8

**Comment by COM8** [comment]
Sorry, but this is not a cpr issue. We do not maintain the vcpkg package. 
There is already an issue there: https://github.com/microsoft/vcpkg/issues/23417
