### ISSUE TITLE
Integration with Omnet++

### ISSUE THREAD

**Issue by juansebastiani2cat** [libcpr/cpr#724]
Dear all,

Perhaps this is somehow offtopic, so my apologies in advance. But, is there a way to integrate CPR into a working simulation ? I already managed to integrate CPR to a working Eclipse project, so I'm guessing there is a way to link the library into an OMNET++ simulation. I already tried linking it in a similar way as in Eclipse, in project properties -> Omnet++ -> Makemake -> Makemake Options -> link and include "cpr" in the -l option. But still says that is unable to find library -lcpr. 

Any help would be much appreciated.

**Comment by COM8** [comment]
To me this sounds like a broken link path in eclipse. Although I've never used OMNET.
I'd say this is possible if you configure OMNET as a proxy and then forward all requests this way.

**Comment by juansebastiani2cat** [comment]
I have solved the issue. I copied the copied the library dependencies (The .so, .zlib-ng and .1 files) into my usr/lib directory. After that, I included the library through 

`Project properties -> Omnet++ -> Makemake -> Makemake Options -> link`

and include "cpr" in the -l option. And now it's working.
