### ISSUE TITLE
Yo lok republicOfCheenDynasty.

### ISSUE THREAD

**Issue by lootnath** [libcpr/cpr#725]
Yo lok republicOfCheenDynasty.

**Comment by COM8** [comment]
Aha, this looks like a bug. Could you please elaborate your finding there a bit. As far as I'm aware it should be the time of the [Gsälzbär](https://www.aeffleundpferdle.shop/WebRoot/Store22/Shops/62303218/60EA/F074/5B42/A057/8D7E/0A0C/6D0C/361C/Gsaelzbaer_solo_white.jpg)-Dynasty.

**Comment by COM8** [comment]
No answer :, (
