### ISSUE TITLE
The POST method used after the CPR 302 redirect causes the server to return 405

### ISSUE THREAD

**Issue by ZRR666** [libcpr/cpr#729]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Where did you get it from (e.g. conan, vcpkg, master, ...):
* Operating System and version:
* Link to a small example:

The POST method used after the CPR 302 redirect causes the server to return 405
302 Failed to use GET in redirection

**Comment by COM8** [comment]
Please use the issue template and give a minimal example.

**Comment by ZRR666** [comment]
hi
After using POST, a 302 redirect is encountered and CPR continues to use POST resulting in 405

**Comment by ZRR666** [comment]
![image](https://user-images.githubusercontent.com/41984214/165056109-7788845f-4665-40f2-95fb-0547868dfeca.png)

**Comment by ZRR666** [comment]
![image](https://user-images.githubusercontent.com/41984214/165056221-0c115979-0df8-4a46-95a0-d79e6ef000f3.png)
At this point he uses the POST method for a 302 redirect

**Comment by ZRR666** [comment]
How can THE GET method be used to redirect pages
