### ISSUE TITLE
CMake FetchContent Examples are not working "out of the box" on MacOS and Windows when requesting https (SSL) endpoint

### ISSUE THREAD

**Issue by HpLightcorner** [libcpr/cpr#730]
When building the minimal cpr example using FetchContent on Windows and macOS, HTTPS (SSL) endpoints are not working. cpr responds with an `INTERNAL_ERROR` with no error message given. 

## Description
When building `cpr` with the following setup:
- CMake Build System (FetchContent minimum example)
- Clang (macOS) or MSVC (Windows)
- latest release
- SSL auto-detect (using platform-specific SSL implementation/library)
- `cpr` using "shipped/integrated" `curl`

and trying to query an HTTPS endpoint, the response indicates an INTERNAL_ERROR without a meaningful error message. I suspect the issue is within the underlying curl ssh implementation, some kind of config?

## Expected Behavior
- Minimum examples should be working without any further configuration
- `cpr` should give a meaningful error message on these internal errors
- `cpr` build should configure SSL backends correctly 

## Actual Behavior
Any request fails with `INTERNAL_ERROR`, no further message given.

## Possible Fix
Currently no suggestions, however, downgrading `cpr` to `v1.6.1` does solve all the issue. So I suspect breaking changes in `curl` which have not been fully reflected in `cpr`.

## Steps to Reproduce
Building miminum example on macOS (M1, Monterey 12.2) and Windows 10.
https://github.com/libcpr/example-cmake-fetch-content

## Context
Building minimum example shipped with `cpr`

## Your Environment
- `cpr` latest release
- Integrated/build with FetchContent CMake
- macOS (M1, Monterey 12.2) and Windows 10

**Comment by COM8** [comment]
This is currently a curl issue: https://github.com/curl/curl/issues/8741#issuecomment-1108286813

Later today I will work on a new cpr release where I downgrade curl to 7.80.0 to get around this issue.
