### ISSUE TITLE
Building cpr should check `LIBCURL_VERSION_NUM` before using `CURLOPT_SSLKEY_BLOB`

### ISSUE THREAD

**Issue by alebcay** [libcpr/cpr#732]
## Description
In the course of packaging cpr 1.8.1 for [Homebrew](https://brew.sh) (downstream PRs https://github.com/Homebrew/homebrew-core/pull/98161, https://github.com/Homebrew/homebrew-core/pull/100206), trying to build cpr 1.8.1 against macOS-provided cURL leads to errors when the system cURL is older than 7.71.0 (i.e. on macOS versions older than 12.x Monterey).

## Expected Behavior
Build should complete successfully using the macOS system curl.

## Actual Behavior
During the CMake configure step:
```
[...]
  -- Found CURL: /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/lib/libcurl.tbd (found version "7.64.1") found components: HTTP HTTPS 
  -- Curl 7.64.1 found on this system.
[...]
```

Build fails with the following error:
```
   [ 94%] Building CXX object cpr/CMakeFiles/cpr.dir/redirect.cpp.o
  cd /tmp/cpr-20220426-23293-rmi4y7/cpr-1.8.1/cpr && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DCPR_ENABLE_SSL -DCPR_FORCE_USE_SYSTEM_CURL -Dcpr_EXPORTS -I/tmp/cpr-20220426-23293-rmi4y7/cpr-1.8.1/include -I/tmp/cpr-20220426-23293-rmi4y7/cpr-1.8.1/cpr_generated_includes -Wall -Wextra -Wpedantic -Werror -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -fPIC -std=gnu++11 -MD -MT cpr/CMakeFiles/cpr.dir/redirect.cpp.o -MF CMakeFiles/cpr.dir/redirect.cpp.o.d -o CMakeFiles/cpr.dir/redirect.cpp.o -c /tmp/cpr-20220426-23293-rmi4y7/cpr-1.8.1/cpr/redirect.cpp
  /tmp/cpr-20220426-23293-rmi4y7/cpr-1.8.1/cpr/session.cpp:495:9: error: unknown type name 'curl_blob'
          curl_blob blob{};
          ^
  /tmp/cpr-20220426-23293-rmi4y7/cpr-1.8.1/cpr/session.cpp:498:41: error: use of undeclared identifier 'CURLOPT_SSLKEY_BLOB'
          curl_easy_setopt(curl_->handle, CURLOPT_SSLKEY_BLOB, &blob);
                                          ^
  2 errors generated.
  make[2]: *** [cpr/CMakeFiles/cpr.dir/session.cpp.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  make[1]: *** [cpr/CMakeFiles/cpr.dir/all] Error 2
  make: *** [all] Error 2
```

## Possible Fix

We noticed that there's already checks using [`LIBCURL_VERSION_NUM`](https://github.com/libcpr/cpr/search?q=LIBCURL_VERSION_NUM) throughout cpr. Per https://curl.se/libcurl/c/CURLOPT_SSLKEY_BLOB.html, `CURL_SSLKEY_BLOB` was introduced in cURL 7.71.0, so there should be a check on the version number before the usage of this symbol.

## Steps to Reproduce

1. Download cpr 1.8.1 source on a macOS machine running version Big Sur (11) or earlier (macOS comes with cURL; these OS versions have cURL versions <7.71.0).
2. Configure with CMake such that the system cURL is used. An example command line invocation is `cmake -S . -B build -DCMAKE_INSTALL_PREFIX=$(pwd)/output -DCPR_FORCE_USE_SYSTEM_CURL=ON`.
3. Verify in the CMake output that the system cURL backend is selected (path of found CURL should end in `libcurl.tbd`).
4. Run the build. An example command line invocation is `cmake --build build`. This should fail on building `session.cpp` with the error described above.

## Context

This has blocked cpr 1.8.1 from being shipped on Homebrew (and, more generally, prevents cpr 1.8.1 from being used on older versions of macOS without building/using a newer cURL version).

## Your Environment

* Version used: cpr 1.8.1
* Where did you get it from (e.g. conan, vcpkg, master, ...): Built from source tarball
* Operating System and version: macOS 11 (Intel and ARM64) and 10.15 (Intel)
* Link to a small example: N/A (issue affects build of cpr itself)

**Comment by COM8** [comment]
Thanks for this nice issue!
I agree, there needs to be a check. Would you like to create a PR for it?
If so, I could push a new release for you :)

**Comment by alebcay** [comment]
Hi Fabian, I'd be happy to open a PR for it but am unsure of what the fix should be. The line `curl_easy_setopt(curl_->handle, CURLOPT_SSLKEY_BLOB, &blob);` should be in a conditional if cURL is new enough. But what should be done instead if cURL is too old?

I'm not too familiar with cURL, so not sure I'm of much help here. 🙂

**Comment by munix9** [comment]
According to the commit https://github.com/libcpr/cpr/commit/4bae8a2cba0f89a53809d602d9232b83126ce1c3 I created the patch [fix-curl-blob-version-check.patch](https://build.opensuse.org/package/view_file/home:munix9/cpr/fix-curl-blob-version-check.patch?expand=1)
openSUSE Leap 15.3 comes with curl 7.66.0, compiling now works with cpr version 1.8.2
It's not tested yet, but maybe it serves as a possible solution (if that's the right approach).

**Comment by COM8** [comment]
Yes, this looks good!

**Comment by munix9** [comment]
Ok, thanks. @alebcay can you please create a PR based on my patch and COM8's comments in https://github.com/libcpr/cpr/issues/732#issuecomment-1112997990 ?

**Comment by alebcay** [comment]
I've opened a change for `libcpr` in #737 and a change for the docs in https://github.com/libcpr/docs/pull/13.

**Comment by COM8** [comment]
@alebcay a new release is available: https://github.com/libcpr/cpr/releases/tag/1.8.3
