### ISSUE TITLE
Response completely empty

### ISSUE THREAD

**Issue by oofsamy** [libcpr/cpr#740]
## Description

I'm trying to use libcpr to perform a GET request to get info about a gist, but when getting the `cpr::Response` object, seems like all fields except the `Url` and `Elapsed` field are just empty, even the error message is just completely null

## Expected Behavior

Should get a status code and body and headers

## Actual Behavior

Literally get nothing

## Steps to Reproduce
Not possible to do so it seems

## Context

Barely affected me, I'm trying to use gists as a small little database (yes its a json one) and I primarily use cpr for networking requests in c++

## Your Environment

* Latest
* VCPKG
* Operating System and version: Windows 10 Version 21H2
* Link to a small example: 

```
	cpr::Response r = cpr::Get(cpr::Url{ "https://api.github.com/gists/0cb7ca6301f450c8d89a7c62add5606b" });

	std::cout << "Message: " << r.error.message << "Body: " << r.text << "Time taken:" << r.elapsed << "Raw header:" << r.raw_header << "Url: " << r.url;
```
``Message: Body: Time taken:0.092267Raw header:Url: https://api.github.com/gists/0cb7ca6301f450c8d89a7c62add5606b``

**Comment by COM8** [comment]
Thanks for reporting.

This is a curl/vcpkg issue.
Here you can find the cur issue: https://github.com/curl/curl/issues/8741#issuecomment-1108286813

There is a workaround available here: https://github.com/microsoft/vcpkg/issues/23417#issuecomment-1100634689

Sadly this is nothing we can fix, since we do not maintain the vcpkg package.

**Comment by oofsamy** [comment]
Hey, sorry to reopen this issue or however git issues work, I have no idea, but I used the workaround given (modified for x64 version) and I still face the same issue, are you at all able to compile the latest version of libcpr (I am too much of a C++ noob to use cmake, I have tried for like a week lol) and send it over? (I have made sure it installed the right version of curl, iti s infact 7.80.0)

```json
{
  "name": "my-project",
  "version": "1.2.3",
  "license": "MIT",
  "dependencies": [
	{
		"name": "cpr",
		"platform": "windows & x64"
	}
  ],
  "builtin-baseline": "aebb363eaa0b658beb19cbefdd5aa2f9cbc14f1e",
  "overrides": [
    {
      "name": "curl",
      "version": "7.80.0",
      "$reason": "https://github.com/microsoft/vcpkg/issues/23417"
    }
  ]
}
```

**Comment by COM8** [comment]
From my side, yes I'm still able to compile.
Sadly I'm unable to test this with vcpkg since I'm not using Windows any more.
