### ISSUE TITLE
Can't send request to certain websites

### ISSUE THREAD

**Issue by JacqueSatan** [libcpr/cpr#743]
## Description
I am trying to perform a GET request to https://discord.com. When i send a GET request to other websites like https://www.google.com or https://httpbin.org, everything works fine. However, anything directed towards https://discord.com ends up making an internal error with no message.

## Expected Behavior
The request should be performed and return a response:
![image](https://user-images.githubusercontent.com/38167139/168421476-8ffcb493-0c6c-4c60-b4c5-2915a351b9bf.png)

## Actual Behavior
The request doesn't perform, and the response object indicates that an internal error has occurred with no further information:
![image](https://user-images.githubusercontent.com/38167139/168421511-3948adbf-a9fa-4464-bdb2-15461d398b08.png)

## Steps to Reproduce
Code used:
```cpp
#include "cpr/cpr.h"

int main()
{
	auto r = cpr::Get(cpr::Url{ "https://discord.com" });
	if (!r.status_code)
		std::cerr << "Error " << (int)r.error.code << " : " << r.error.message << std::endl;
	else
		std::cout << r.text << std::endl;
}
```

## Context
I'm trying to update an old API wrapper for Discord, so the code didn't change compared to what it was when it worked.

## Your Environment
* Version used: 1.8.3
* Where did you get it from: vcpkg
* Operating System and version: Windows 11 22616.100
* Link to a small example: https://github.com/JacqueSatan/ethyme.cpp/blob/master/src/client.cpp#L32

**Comment by COM8** [comment]
On Linux the following forks for me:
```c++
TEST(BasicTests, GetDiscord) {
    Url url{"https://discord.com/"};
    Response response = cpr::Get(url);
    EXPECT_EQ(url, response.url);
    EXPECT_EQ(std::string{"text/html"}, response.header["content-type"]);
    EXPECT_EQ(200, response.status_code);
    EXPECT_EQ(ErrorCode::OK, response.error.code);
}
```

This sounds like the curl/vcpkg issue.
Here you can find the curl issue: https://github.com/curl/curl/issues/8741#issuecomment-1108286813

There is a workaround available here: https://github.com/microsoft/vcpkg/issues/23417#issuecomment-1100634689

Please let me know if this works for you.

**Comment by JacqueSatan** [comment]
Thank you for your answer. The workaround works perfectly. Should I close the issue now or wait until the problem is solved?

**Comment by COM8** [comment]
Since this is nothing we can fix, since are not maintaining the vcpkg package I'm closing this one.
