### ISSUE TITLE
Add support for uploading arbitrary file parts with CURLOPT_RESUME_FROM

### ISSUE THREAD

**Issue by simon-berger** [libcpr/cpr#745]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to upload arbitrary parts of a file, as [CURLOPT_RANGE](https://curl.se/libcurl/c/CURLOPT_RANGE.html) should not be used for HTTP PUT uploads, as it conflicts with other options. Instead [CURLOPT_RESUME_FROM](https://curl.se/libcurl/c/CURLOPT_RESUME_FROM.html) should be used together with [CURLOPT_INFILESIZE](https://curl.se/libcurl/c/CURLOPT_INFILESIZE.html).

**Describe the solution you'd like**
Implement the [CURLOPT_RESUME_FROM](https://curl.se/libcurl/c/CURLOPT_RESUME_FROM.html) option in order to support the upload of arbitrary file parts.

**Describe alternatives you've considered**
I am not aware of any alternatives.

**Additional context**
If you like this feature I can create a pull request for it.

**Comment by COM8** [comment]
Yes, this would be a nice to have feature!

**Comment by simon-berger** [comment]
Then I will work on it in the next few weeks and create a PR when I'm done

**Comment by simon-berger** [comment]
I think we can close this issue, as libcurl / http will not support this (see: #753).
