### ISSUE TITLE
Post request results in internal error: CURLE_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by yeSpud** [libcpr/cpr#747]
## Description

When trying to make a post request to send an embed to a discord webhook the response given results in `0` with the message of `Internal Error`. Doing more digging to follow what causes the error reveals that curl is throwing `CURLE_OUT_OF_MEMORY` at some point.

## Expected Behavior

Should just send embed to webhook and return `200`.

## Actual Behavior

Returns `0` with message of `Internal Error` (with evidence of actual error being `CURLE_OUT_OF_MEMORY`)

## Steps to Reproduce

Tried sending an embed with the following code:
```cpp
cpr::Response sendWebhook(const std::string &json) {

	cpr::Body body = cpr::Body{json};
	cpr::Header header = cpr::Header{{"Content-Type", "application/json"}};
	cpr::Url url = cpr::Url{webhookURL};
	//cpr::SslOptions sslOpts = cpr::Ssl(cpr::ssl::TLSv1_3{});
	cpr::VerifySsl verifySsl = cpr::VerifySsl{false};
	cpr::Response response = cpr::Post(url, body, header, verifySsl);

	return response;
}
```

where the provided json argument was the following:
```cpp
"{\"embeds\":[{\"author\":{\"name\":\"Foxes in Love has a new post!\",\"url\":\"https://foxes-in-love.tumblr.com/post/680491087596584960\",\"icon_url\":\"https://64.media.tumblr.com/avatar_a95095bda931_512.png\"},\"image\":{\"url\":\"https://64.media.tumblr.com/9e5ee95e13e9287217978e57a5530769/d2cd88370977c72a-1f/s2048x3072/d0d6ce7affc540cb4bdbe260979b6ba9ad82acee.jpg\"}}]}"
```

and webhookURL is the URL to send the post request to (the discord webhook)  

## Context

Used to use this library for fetching and posting new Tumblr posts to discord.

## Your Environment

* Version used: Was just pulling from mater ([this was the most recent commit](https://github.com/libcpr/cpr/commit/5e64f82c5403f4ad0b81ec391e818699feb334c4))
* Where did you get it from (e.g. conan, vcpkg, master, ...): Master branch via CMake FetchContent
* Operating System and version: macOS 12.4
* Link to a small example: Small example provided in steps to reproduce ([here's a link to the full project if you want it though](https://github.com/yeSpud/FoxWebhook))

**Comment by COM8** [comment]
I will have a look at it later today.

**Comment by COM8** [comment]
But to me this sounds like: https://github.com/curl/curl/issues/8741#issuecomment-1108286813

Could you please try what happens when you use the following commit: db351ffbbadc6c4e9239daaa26e9aefa9f0ec82d
 from: https://github.com/libcpr/cpr/releases/tag/1.8.3

**Comment by yeSpud** [comment]
That seems to have fixed it - thank you!

Not sure at what point the most recent commits broke post requests, so I'm unsure if this should be closed as current builds run into that error

**Comment by COM8** [comment]
On master we are curently using the latest curl, which breaks this. I'm keeping this open until we either downgraded curl on master or we got a fixed version.

**Comment by COM8** [comment]
We downgraded the version of libcurl since there is no fix in sight.
