### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by daihanhle** [libcpr/cpr#749]
Hi I check out the code and build it. I got this error:

[ 77%] Building CXX object cpr/CMakeFiles/cpr.dir/auth.cpp.o
In file included from /home/daihanh/_vscode/http_cpr/cpr/cpr/auth.cpp:1:0:
/home/daihanh/_vscode/http_cpr/cpr/include/cpr/auth.h:20:21: error: function ‘cpr::Authentication& cpr::Authentication::operator=(cpr::Authentication&&)’ defaulted on its first declaration with an exception-specification that differs from the implicit declaration ‘cpr::Authentication& cpr::Authentication::operator=(cpr::Authentication&&)’
     Authentication& operator=(Authentication&& old) noexcept = default;
                     ^
gmake[2]: *** [cpr/CMakeFiles/cpr.dir/auth.cpp.o] Error 1
gmake[1]: *** [cpr/CMakeFiles/cpr.dir/all] Error 2
gmake: *** [all] Error 2

**Comment by daihanhle** [comment]
GCC version 4.8

**Comment by daihanhle** [comment]
ok with gcc 7.1

**Comment by COM8** [comment]
gcc 4.8 is too old. More on that can be found here: https://github.com/libcpr/cpr/issues/578
