### ISSUE TITLE
Update Mongoose to Version 7

### ISSUE THREAD

**Issue by COM8** [libcpr/cpr#757]
## Description

With the latest releases of OpenSSL we get a few deprecation warnings, when compiling [mongoose](https://github.com/cesanta/mongoose):
```log
[build] /home/fabian/Documents/Repos/libcpr/cpr/build/_deps/mongoose-src/mongoose.c: In function ‘mg_use_cert’:
[build] /home/fabian/Documents/Repos/libcpr/cpr/build/_deps/mongoose-src/mongoose.c:4758:7: warning: ‘PEM_read_bio_DHparams’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[build]  4758 |       dh = PEM_read_bio_DHparams(bio, NULL, NULL, NULL);
[build]       |       ^~
[build] In file included from /usr/include/openssl/ssl.h:36,
[build]                  from /home/fabian/Documents/Repos/libcpr/cpr/build/_deps/mongoose-src/mongoose.c:4471:
[build] /usr/include/openssl/pem.h:469:1: note: declared here
[build]   469 | DECLARE_PEM_rw_attr(OSSL_DEPRECATEDIN_3_0, DHparams, DH)
[build]       | ^~~~~~~~~~~~~~~~~~~
[build] /home/fabian/Documents/Repos/libcpr/cpr/build/_deps/mongoose-src/mongoose.c:4767:7: warning: ‘PEM_read_bio_DHparams’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[build]  4767 |       dh = PEM_read_bio_DHparams(bio, NULL, NULL, NULL);
[build]       |       ^~
[build] /usr/include/openssl/pem.h:469:1: note: declared here
[build]   469 | DECLARE_PEM_rw_attr(OSSL_DEPRECATEDIN_3_0, DHparams, DH)
[build]       | ^~~~~~~~~~~~~~~~~~~
[build] /home/fabian/Documents/Repos/libcpr/cpr/build/_deps/mongoose-src/mongoose.c:4773:7: warning: ‘DH_free’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[build]  4773 |       DH_free(dh);
[build]       |       ^~~~~~~
[build] In file included from /usr/include/openssl/dsa.h:51,
[build]                  from /usr/include/openssl/x509.h:37,
[build]                  from /usr/include/openssl/ssl.h:31:
[build] /usr/include/openssl/dh.h:200:28: note: declared here
[build]   200 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
[build]       |                            ^~~~~~~
```

## Expected Behavior

We should not use deprecated OpenSSL functions.

## Possible Fix

A solution would be to update our mongoose implementation to e.g. [version 7.7](https://github.com/cesanta/mongoose/releases/tag/7.7).

**BUT** this requires rewriting large parts of the http(s) test server. Also some functionality like simulating slow connections, like required [here](https://github.com/libcpr/cpr/blob/db351ffbbadc6c4e9239daaa26e9aefa9f0ec82d/test/httpServer.cpp#L88-L90) is not that easily possible any more since sending the header and payload not got merged into on call: [`mg_http_reply`](https://github.com/cesanta/mongoose/blob/d5993ba27ece4b406c230eca63b76dd5d2c28a2d/mongoose.h#L1071-L1072)

**Comment by saendigPhilip** [comment]
I would like to work on that issue

**Comment by COM8** [comment]
Sure! I assigned you to the issue. If you want, I can push the branch I started working on this, so you have a rough starting point and don't start from zero.

**Comment by saendigPhilip** [comment]
Yes, that would be very helpful, I think

**Comment by COM8** [comment]
Thanks for looking into this. I always was wondering if this test was even working at all. Now we have the confirmation. In my eyes we should still keep the test as it then just adds additional delay on the server side.
