### ISSUE TITLE
Example code (cprget) not linking properly

### ISSUE THREAD

**Issue by kgofron** [libcpr/cpr#759]
Fails at linking stage

 

## Expected Behavior
 The cprget should compile and link.

## Actual Behavior
 The cprget fails linking

## Possible Fix
 Not sure if it is a version issue, or something else.

## Steps to Reproduce
 Reproducible
 
1. git clone https://github.com/libcpr/cpr.git; mkdir build && cd build; cmake ..; cmake --build .; make
2. example cprget.cpp file compiled and linked to libcpr
3.
4.

## Context
 Planning to use libcpr with frozen/json parser to develop a device control driver. I was attracted to this because, I prototyped driver in python using requests.

## Your Environment

* Version used: 1.8.2
* Where did you get it from (e.g. conan, vcpkg, master, ...): 
* Operating System and version:5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Link to a small example: 
```
/docs/cpr$ more cprget.cpp 
#include <iostream>
#include <string>
#include <cpr/cpr.h>

int main(int argc, char** argv) {
    cpr::Response r = cpr::Get(cpr::Url{"https://api.github.com/repos/whoshuu/cpr/contributors"},
                               cpr::Authentication{"user", "pass"},
                               cpr::Parameters{{"anon", "true"}, {"key", "value"}});
    std::cout << "Status code: " << r.status_code << '\n';
    std::cout << "Header:\n";
    for (const std::pair<std::string, std::string>& kv : r.header) {
        std::cout << '\t' << kv.first << ':' << kv.second << '\n';
    }
    std::cout << "Text: " << r.text << '\n';
    return 0;
}
```
===================
Trying to compile example code, I am getting linker errors. It is possible, I am not doing this correctly.
-----------------------------------------

/docs/cpr$ g++ -o cprget -I/home/kgofron/src/git/cpr/include -I/home/kgofron/src/git/cpr/build/cpr_generated_includes  -L/home/kgofron/src/git/cpr/build/lib  -lcpr  cprget.cpp
/usr/bin/ld: /tmp/ccALvHRf.o: in function `main':
cprget.cpp:(.text+0x152): undefined reference to `cpr::Parameters::Parameters(std::initializer_list<cpr::Parameter> const&)'
/usr/bin/ld: /tmp/ccALvHRf.o: in function `cpr::Authentication::Authentication(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)':
cprget.cpp:(.text._ZN3cpr14AuthenticationC2EONSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_[_ZN3cpr14AuthenticationC5EONSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_]+0x2b): undefined reference to `vtable for cpr::Authentication'
/usr/bin/ld: /tmp/ccALvHRf.o: in function `cpr::Authentication::~Authentication()':
cprget.cpp:(.text._ZN3cpr14AuthenticationD2Ev[_ZN3cpr14AuthenticationD5Ev]+0x13): undefined reference to `vtable for cpr::Authentication'
/usr/bin/ld: /tmp/ccALvHRf.o: in function `cpr::Response cpr::Get<cpr::Url, cpr::Authentication, cpr::Parameters>(cpr::Url&&, cpr::Authentication&&, cpr::Parameters&&)':
cprget.cpp:(.text._ZN3cpr3GetIJNS_3UrlENS_14AuthenticationENS_10ParametersEEEENS_8ResponseEDpOT_[_ZN3cpr3GetIJNS_3UrlENS_14AuthenticationENS_10ParametersEEEENS_8ResponseEDpOT_]+0x36): undefined reference to `cpr::Session::Session()'
/usr/bin/ld: cprget.cpp:(.text._ZN3cpr3GetIJNS_3UrlENS_14AuthenticationENS_10ParametersEEEENS_8ResponseEDpOT_[_ZN3cpr3GetIJNS_3UrlENS_14AuthenticationENS_10ParametersEEEENS_8ResponseEDpOT_]+0x88): undefined reference to `cpr::Session::Get()'
/usr/bin/ld: cprget.cpp:(.text._ZN3cpr3GetIJNS_3UrlENS_14AuthenticationENS_10ParametersEEEENS_8ResponseEDpOT_[_ZN3cpr3GetIJNS_3UrlENS_14AuthenticationENS_10ParametersEEEENS_8ResponseEDpOT_]+0x95): undefined reference to `cpr::Session::~Session()'
/usr/bin/ld: cprget.cpp:(.text._ZN3cpr3GetIJNS_3UrlENS_14AuthenticationENS_10ParametersEEEENS_8ResponseEDpOT_[_ZN3cpr3GetIJNS_3UrlENS_14AuthenticationENS_10ParametersEEEENS_8ResponseEDpOT_]+0xba): undefined reference to `cpr::Session::~Session()'
/usr/bin/ld: /tmp/ccALvHRf.o: in function `void cpr::priv::set_option<cpr::Url, cpr::Authentication, cpr::Parameters>(cpr::Session&, cpr::Url&&, cpr::Authentication&&, cpr::Parameters&&)':
cprget.cpp:(.text._ZN3cpr4priv10set_optionIJNS_3UrlENS_14AuthenticationENS_10ParametersEEEEvRNS_7SessionEDpOT_[_ZN3cpr4priv10set_optionIJNS_3UrlENS_14AuthenticationENS_10ParametersEEEEvRNS_7SessionEDpOT_]+0x5d): undefined reference to `cpr::Session::SetOption(cpr::Url const&)'
/usr/bin/ld: cprget.cpp:(.text._ZN3cpr4priv10set_optionIJNS_3UrlENS_14AuthenticationENS_10ParametersEEEEvRNS_7SessionEDpOT_[_ZN3cpr4priv10set_optionIJNS_3UrlENS_14AuthenticationENS_10ParametersEEEEvRNS_7SessionEDpOT_]+0x82): undefined reference to `cpr::Session::SetOption(cpr::Authentication const&)'
/usr/bin/ld: cprget.cpp:(.text._ZN3cpr4priv10set_optionIJNS_3UrlENS_14AuthenticationENS_10ParametersEEEEvRNS_7SessionEDpOT_[_ZN3cpr4priv10set_optionIJNS_3UrlENS_14AuthenticationENS_10ParametersEEEEvRNS_7SessionEDpOT_]+0xa7): undefined reference to `cpr::Session::SetOption(cpr::Parameters&&)'
collect2: error: ld returned 1 exit status

**Comment by COM8** [comment]
When compiling your code with `g++ -o cprget -Iinclude/ -Ibuild/cpr_generated_includes/ -Lbuild/lib/lib -lcpr cprget.cpp`, for the following happens:
```log
cprget.cpp: In function ‘int main(int, char**)’:
cprget.cpp:7:66: error: no matching function for call to ‘cpr::Authentication::Authentication(<brace-enclosed initializer list>)’
    7 |                                cpr::Authentication{"user", "pass"},
      |                                                                  ^
In file included from include/cpr/api.h:11,
                 from include/cpr/cpr.h:4,
                 from cprget.cpp:3:
include/cpr/auth.h:17:5: note: candidate: ‘cpr::Authentication::Authentication(cpr::Authentication&&)’
   17 |     Authentication(Authentication&& old) noexcept = default;
      |     ^~~~~~~~~~~~~~
include/cpr/auth.h:17:5: note:   candidate expects 1 argument, 2 provided
include/cpr/auth.h:16:5: note: candidate: ‘cpr::Authentication::Authentication(const cpr::Authentication&)’
   16 |     Authentication(const Authentication& other) = default;
      |     ^~~~~~~~~~~~~~
include/cpr/auth.h:16:5: note:   candidate expects 1 argument, 2 provided
include/cpr/auth.h:15:5: note: candidate: ‘cpr::Authentication::Authentication(std::string&&, std::string&&, const cpr::AuthMode&&)’
   15 |     Authentication(std::string&& username, std::string&& password, const AuthMode&& auth_mode) : auth_string_{std::move(username) + ":" + std::move(password)}, auth_mode_{std::move(auth_mode)} {}
      |     ^~~~~~~~~~~~~~
include/cpr/auth.h:15:5: note:   candidate expects 3 arguments, 2 provided
In file included from include/cpr/api.h:11,
                 from include/cpr/cpr.h:4,
                 from cprget.cpp:3:
include/cpr/auth.h:14:5: note: candidate: ‘cpr::Authentication::Authentication(const string&, const string&, const cpr::AuthMode&)’
   14 |     Authentication(const std::string& username, const std::string& password, const AuthMode& auth_mode) : auth_string_{username + ":" + password}, auth_mode_{auth_mode} {}
      |     ^~~~~~~~~~~~~~
include/cpr/auth.h:14:5: note:   candidate expects 3 arguments, 2 provided

```

To fix it try the following `cpr::Authentication{"user", "pass", cpr::AuthMode::BASIC},`

**Comment by kgofron** [comment]
My mistake: the library libpcr must be after cprget.cpp source file.

```
g++ -o cprget -I/home/kgofron/src/git/cpr/include -I/home/kgofron/src/git/cpr/build/cpr_generated_includes  -L/home/kgofron/src/git/cpr/build/lib  cprget.cpp -lcpr
```
