### ISSUE TITLE
Waiting times with cpr::get when getting more then a few kb

### ISSUE THREAD

**Issue by Binary-System** [libcpr/cpr#761]
I have a strange waiting time when using cpr::Get to download a file with more then a few kb
```
int main()
{
	cpr::Response r = cpr::Get(cpr::Url{ "http://www.httpbin.org/bytes/1096" });
	std::cout << r.url << std::endl;
	std::cout << r.status_code << std::endl;
	std::cout << r.header["content-type"] << std::endl;
	std::cout << r.text << std::endl;
}
```
takes about a quarter of a second

```
int main()
{
	cpr::Response r = cpr::Get(cpr::Url{ "http://www.httpbin.org/bytes/10960" });
	std::cout << r.url << std::endl;
	std::cout << r.status_code << std::endl;
	std::cout << r.header["content-type"] << std::endl;
	std::cout << r.text << std::endl;
}
```
takes eleven seconds with 10 seconds without any cpu or memory usage/change.
Is something in cpr freezing there, waiting for something?
Can someone reproduce that phenomenon?

**Comment by Binary-System** [comment]
Timespan rises with file size. 22mb take 4-6 seconds network traffic and about 3 minutes "wait time" after that for example.

**Comment by COM8** [comment]
For me your example takes roughly 0.2 seconds to complete:
```log
[fabian@fabian-linux build]$ time ./cpr_example 
http://www.httpbin.org/bytes/10960
200
application/octet-stream

real	0m0.285s
user	0m0.005s
sys	0m0.008s
```

What version of cpr are you using, what OS are you on? Please don't just ditch the issue template next time. It contains valuable information which I now have to ask you one by one again.

What happens if you run:
```bash
time curl --output result.bin http://www.httpbin.org/bytes/10960
```

**Comment by Binary-System** [comment]
Systems: Windows 8.1, 10 and 11
IDE: Visual Studio 2019
CPR:1.6.2 via vcpkg 

time curl doesn't work because windows.

It seems std::sting access is somehow way slower when it's contained in cpr::response then in std::string "naked"

I would expect both timer outputs to be roughly the same in the following quick and dirty snippet:
```
int main()
{
	Timer t1;
	
	cpr::Response r1 = cpr::Get(cpr::Url{ "http://212.183.159.230/20MB.zip" }); // file IP is from http://xcal1.vodafone.co.uk
	std::cout << r1.url << std::endl;
	std::cout << r1.status_code << std::endl;
	std::cout << r1.header["content-type"] << std::endl;

	t1.reset();
	std::cout << r1.text << std::endl;
	std::cout << "Time elapsed: " << t1.elapsed() << " seconds\n";

	std::string s = "";
	srand(time(NULL));

	for (int i = 0; i <= 20971520; i++) {
		s.append(std::to_string(rand() % 10));
	}

	t1.reset();
	std::cout << s << std::endl;
	std::cout << "Time elapsed: " << t1.elapsed() << " seconds\n";

}
```
But first is 39 seconds, 2nd is 3.5 seconds (both should be 20MB "in size")

Or am I really stupid somewhere here?

PS: Sorry somehow I didn't noticed/got the template

**Comment by COM8** [comment]
What happens in case you reserve some space before doing the request like described here: https://docs.libcpr.org/advanced-usage.html#large-responses

**Comment by COM8** [comment]
Ah, you are using 1.6.2.  There `cpr::ReserveSize` is not available. Any reason why you are using an outdated version of cpr?

**Comment by Binary-System** [comment]
Will update and try again with and without ReserveSize.

Until now possible risk of breaking something with an update was bigger then possible new features or problems fixed.

**Comment by Binary-System** [comment]
When installed with cvpgk version number of cpr:x86-windows updates to 1.8.3 but ReserveSitze.h and a few other files are missing completely. Further tests here have to wait until there is an solution to that.

**Comment by Binary-System** [comment]
Have to wait until https://github.com/microsoft/vcpkg/issues/25237 is published will then investigate further.

**Comment by Binary-System** [comment]
There seems to be a problem integrating the latest CPR version into vcpkg

https://github.com/microsoft/vcpkg/pull/25244

**Comment by COM8** [comment]
Closing this one for now since it does not seam to be a cpr issue itself.
Feel free to reopen in case this changes.
