### ISSUE TITLE
Response for a HTTPS Get to Jira returns error code 4.

### ISSUE THREAD

**Issue by Raigestain** [libcpr/cpr#762]
## Description
I've been trying to do a GET request using the Jira REST API, but all that I got was an **Error Code** 4, with a **Status Code** 0

## Expected Behavior
Get the json information from the page.

## Actual Behavior
Error Code: 4
Status Code: 0
Empty Body.

## Steps to Reproduce

Here you can find two examples of what I tried.

1.
```
int main()
{
    cpr::Response response = cpr::Get(cpr::Url{ "https://mypage.atlassian.net/rest/api/latest/project" },
		cpr::Authentication{ "myuser@mydomain.com", "atlassianpasswordtoken", cpr::AuthMode::BASIC},
		cpr::Header{{"accept", "application/json"} });

    if (response.status_code == 0)
    {
        cout << response.error.message << endl; //Empty.
	cout << (int)response.error.code << endl; // 4
    }

    cout << "Url: " << response.url << endl; //https://mypage.atlassian.net/rest/api/latest/project
    cout << "Status Code: " << response.status_code << endl; // 0
    cout << "Header: " << response.header["content-type"] << endl; // Empty.
    cout << "" << response.text << endl; //Empty.

    return 0;
}
```

2.
```
int main()
{
    cpr::Url url = { "https://mypage.atlassian.net/rest/api/latest/project" };
    cpr::Authentication auth = { "myuser@mydomain.com", "atlassianpasswordtoken", cpr::AuthMode::BASIC };

    cpr::Session session;
    session.SetUrl(url);
    session.SetAuth(auth);

    cpr::Response response = session.Get();
    
    //Same responses that in the previous try.
    if (response.status_code == 0)
    {
        cout << response.error.message << endl;
        cout << (int)response.error.code << endl;
    }

    cout << "Url: " << response.url << endl;
    cout << "Status Code: " << response.status_code << endl;
    cout << "Header: " << response.header["content-type"] << endl;
    cout << "" << response.text << endl;
    
    return 0;
}
```

## Notes:
I tried different ways to do it.

- Used different url's. All of them similar, but I event tried to use just `https://mypage.atlassian.net`, expecting the html, but nothing arrived.
- Used the different values for the AuthMode.
- Encrypted the credentials.
- Tried to use the headers.
- Tried to use the parameters.

In general I did some different tests but didn't managed to get the info.

## Your Environment

* Version used: 1.8.1
* Where did you get it from (e.g. conan, vcpkg, master, ...): master.
* Operating System and version: Windows 10.

**Comment by COM8** [comment]
Try using [Release 1.8.3](https://github.com/libcpr/cpr/releases/tag/1.8.3). This is currently a curl issue: https://github.com/curl/curl/issues/8741 since we are using a rather new version of curl in master.
