### ISSUE TITLE
cpr fails cpack (using NSIS) on windows

### ISSUE THREAD

**Issue by TennisBowling** [libcpr/cpr#766]
## Description
cpr appears to use absolute paths, which NSIS does not allow.
when trying to pack my project, I get
```
CMake Error at D:/a/executionbackup/executionbackup/build/_deps/zlib-build/cmake_install.cmake:47 (message):
  ABSOLUTE path INSTALL DESTINATION forbidden (by caller): C:/Program Files
  (x86)/executionbackup/lib/zlib.lib
Call Stack (most recent call first):
  D:/a/executionbackup/executionbackup/build/_deps/cpr-build/cmake_install.cmake:42 (include)
  D:/a/executionbackup/executionbackup/build/cmake_install.cmake:53 (include)
```

## Expected Behavior
NSIS packs the project correctly

## Actual Behavior
NSIS crashes because there is an absolute path

## Possible Fix
remove absolute path somehow

## Steps to Reproduce
1. make a project with cpr in it
2. pack with cmake using `cpack -G NSIS`

example in github actions: https://github.com/TennisBowling/executionbackup/runs/6974017832?check_suite_focus=true

## Context
I'm trying to use cpr in a program that I'm trying to pack as one executable

## Your Environment
* Version used: v1.8.3
* Where did you get it from (e.g. conan, vcpkg, master, ...): cmake fetchcontent
* Operating System and version: windows, latest
* Link to a small example: https://github.com/TennisBowling/executionbackup/runs/6974017832?check_suite_focus=true

**Comment by KingKili** [comment]
Seams like the issue is in the build system of zlib. Since zlib is no hard dependency, I would recommend you trying to remove it (`-DCURL_ZLIB=OFF`). Please let me know if you require further assistance.

**Comment by TennisBowling** [comment]
yeah that works. thank you!
quick question because i dont know where else to post and doesn't warrent an issue:
can cpr be built statically with cmake?

**Comment by KingKili** [comment]
Sure this is possible using `-DBUILD_SHARED_LIBS=false`
