### ISSUE TITLE
HTTP Streaming Protocol support?

### ISSUE THREAD

**Issue by D7EAD** [libcpr/cpr#767]
Does CPR allow support for HTTP Streaming Protocol in any way? 

I'm currently writing a wrapper for a particular web API, and certain endpoints make use of HTTP streaming. These endpoints describe a requirement for a persistent connection (much like WebSockets) as data is supplied to the client in real time as it comes in; they describe it like so:

- *"Establishing a connection to the streaming APIs means making a very long lived HTTP request, and parsing the response incrementally. Conceptually, you can think of it as downloading an infinitely long file over HTTP."*

Is this currently possible with CPR? If not, would this be a viable feature addition in the future?

**Comment by COM8** [comment]
In theory yes, but I never tested it. What one could use in this case is the [`WriteCallback`](https://docs.libcpr.org/advanced-usage.html#setting-callbacks)

**Comment by D7EAD** [comment]
Alright, I'll make use of that and get back to you with the results of such.

**Comment by HellsingDarge** [comment]
It is possible with `WriteCallback`, with a few caveats:
* you'll need to have a dedicated `Session` object for catching these stream writes, as any changes to the holding object will invalidate it
* cURL, and by extension CPR, are single-threaded - the execution will wait until the stream has been signaled to have been ended by the endpoint, so you'll need to listen to the stream in a separate thread

**Comment by D7EAD** [comment]
Alright, with that, I'll close this issue and get to it. Thanks a lot.
