### ISSUE TITLE
Need example for connecting to SSL host+port

### ISSUE THREAD

**Issue by kpadmasola** [libcpr/cpr#772]
Hi, 

The documentation has many examples on how to use cpr to connect to https endpoints.
However, I need to connect to an SSL host+port over plain TCP (not HTTPS) to send and receive messages. Is this possible using cpr? It would be great if you can share sample code for this.

thank you!

**Comment by COM8** [comment]
Or could you please elaborate your requirement a bit more?

**Comment by kpadmasola** [comment]
Something similar to https://github.com/chriskohlhoff/asio/blob/master/asio/src/examples/cpp11/ssl/client.cpp, but using cpr.

**Comment by COM8** [comment]
Hmmm...
I'm sorry to say, this is nothing we can provide you with since we are building on top of libcurl. So in case you can find such functionality in libcurl we can think about creating an interface inside cpr for it.

**Comment by COM8** [comment]
Closing this for now, since this is nothing we can provide.
