### ISSUE TITLE
DNS Lookup using cpr

### ISSUE THREAD

**Issue by pythagoras9** [libcpr/cpr#782]
I am trying to obtain the IP address of a machine which has a hostname. I do not have the DNS IP address as the DNS server is local. It would be great if cpr had the facility to do a dns lookup. Perhaps even reverse lookups.

**Comment by COM8** [comment]
In my eyes this is not something we will target any time soon. The goal of cpr is to perform web request and let the operating system deal with resolving host names.

This might help: https://stackoverflow.com/questions/2151854/c-resolve-a-host-ip-address-from-a-url

Boost also has this functionality:
https://dens.website/tutorials/cpp-asio/resolvers
