### ISSUE TITLE
Read Callback doesn't work with PUT

### ISSUE THREAD

**Issue by locez** [libcpr/cpr#786]
## Description

Read Callback doesn't work with PUT, it just work with POST method

```cpp
#include<cpr/cpr.h>

#include<iostream>

using namespace cpr;
int main(int c, char ** v) {
  Url url("http://httpbin.org/put");
  int count = 0;
  cpr::Session session;
  session.SetUrl(url);
  session.SetReadCallback(cpr::ReadCallback {
    3,
    [ & ](char * buffer, size_t & size, intptr_t /*userdata*/ ) -> size_t {
      std::string data;
      ++count;
      switch (count) {
      case 1:
        data = "x=";
        break;
      case 2:
        data = "5";
        break;
      default:
        return false;
      }
      std::cout << count << "  " << data;
      std::copy(data.begin(), data.end(), buffer);
      size = data.size();
      return true;
    }
  });
  // PUT object
  auto response = session.Put();
  std::cout << "body:" << response.text << std::endl;
  std::cout << "code: " << response.status_code << std::endl;
  std::cout << "error: " << (int) response.error.code << std::endl;
}
```

## Expected Behavior

upload big file with put method

## Actual Behavior
it doesn't work with PUT method

## Your Environment
cpr: 1.8.3
libcurl: curl-7.77.0.tar.gz

* Version used:
* Where did you get it from (e.g. conan, vcpkg, master, ...):
* Operating System and version:
* Link to a small example:

**Comment by COM8** [comment]
Confirmed. Thanks for reporting. I created a PR to fix this issue here: https://github.com/libcpr/cpr/pull/787

**Comment by COM8** [comment]
Could you please try if this PR fixes your issue?

**Comment by locez** [comment]
I'll test whether this change meets the requirements on Monday. How about the CURLOPT_UPLOAD parameter, I see that some examples use this parameter, but this parameter is not set anywhere in the cpr source code

**Comment by COM8** [comment]
As far as I'm understanding it ([docs](https://curl.se/libcurl/c/CURLOPT_UPLOAD.html)), this can be used in case your only intend is to upload stuff. But when setting this, this would break stuff for other people, which expect some kind of response from the server.

Please let me know as soon as possible once you have tested those changes, so I can release 1.9.0, including or excluding this fix.

**Comment by locez** [comment]
We have tested this modification and it solved our problem.

**Comment by COM8** [comment]
Awesome! Thanks for the fast reply. Now I can finish up the release.
