### ISSUE TITLE
Advanced Usage Page Shows 404

### ISSUE THREAD

**Issue by hamzaahmedzia1** [libcpr/cpr#788]
On https://docs.libcpr.org/introduction.html If you browse all the way down on the basic usage page to the section
`With these basic operations, modern C++ has access to a significant portion of the world wide web’s APIs. For more complex applications, check out the [Advanced Usage guides](https://docs.libcpr.org/cpr/advanced-usage.html).`

That link shows 404. 

The left navigation pane for on https://docs.libcpr.org/introduction.html for [Advanced Usage](https://docs.libcpr.org/advanced-usage.html) works fine.

**Comment by COM8** [comment]
Thanks for reporting. Fixed: https://github.com/libcpr/docs/commit/6d8b0060d64adbb089e1a1ee584cf42a64f2eaf3
