### ISSUE TITLE
proxy issue

### ISSUE THREAD

**Issue by khtkiprw** [libcpr/cpr#790]
Why should setting up a proxy be based on the requested URL protocol ? 

Shouldn't the user be the protocol that specifies the proxy

According to the request URL protocol, I can not set up socks5 proxy? 

```
 std::string protocol = url_.str().substr(0, url_.str().find(':'));
    if (proxies_.has(protocol)) {
        curl_easy_setopt(curl_->handle, CURLOPT_PROXY, proxies_[protocol].c_str());
        if (proxyAuth_.has(protocol)) {
            curl_easy_setopt(curl_->handle, CURLOPT_PROXYAUTH, CURLAUTH_ANY);
            curl_easy_setopt(curl_->handle, CURLOPT_PROXYUSERPWD, proxyAuth_[protocol]);
        }
    }

```

**Comment by COM8** [comment]
To ensure, you get a reply in time, please use the issue template next time, when you create an issue ;)

This issue should help: https://github.com/libcpr/cpr/issues/461
