### ISSUE TITLE
find_package for CMake

### ISSUE THREAD

**Issue by jmafc** [libcpr/cpr#792]
**Is your feature request related to a problem? Please describe.**
The suggested approach of using FetchContent to include `cpr` causes it (and *everything else*) to be checked and rebuilt (including all of `curl` *and* its tests) any time I tweak my `CMakeLists.txt` (which I've been doing rather frequently because I'm migrating other programs--and only two of which use `cpr` and those are essentially done).

**Describe the solution you'd like**
A `find_package` alternative to the FetchContent suggestion.

**Describe alternatives you've considered**
I built `cpr` locally and installed it to `/usr/local/lib` and added `find_package` to my CMakeLists.txt. However, `cmake` complained about not being able to find `cprConfig.cmake` or `cpr-config.cmake`. Since the latter file exists in your root directory, I copied it manually to `/usr/local/lib/cmake/CPR`. However, cmake now complains:
```
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find CPR (missing: CPR_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/lib/cmake/CPR/cpr-config.cmake:21 (find_package_handle_standard_args)
```
So what I'm really asking is that the work that was started when that `cpr-config.cmake` was created be completed so that `find_package` can be used.

**Additional context**
Using `cpr 1.9.0` on Debian 11.

**Comment by jmafc** [comment]
Looking a little closer, I see that #645 was a PR that attempted to fix this problem and that created the file `cmake/cprConfig.cmake.in` (so the older `cpr-config.cmake` can probably be removed).  It also modified the `cpr/CMakeLists.txt` to create the `cprTargets.cmake` needed by the `.in` file. However, I cannot find the `cprTargets.cmake` file in build directory tree after doing a `cmake --build .`. So, instead of being a "feature request", this ought to be considered a bug.

**Comment by KingKili** [comment]
In order for the CPR config to be installed, you must use the libcurl of your system (`CPR_FORCE_USE_SYSTEM_CURL`). Then it should all work as requested after a `make install`.

**Comment by jmafc** [comment]
OK, tested and that does work. However, that fact and the procedure for using Cmake `find_package` s perhaps should be mentioned in the main  README?

**Comment by COM8** [comment]
@jmafc Would you like to create a PR for this?

**Comment by jmafc** [comment]
Not at this time. Sorry. You may close the issue if you want.
