### ISSUE TITLE
README Replace C++11 by C++17

### ISSUE THREAD

**Issue by Lecrapouille** [libcpr/cpr#796]
Hi !

The README says many times the project is C++11 compliant `Using the more expressive language facilities of C++11` or `a C++11 compatible compiler such as Clang or GCC.` but C++17 is mandatory.

**Comment by COM8** [comment]
Yes, you are right. We are currently transitioning master to cpp17 (https://github.com/libcpr/cpr/pull/765).
The last release with cpp11 support is [1.9.0](https://github.com/libcpr/cpr/releases/tag/1.9.0). I was planing to update the readme accordingly, to let people know how to get a cpp11 compatible version of cpr.
