### ISSUE TITLE
I get a Seg Fault on GET request. Version 1.9.0

### ISSUE THREAD

**Issue by Reivax47** [libcpr/cpr#797]
Hi !

I've just moved from 1.7.0 to 1.9.0 this morning and I get a seg fault on my first GET request.
This line in session.h make it crash:
`    ~Session() = default;`

Up in the pile, in cpr::Get, I get this : 
`str_ = <error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.><error reading variable: Cannot create a lazy string with address 0x0, and a non-zero length.>`

I have no idea why I get this. I didn't change the way I'm calling the GET request : 

` cpr::Url url = cpr::Url{this->adresse_root + requete}; 
 cpr::Response monRetour = cpr::Get( url );`

Thanks !

## Your Environment

* Version used: 1.9.0
* Where did you get it from (e.g. conan, vcpkg, master, ...): CMAKE
* Operating System and version: Debian 10

**Comment by COM8** [comment]
Thanks for taking the time to report this!
Could you please provide a minimal example, since I currently can not reproduce this issue on Debian 10/Fedora 36 and Ubuntu {20.04, 22.04}.

**Comment by COM8** [comment]
And a complete stack trace please 😄 .

**Comment by Reivax47** [comment]
> And a complete stack trace please smile .

The precise point of the crash : 
![image](https://user-images.githubusercontent.com/47529668/181002687-068f9960-7edd-4333-b113-9e7715d23847.png)

cpr::Session ~Session
![image](https://user-images.githubusercontent.com/47529668/181003075-9c9b3231-edaf-4557-ad59-d740b14dd541.png)

And my call : 
![image](https://user-images.githubusercontent.com/47529668/181003448-aaa4e3ee-ef10-41a8-a9cf-635982ff1271.png)

Thanks for your time.

**Comment by COM8** [comment]
Since you are consuming cpr via CMake, could you please try the following patch.
Replace `writeFunction(...)` inside `cpr/util.cpp` with the following patched version:
```
size_t writeFunction(char* ptr, size_t size, size_t nmemb, std::string* data) {
    size *= nmemb;
    if (ptr && size > 0) {
        data->append(ptr, size);
    }
    return size;
}
```

**Comment by COM8** [comment]
`response_string_reserve_size_` also has a rather "broken" value.

**Comment by Reivax47** [comment]
> 

So with util.cpp modified as this :  
![image](https://user-images.githubusercontent.com/47529668/181007560-f6372ad3-0f11-4daa-bc26-0ce84a100a95.png)

I get the same result.
![image](https://user-images.githubusercontent.com/47529668/181007689-bf95d4c2-a8b7-4ece-a6ec-2ec43c8a5bae.png)

![image](https://user-images.githubusercontent.com/47529668/181007828-5ac248d5-92f2-4caf-94ed-ce2d3e4249e2.png)
Thanks  !

**Comment by COM8** [comment]
OK, then I don not know any further. Could you please provide a minimal example, so I can debug this?

**Comment by Reivax47** [comment]
Ok, I'm working on it.
Thanks for your time.

**Comment by COM8** [comment]
Any updates on this issue?

**Comment by Reivax47** [comment]
Hi Fabian,

Sorry to be late.

Yes and all was on me. I'm working on a remote device. On this device,
CPR's update was not successful. I did update again and since then
everything is fine.

Sorry again to not updated you and false report.
Xavier.

Le jeu. 11 août 2022 à 09:18, Fabian Sauter ***@***.***> a
écrit :
