### ISSUE TITLE
Async requests does not go parallel

### ISSUE THREAD

**Issue by walge-laine** [libcpr/cpr#800]
## Description
In older versions of `cpr` where `std::async` is used, async requests can be sent concurrently, but in the latest version, they are serial. After some brief debugging, I found that `GlobalThreadPool` has one thread and it seems `idle_thread_num` never decreases so no more threads would be created. Here's my test code
```c++
#include <chrono>
#include "cpr/cpr.h"
#include "fmt/chrono.h"

int main() {
    std::vector<std::future<void>> futs;

    for (int i = 0; i < 10; ++i) {
#if 1
	futs.emplace_back(cpr::GetCallback(
	    [] (cpr::Response res) {
		auto time = std::chrono::system_clock::now();
		fmt::print("{:%H:%M:%S} {}\n", time, res.text);
	    },
	    cpr::Url{"https://localhost/hello"}
	));
#else
	futs.emplace_back(std::async(
	    [] {
		auto res = cpr::Get(cpr::Url{"https://localhost/hello"});
		auto time = std::chrono::system_clock::now();
		fmt::print("{:%H:%M:%S} {}\n", time, res.text);
	    }
	));
#endif
    }

    for (auto &&f : futs) {
	f.wait();
    }
}
```
 
## Expected Behavior
I think `cpr::GetCallback` should behave similarly with manually wrapping `cpr::Get` in `std::async`.

## Actual Behavior
When using `cpr::GetCallback`, I got following output (local server responds in exactly 5 seconds):
```
21:59:52 Hello 0
21:59:57 Hello 1
22:00:02 Hello 2
22:00:07 Hello 3
22:00:12 Hello 4
22:00:17 Hello 5
22:00:22 Hello 6
22:00:27 Hello 7
22:00:32 Hello 8
22:00:37 Hello 9
```
Time and ordered response texts indicate serial requests.  

While `std::async` produce
```
22:05:15 Hello 1
22:05:15 Hello 2
22:05:15 Hello 0
22:05:15 Hello 3
22:05:15 Hello 5
22:05:15 Hello 9
22:05:15 Hello 8
22:05:15 Hello 4
22:05:15 Hello 7
22:05:15 Hello 6
```

## Your Environment
* Version used: 1.9.0
* Where did you get it from (e.g. conan, vcpkg, master, ...): vcpkg
* Operating System and version: Windows11  21H2  22000.832
* Link to a small example:

**Comment by COM8** [comment]
Thanks for taking the time to report this! I will have a look at it shortly.

**Comment by COM8** [comment]
Short example demonstrating the issue:
```c++
#include <future>
#include <iostream>
#include <string>
#include <vector>
#include <cpr/cpr.h>

int main(int /*argc*/, char** /*argv*/) {
    std::vector<std::future<void>> futs;
    for (size_t i = 0; i < 10; i++) {
        futs.emplace_back(cpr::GetCallback(
            [i](cpr::Response /*res*/) {
                std::cout << "Done: " << i << '\n';
            },
            cpr::Url{"http://www.httpbin.org/get"}));
    }

    for (const std::future<void>& f : futs) {
        f.wait();
    }
    return 0;
}
```

**Comment by COM8** [comment]
Created a fix for it here: https://github.com/libcpr/cpr/pull/802

How important is it for your current workflow since I was planing to make a new 1.9.x release by the the end of the month. In case it's important to have this fixed as soon as possible, I can work on a new release this week.

As a workaround you can do something like:
```c++
#include <chrono>
#include <future>
#include <iostream>
#include <string>
#include <thread>
#include <vector>
#include <cpr/cpr.h>

int main(int /*argc*/, char** /*argv*/) {
    std::vector<std::future<void>> futs;
    for (size_t i = 0; i < 10; i++) {
        futs.emplace_back(cpr::GetCallback(
            [i](cpr::Response /*res*/) {
                std::cout << "Done: " << i << '\n';
            },
            cpr::Url{"http://www.httpbin.org/get"}));
            std::this_thread::sleep_for(std::chrono::milliseconds(10)); // Save delay
    }

    for (const std::future<void>& f : futs) {
        f.wait();
    }
    return 0;
}
```
This gives the threads enough time to start internally and reduce their counters.
