### ISSUE TITLE
Is there a reason why the relatively old libcurl version 7.80 is built?

### ISSUE THREAD

**Issue by matthiasklein** [libcpr/cpr#804]
What are your plans regarding updating to newer libcurl versions like 7.84.0?

**Comment by COM8** [comment]
Currently impossible due to: https://github.com/curl/curl/issues/8741

An update would break HTTPS on Windows.

**Comment by christk1** [comment]
I need to use this library with cmake on my project to make requests but I also need libcurl SMTP support inside my project. The SMTP is disabled in the curl installed with the cpr lib. Is there any workaround?

**Comment by TheAssassin** [comment]
I just tried, and if this behavior was made configurable (i.e., `CURLOPT_CERTINFO` would not be set by default), newer libcurl versions should work.

**Comment by COM8** [comment]
Curl added https://github.com/curl/curl/issues/8741 to the list of known bugs so 🤷🏻‍♂️  I guess.
I plan to replace the affected code somehow and then I really would like to update curl rather sooner than later again.

**Comment by COM8** [comment]
> I just tried, and if this behavior was made configurable (i.e., `CURLOPT_CERTINFO` would not be set by default), newer libcurl versions should work.

Making it an option is no solution in my eyes since it just will lead to more tickets of people asking why does XYZ not work on my system. I added it to the TODO list for the 1.11.0 release.

**Comment by COM8** [comment]
Update: Changed the milestone to 1.9.x since this is something we can and should backport to 1.9.x.

**Comment by COM8** [comment]
Fixed with the update to curl 8.4.0 in cpr [1.10.5](https://github.com/libcpr/cpr/releases/tag/1.10.5) and [1.9.7](https://github.com/libcpr/cpr/releases/tag/1.9.7).
