### ISSUE TITLE
How to send data that is not form-encoded?

### ISSUE THREAD

**Issue by denglihong2007** [libcpr/cpr#808]
When I send a post request using libcpr or Python's requests, the server returns:
```
{'msg':'illegal request method','returnCode':'00405','data':'Content type'application/x-www-form-urlencoded; charset=UTF-8'not supported'}'.
```
C++ Code:
```
cpr::Response r = cpr::Post(cpr::Url{ "https://ec.95306.cn/api/bl/queryProduct/querySkb" },
	cpr::Timeout{ 7000 },
	cpr::Payload{ {"gbcc", "X8003"} });
```
Python Code:
```
data = {
    "gbcc": "X8003"
}
r = requests.post("https://ec.95306.cn/api/bl/queryProduct/querySkb", data=data)
```

It is written in the docs of Python's requests that:
`There are times that you may want to send data that is not form-encoded. If you pass in a string instead of a dict, that data will be posted directly.Instead of encoding the dict yourself, you can also pass it directly using the json parameter (added in version 2.4.2) and it will be encoded automatically`.
So I use:
```
data = {
    "gbcc": "X8003"
}
r = requests.post("https://ec.95306.cn/api/bl/queryProduct/querySkb", json=data)
```
In this way, it works normally.
So how do you use libcurl to do this?

Another problem is how to pass a numeric value with payload, like this:
```
cpr::Payload{ {"skbbbh",1} });
```

**Comment by COM8** [comment]
Try using a `cpr::Body` instead of a `cpr::Payload` for posting raw data. But I agree, this is something we should document better.

**Comment by denglihong2007** [comment]
> Try using a instead of a for posting raw data. But I agree, this is something we should document better.`cpr::Body``cpr::Payload`

like `cpr::Body{ {'"gbcc"="X8003"'} }?`

**Comment by COM8** [comment]
No, like this:
```c++
std::string body{R"({"RegisterObject": {"DeviceID": "65010000005030000001"}})"};
cpr::Response response = cpr::Post(url, cpr::Header{{"Content-Type", "application/json"}}, cpr::Body{body});
```

**Comment by denglihong2007** [comment]
> No, like this:
> 
> ```c++
> std::string body{R"({"RegisterObject": {"DeviceID": "65010000005030000001"}})"};
> cpr::Response response = cpr::Post(url, cpr::Header{{"Content-Type", "application/json"}}, cpr::Body{body});
> ```

Thank you!
