### ISSUE TITLE
Can't Compile Application in 32 Bit

### ISSUE THREAD

**Issue by lthon09** [libcpr/cpr#809]
I can't seem to get CMake to compile my application for 32 bit with CPR working. When I try to do it, an uncompatible error gets raised. I'm not sure why this happens as I've already added the `-m32` flags.

My `main.cpp` file is just:

```cpp
# include <cpr/cpr.h>

int main() {
    return 0;
}
```

This is my `CMakeLists.txt`:

```cmake
cmake_minimum_required(VERSION 3.24)

project(test)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_BUILD_TYPE "Release")

string(APPEND CMAKE_C_FLAGS " -m32")
string(APPEND CMAKE_CXX_FLAGS " -m32 -mwindows -s -O2")

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ../dist)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ../dist)

add_executable(${PROJECT_NAME} main.cpp)

include(FetchContent)

FetchContent_Declare(cpr
    GIT_REPOSITORY https://github.com/libcpr/cpr.git
    GIT_TAG f9575ca983014f637f6f4956fc7d26b002fde7d1
)
FetchContent_MakeAvailable(cpr)

target_link_libraries(${PROJECT_NAME} PRIVATE cpr::cpr)
```

Above, as you can see, I'm trying to compile these in 32 bit with the `-m32` flag.

If I don't try compiling in 32 bit, the process runs through fine, but if I do, at `Linking C shared library ../dist/libcurl.dll`, it errors:

```
[ 70%] Linking C shared library ../dist/libcurl.dll
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: i386:x86-64 architecture of input file `CMakeFiles/libcurl.dir/objects.a(libcurl.rc.obj)' is incompatible with i386 output     
collect2.exe: error: ld returned 1 exit status
make[2]: *** [_deps/curl-build/lib/CMakeFiles/libcurl.dir/build.make:2709: 
_deps/curl-build/dist/libcurl.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:264: _deps/curl-build/lib/CMakeFiles/libcurl.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

It should've compiled without any error, but there are errors.

Maybe I must be doing something wrong.

I'm using TDM GCC on a 64 bit Windows machine.

If anyone can reproduce this, please let me know.

I don't know of a possible fix as of now, I would appreciate it if a fix can be provided for this.

I don't know if CPR supports 32 bit compilation, but I'm still trying to do so.

Thanks in advance!

**Comment by COM8** [comment]
Thanks for reporting!
First of all, compiling works, but it fails during linking. Your issue is, that you try to link a `i386:x86-64` version of libcurl with to a `i386` binary. So something does not come through to when building libcurl. It still builds as 64-Bit target.

**Comment by COM8** [comment]
Based on the following StackOverflow article, you also have to specify the 32-Bit mode for the linker flags:
https://stackoverflow.com/questions/5805874/the-proper-way-of-forcing-a-32-bit-compile-using-cmake

**Comment by lthon09** [comment]
Do you think this is good?

```cmake
set_target_properties(cpr PROPERTIES COMPILE_FLAGS "-m32" LINK_FLAGS "-m32")
```

**Comment by lthon09** [comment]
```cmake
cmake_minimum_required(VERSION 3.24)

project(dropper)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_BUILD_TYPE "Release")

string(APPEND CMAKE_C_FLAGS " -m32")
string(APPEND CMAKE_CXX_FLAGS " -m32")

string(APPEND CMAKE_CXX_FLAGS " -s -O2")

set(CMAKE_WIN32_EXECUTABLE ON)

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})

add_executable(${PROJECT_NAME} main.cpp)

set_target_properties(${PROJECT_NAME} PROPERTIES COMPILE_FLAGS "-m32" LINK_FLAGS "-m32")

include(FetchContent)

FetchContent_Declare(cpr
    GIT_REPOSITORY https://github.com/libcpr/cpr.git
    GIT_TAG f9575ca983014f637f6f4956fc7d26b002fde7d1
)
FetchContent_MakeAvailable(cpr)

set_target_properties(cpr PROPERTIES COMPILE_FLAGS "-m32" LINK_FLAGS "-m32")

target_link_libraries(${PROJECT_NAME} PRIVATE cpr::cpr)
```

This is my current CMake file, please tell me if I'm doing something wrong, but it still isn't working yet.

Thanks!

**Comment by COM8** [comment]
I think it has to be:
```c++
set_target_properties(${PROJECT_NAME} PROPERTIES COMPILE_FLAGS "-m32" LINK_FLAGS "-m32")
```

instead of:
```c++
set_target_properties(cpr PROPERTIES COMPILE_FLAGS "-m32" LINK_FLAGS "-m32")
```

In case this does not work, I also don't know any further, but in my eyes this has to be a configuration error.
Some time next week I can have a deeper look into it.

**Comment by lthon09** [comment]
ive done that too, ive also tried compiling curl manually and it must be curl at fault here. idk why i cant compile it in 32 bit

**Comment by COM8** [comment]
How did you solve it?

**Comment by lthon09** [comment]
i switched to java from c++, and even if i didnt, my solution is to just compile for 64 bit only. i pretty much just gave up trying to compile for 32 bit so i thought id just close this

**Comment by COM8** [comment]
Oh wow 🤣 . Well, that's not the answer I was hoping for.

**Comment by lthon09** [comment]
)) unfortunate, cpr is a nice lib tho. its curl that i cant compile for 32 bit

**Comment by lthon09** [comment]
@COM8 problem solved, i just set the target system properties and libcurl successfully compiled

heres my cmake file:
```cmake
cmake_minimum_required(VERSION 3.24)

project(proj)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_BUILD_TYPE "Release")

set(CMAKE_WIN32_EXECUTABLE ON)

string(APPEND CMAKE_C_FLAGS " -m32")
string(APPEND CMAKE_CXX_FLAGS " -m32 -mwindows -s -O2")

set(CMAKE_SYSTEM_NAME "Windows")
set(CMAKE_SYSTEM_PROCESSOR "i386")

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})

set(BUILD_SHARED_LIBS OFF)

add_executable(${PROJECT_NAME} ...)

include(FetchContent)

FetchContent_Declare(cpr
    GIT_REPOSITORY https://github.com/libcpr/cpr.git
    GIT_TAG 7a02d679308a19220e3b75616c18ff9e8deb5f9a
)
FetchContent_MakeAvailable(cpr)

target_link_libraries(${PROJECT_NAME} PRIVATE cpr::cpr)
```

**Comment by COM8** [comment]
I'm glad to hear and thanks for publishing your findings here.
