### ISSUE TITLE
Some way to get a cpr::Payload object from a JSON string? (or update documentation showing how)

### ISSUE THREAD

**Issue by NateNate60** [libcpr/cpr#813]
**Is your feature request related to a problem? Please describe.**

There's a strange issue that I'm always bumping into. The scenario is that I have a JSON object string that I am trying to transmit as encoded form data. But where I get stuck is trying to transmit this data via a POST request. If there's already a way to do what I'm describing, I wasn't able to figure it out from reading the documentation. 

**Describe the solution you'd like**

I see two potential solutions:

- Add a fifth overload to the constructor of `cpr::Payload` with the signature `Payload (const std::string & json_string)` that initialises a `cpr::Payload` object from a JSON-format `std::string` (probably would be the most obvious and transparent to users)
- Make a new class `cpr::EncodedJSON` that represents a JSON object, and then allow the transmission of a `cpr::EncodedJSON` like a `cpr::Payload` or `cpr::Body`, translating it to encoded form data.

or, if the desired functionality already exists,

- document how to do it under "Introductions\#POST Requests" in the documentation

**Describe alternatives you've considered**

As far as I know, there isn't a neat way to do this; the two ways of transmitting data, as far as I gather from the documentation, are `cpr::Payload` and `cpr::Body`. `cpr::Payload` expects an initialisation list, so this probably won't work if the JSON object to be transmitted has varying numbers of keys (that isn't known until runtime). I'm not a C++ expert by any means, so maybe there *is* a way to do it that I just am not aware of. `cpr::Body` is promising. Still, AFAIK the data must be converted from a JSON string to URL-encoded form data manually, which is cumbersome, and then set the content type header appropriately.

I see a third potential solution involving parsing the JSON string, building a `std::map` or something, and then giving `cpr::Payload` iterators to the front and back of the map (which I assume is what `Payload<It>(const It begin, const It end)` means). But that isn't exactly much easier.

**Comment by COM8** [comment]
Sadly this is not possible since this would require us to add an additional dependency to for example `nlohman::json`.
But you can do the following: https://github.com/libcpr/cpr/issues/609#issuecomment-897423028

**Comment by NateNate60** [comment]
I have figured out a solution (or workaround, depending on how you look at it), and I think it should be added to the documentation. `cpr::Payload::Add` has the ability to add key-value pairs to a `cpr::Payload` object at runtime, and thus, it's just a case of parsing the JSON string into an iterable container (which is the responsibility of the user) and then calling `Add()` to add key-value pairs to the `cpr::Payload` object. It would work with a `std::map` (or similar STL container) or an `nlohmann::json`, it really just needs to be something that can be iterated over

```cpp
std::map<std::string, std::string> input_object = {{"key1", "value1"}, {"key2", "value2"}};
cpr::Payload payload_object;
for (auto & [key, value] : input_object) {
    payload_object.Add({key, value});
// simply give payload_object to cpr::Post or whatever to include that as the body!
```

`cpr::Payload::Add` isn't documented, but it should be.

**Comment by NateNate60** [comment]
@COM8
