### ISSUE TITLE
Killed, Exit Code 137

### ISSUE THREAD

**Issue by Pxddyk45** [libcpr/cpr#815]
## Expected Behavior

It should run normally
## Actual Behavior
It gets killed, error code 137
```
~/Dev/C++                                                                                                                                                                                   
❯ ./main
[1]    2182 killed     ./main

~/Dev/C++                                                                                                                                                                            
❯ echo $?
137
```
## Steps to Reproduce

code:
```
#include <iostream>
#include <cpr/cpr.h>
int main()
{
    cpr::Response r = cpr::Get(cpr::Url{"http://httpbin.org/get"});
    std::cout << r.text << '\n';
}
```
g++ arguments: -I./include -L./lib -lcpr -std=gnu++20

## Your Environment

* Where did you get it from (e.g. conan, vcpkg, master, ...): master
* Operating System and version: macOS Monterey 12.4 (M1)

**Comment by COM8** [comment]
To me error `137` sound like a memory issue. Perhaps something is wrong there when using a M1 Mac. Sadly I can not look deeper into this since I do not have access to a M1 Mac.

Any chance you could debug it a bit further using gdb, so we know at least where it is crashing?

**Comment by Pxddyk45** [comment]
Somehow it fixed itself by restarting my mac, if this occurs again i'll reopen the issue
