### ISSUE TITLE
Is there a way to reuse connections?

### ISSUE THREAD

**Issue by frankfreakpan** [libcpr/cpr#823]
Hi guys, amazing work! No more struggles with libcurl.
Since my project requires MTLS between client and sever, an new connection for every request is not acceptable. I'm trying to find a way to reuse the connections as much as possible between threads. I guess I'm looking for something like a connection pool sort of thing.
Can this be done with the existing interfaces from libcpr? Or do I have to manage the Sessions myself?

**Comment by COM8** [comment]
Try using a `cpr::Session` object. There you can perform multiple requests over the same session.
Docs: https://docs.libcpr.org/advanced-usage.html#session-objects

**Comment by frankfreakpan** [comment]
Thank you for your quick reply.
From my understanding Session is a wrapper around the libcurl handle, so that leads to the following questions:
1、Session.Get() perform in a blocking way, and It process requests on at a time right?
2、Is it safe to share Session in different threads?

**Comment by COM8** [comment]
1. Yes. But there are also options for async requests [here](https://docs.libcpr.org/advanced-usage.html#asynchronous-requests) and for multiple requests at a time [here](https://docs.libcpr.org/advanced-usage.html#multi-perform). But this requires multiple session objects.
2. No. One `cpr::Session` per thread.

**Comment by frankfreakpan** [comment]
OK, I think I understood most parts correctly. Async and multi might not exactly meet my needs, but I'll look more into those.
Last question: 
libcurl keeps a connections pool for each handle(in cpr's case it's Session), is that pool lost after curl_easy_cleanup? And In order to reuse that pool I have to reuse the handle(Session) as much as possible right?

**Comment by COM8** [comment]
When you destroy a session, we also cleanup the curl handle for you:
https://github.com/libcpr/cpr/blob/c642a767e7788d8ccd3de8ddfae00cd92d12d715/cpr/curlholder.cpp#L21-L26

As long as this curl handle exists, curl keeps it inside its session pool.

**Comment by frankfreakpan** [comment]
Thank you,
