### ISSUE TITLE
vcpkg cpr[core]:x64-windows update to new version request

### ISSUE THREAD

**Issue by lightheart33** [libcpr/cpr#826]
Library name: cpr[core]:x64-windows

New version number: 1.9.2 or later (One that support Authentication (HTTP Authorization) Basic and Bearer).

Other information that may be useful (release notes, etc...)

With Visual Studio 2017 I first tried the NuGet package version 1.9.2, somehow I have problem with it, it cannot include cpr/cpr.h.
So instead I tried vcpkg cpr[core]:x64-windows, it compiles fine, but its still version 1.3.0-8,
and I need Basic Authorization for obtaining the OAuth2 access token,
and Bearer Authorization for the following REST requests.
Unfortunately these seem not to be supported in version 1.3.0-8, but they seem to be supported in 1.9.2 or later,
so it would be nice if vcpkg cpr[core]:x64-windows could be updated to a newer version that support those.

Thanks for considering! M

**Comment by COM8** [comment]
So, I don't really get your issue :)

You are trying to use cpr 1.3.0 via vcpkg? But you require features from 1.9.2, right?
But why don't you use 1.9.2. What is your issue, what error does it produce?

Please use the issue template the next time you create a new issue.

**Comment by lightheart33** [comment]
>You are trying to use cpr 1.3.0 via vcpkg?
Yes that works.
>But you require features from 1.9.2, right?
Correct, yes
>But why don't you use 1.9.2. What is your issue, what error does it produce?
Because the only version that I seem to be available to get with vcpkg is 1.3.0:
C:\sources\git\vcpkg>vcpkg search cpr
cpr                  1.3.0-8          C++ Requests is a simple wrapper around libcurl inspired by the excellent Pyth...
I would luv to use 1.9.2, but how do I get the version 1.9.2 down with vcpkg?
If a newer version is available over vcpkg? I could try creating a vcpkg.json that forces it to this version.

>Please use the issue template the next time you create a new issue.
ok will do :)

**Comment by COM8** [comment]
Sorry, but we don't maintain the vcpkg package. Please create an issue or PR here: https://github.com/Microsoft/vcpkg

**Comment by lightheart33** [comment]
Ok, thank you, I will.
