### ISSUE TITLE
[question] how to support both http and https in one cpr call

### ISSUE THREAD

**Issue by laoshanxi** [libcpr/cpr#828]
Hi,

the target REST url (m_url) might be http or https, and I used cpr::SslOptions in case of SSL, how could I use sslOpts parameter but also support http call?
```
cpr::SslOptions sslOpts;
sslOpts.verify_host = false;
sslOpts.verify_peer = false;
cpr::Response r = cpr::Download(fileStream, cpr::Url{m_url, restPath}, cprHeader, sslOpts);
```

**Comment by COM8** [comment]
`cpr::SslOptions` apply only in case you perform an HTTPS request. For HTTP requests they will be ignored.

Is this what you were asking? Sorry I don't completely get your question.

**Comment by laoshanxi** [comment]
Thanks for your response, that's the answer.
