### ISSUE TITLE
download

### ISSUE THREAD

**Issue by AdmiralNicherov** [libcpr/cpr#832]
what kind of nonsense do I have to download all sorts of cmake git why can't you make me download just 1 file moved it and that's all why should I suffer

**Comment by COM8** [comment]
![image](https://user-images.githubusercontent.com/11741404/193232913-1cb0abbb-ab1a-47e4-8342-d1fb6fc06bb2.png)

Thank you for your kind and constructive issue/feature request. This is really something that helps us humans becoming a multi planetary race 🤠.

Nevertheless I see, where you are coming from. The next time please take your time to elaborate your use case a bit more and let us know if you have any real suggestions how we can improve the current situation.
Please remember that we are not paid to solve or even answer your issues, so we do all this work in OUR free time.

Still I would like to try helping you with your issue.
There are in fact one click solutions out there.
1. [NuGet](https://www.nuget.org/packages/libcpr) Windows and Linux
2. [vcpkg](https://vcpkg.io/en/index.html) Windows Linux
3. There is an [AUR](https://aur.archlinux.org/packages/cpr) Arch Linux package
4. Our CI produces a Debian package: https://github.com/libcpr/cpr/actions/workflows/build-deb.yml

All of those simply can be installed with one click/command and then you can link against them using `-lcpr`.

### Why does one need a build system for C++?
Well we could go into this discussion why one should use CMake and why it solves an unnecessary problem but frankly I don't have the time for it and I'm the wrong one for this discussion.

But in case you really don't want to use a build system, try switching to an other language like C# or Python. You loose performance, but they are more "beginner friendly" in that case 😊.
