### ISSUE TITLE
vcpkg cpr: static libraries (x64)

### ISSUE THREAD

**Issue by hiroashikawa** [libcpr/cpr#838]
## Description
I installed following vcpkg dependencies:
```
cpr:x86-windows
cpr:x64-windows
cpr
curl:x86-windows
curl:x64-windows
```
After Enabling Static Libraries in the Vcpkg Settings in my project and compiling I get following errors (Yes /MT results in that issue, /MD will compile but will again drop dlls):
![devenv_zcxf6hRvU3](https://user-images.githubusercontent.com/91470165/195137845-29c16760-dcd5-4d99-a2e4-c10aeafe06ec.png)

## Expected Behavior
Compile using Static Libraries, no external DLLs, single .exe file.

## Actual Behavior
Compiler gives errors, wont compile.

## Possible Fix
N/A

## Steps to Reproduce

1. Install vcpkg
2. Install all the dependencies I listed in my description
3. Create a C++ Project, enable Static Libraries in the vcpkg project settings tab
4. `#include <cpr/cpr.h>` Include this anywhere, compile, errors.

## Context
I am trying to use CPR For POST/GET Requests as I really like the library, but I really hate getting those libcurl, zlib dlls.

## Your Environment

* Version used: latest vcpkg, latest cpr from vcpkg
* Where did you get it from (e.g. conan, vcpkg, master, ...): vcpkg
* Operating System and version: Windows 10 x64, 21H1 (19043.2006)
* Link to a small example:

**Comment by COM8** [comment]
The vcpkg package is not maintained by us. Please create an issue here: https://github.com/Microsoft/vcpkg
