### ISSUE TITLE
cpr::Session not allowed for NRVO

### ISSUE THREAD

**Issue by rlalik** [libcpr/cpr#845]
### Description

When using `cpr::Session` in kind of builder function the NRVO is not possible. See following example:
```c++
#include <cpr/cpr.h>
auto f() {
    cpr::Session s;
    return s;
}
int main() {
    auto s = f();
    return 0;
}
```
which compiled with `gcc -std=c++17` (NRVO and RVO are mandatory, gcc-11.3.0 and gcc-12.2.0 tested) yields an error:
> test.cc:4:12: error: use of deleted function ?cpr::Session::Session(const cpr::Session&)?
>   4 |     return s;

The RVO works as expected:
```c++
#include <cpr/cpr.h>
auto f() {
    return cpr::Session();
}
int main() {
    auto s = f();
    return 0;
}
```
From inspection of `session.h` seems that `cpr::Session` breaks rule of five and is missing `Session(Session && other)` move constructor. Adding it seems to be solving problem, unless there is a reason why it should not be allowed, but then should perhaps be declared as deleted. The compilator will not instate a default one.

### Example/How to Reproduce

Create an example as described above.

### Possible Fix

Adding move constructor:
```c++
Session(Session && other) = default;
```
seems to be fixing the problem.

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

- OS: Linux
- Version: 1.9.2 and current master

**Comment by COM8** [comment]
Thanks for reporting!
I created a PR to fix this: #848
