### ISSUE TITLE
CMake config not saved if CPR_USE_SYSTEM_CURL is FALSE

### ISSUE THREAD

**Issue by paskino** [libcpr/cpr#847]
### Description

I'm building a project depending on cpr which uses `find_package(cpr REQUIRED)`. Is there a reason why you do not save the configuration if `CPR_USE_SYSTEM_CURL` is set to `FALSE`?

https://github.com/libcpr/cpr/blob/5ae5fdeadfbbb784192c034be0222016123c94ad/cpr/CMakeLists.txt#L62-L69

### Example/How to Reproduce

N/A

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

- OS: Ubuntu 18.04
- Version: 5ae5fdeadfbbb784192c034be0222016123c94ad

**Comment by paskino** [comment]
I will retry, but it didn't seem to have lead to the expected result.

**Comment by KingKili** [comment]
Did you also set `CPR_USE_SYSTEM_CURL` to true? Can you show me the CMake output?

**Comment by paskino** [comment]
Hi, I had to install `libcurl4-openssl-dev` on my ubuntu machine and then I was successful with `CPR_USE_SYSTEM_CURL=ON`
