### ISSUE TITLE
cpr::MultiPerform not available

### ISSUE THREAD

**Issue by immerhart** [libcpr/cpr#849]
### Description

Added cpr over 
```
include(FetchContent)
FetchContent_Declare(cpr GIT_REPOSITORY https://github.com/libcpr/cpr.git
                         GIT_TAG f88fd7737de3e640c61703eb57a0fa0ce00c60cd) # The commit hash for 1.9.2. Replace with the latest from: https://github.com/libcpr/cpr/releases
FetchContent_MakeAvailable(cpr)
```
to the cmake project, but `MultiPerform` seems to be missing completely (header is not present in the include dir).
I tried it with `1.9.0` as well.
Is there some setting needed? Should it be included in 1.9.2?

### Example/How to Reproduce

NA

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

- OS: Ubuntu 20.04.4
- Version: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
- cmake version 3.16.3

**Comment by COM8** [comment]
Multiperform is a `1.10.0` [feature](https://github.com/libcpr/cpr/pull/770). To use it please use at least 5ae5fdeadfbbb784192c034be0222016123c94ad.
