### ISSUE TITLE
dyld[44965]: symbol not found in flat namespace '__ZN3cpr10ParametersC1ERKSt16initializer_listINS_9ParameterEE'

### ISSUE THREAD

**Issue by HenryChen-CH** [libcpr/cpr#856]
### Description

I have a code that use cpr library. I build it on MacBook with M1 chip. 
the build is successful but it throws run time error.
this error code __ZN3cpr10ParametersC1ERKSt16initializer_listINS_9ParameterEE has the key word: cpr parameters, initializer. it seems to indicate the issue is with cpr parameters initializer. however I don't know what's wrong exactly. 

### Example/How to Reproduce

1. Create a cpr get request with cpr parameter
2. Perform the request
3. build
4. run

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

- OS: Mac OS
- Version: 13.0.1

**Comment by COM8** [comment]
After [demangling](http://demangler.com/) it, it results in: `_cpr::Parameters::Parameters(std::initializer_list<cpr::Parameter> const&)`

Could it be that you own a M1 Mac?

**Comment by COM8** [comment]
Could you please provide a complete log of the crash?

**Comment by COM8** [comment]
Closing this one for inactivity.
