### ISSUE TITLE
_ITERATOR_DEBUG_LEVEL and RuntimeLibrary missmatches

### ISSUE THREAD

**Issue by Sm0k3Official** [libcpr/cpr#858]
### Description

Hi there, I need to use cpr header for a project and I encounter some errors while building the solution for the first time after adding the cpr/cpr.h header. I was searching all over the place to fix it, I even try to change the RuntimeLibraries from MD to MDd and nothing. (or maybe I didn't do it in a correct way)

![image](https://user-images.githubusercontent.com/46896531/206856876-b608f869-c911-474f-b42b-8908f2d4f616.png)

If I will comment the 55th line, the app will start building fine. 
![image](https://user-images.githubusercontent.com/46896531/206857203-744d875c-6a2f-42af-ac7f-ef02ff6675e7.png)

Here are the project settings
![image](https://user-images.githubusercontent.com/46896531/206857566-36d45401-5438-4502-85f9-0eb41e160704.png)
![image](https://user-images.githubusercontent.com/46896531/206857571-d9e864ff-189e-4538-957e-89f6d4aab112.png)

### Example/How to Reproduce

Down there I put the Login.h and Login.cpp files (in the last file I need to use CPR to extract data from a link) . 

Login.h
```cpp
#pragma once

#include <QDialog>

#include "ui_Login.h"

#include <QFile>
#include <QTextStream>

#include <cpr/cpr.h>

class Login : public QDialog
{
	Q_OBJECT

private:
	Ui::Login ui;

public:
	explicit Login();
	~Login();

private slots:
	void on_loginPushButton_released();

public:
	const std::string GetUsername() const;
	const std::string GetPassword() const;	
};
```

Login.cpp
```cpp
#include "Login.h"

Login::Login()
{
	ui.setupUi(this);

	ui.passwordLineEdit->setEchoMode(QLineEdit::Password);
}

Login::~Login()
{
}

const std::string Login::GetUsername() const
{
	return ui.usernameLineEdit->text().toStdString();
}

const std::string Login::GetPassword() const
{
	return ui.passwordLineEdit->text().toStdString();
}

void Login::on_loginPushButton_released()
{
	auto username = GetUsername();
	auto password = GetPassword();

	cpr::Response response = cpr::Get(cpr::Url{ "http://localhost:18080/users" });
}
```

### Where did you get it from?

vcpkg

### Additional Context/Your Environment

- OS: W11
- Version: 22H2

**Comment by COM8** [comment]
Thanks for reporting but I don't think this is a cpr issue ([more](https://stackoverflow.com/questions/7668200/error-lnk2038-mismatch-detected-for-iterator-debug-level-value-0-doesnt)). In case you provide a minimal example with just cpr (as a zip), I can have a look at it.

**Comment by Sm0k3Official** [comment]
Yeah sure. Should I put here the zip file or I should sent it to you via discord ?

**Comment by Sm0k3Official** [comment]
Hi, sorry for responding so late. I had some extra work to do. Long story short, I created a new project with just a few classes, just for testing if does it really work. And it doesn't work, I'm receiving the same error. :(

The big project is in the same configuration as the newest one (see the project specs below).

Here is the new project ( VS 2022 v143 project with 10.0.22000 SDK )
https://we.tl/t-7bd2B8BG2T

**Comment by COM8** [comment]
Could you please provide me a *minimal* project, with only cpr as dependency? In your provided example there are to many variables, that influence the build process.

**Comment by Sm0k3Official** [comment]
Hi, I found that when I set in the project settings to **Debug Configuration**, **RuntimeLibrary** to **MD**, the **strings** go to a different planet and **display unreadable characters**.

**Comment by Sm0k3Official** [comment]
Hi again, I found that u have a nuget package (**libcpr** to be more speciffic) and I said "hmm, let's try this one too and see if this can fix my problem" **(P.S. Actually it did)**. 

Long story short, **the steps** to solve the above mentioned problems are:
- in **project settings**, I set the **C++ standard** to **C++20** (at least **C++20**)
- I installed the **libcpr nuget** (found on **nuget.org**)

After these steps, **all the bugs are gone** (the bugs with the strings and those missmatches between MD and MDd are gone) and all is working fine.

Thanks for all the support!

**Comment by COM8** [comment]
Great to hear. Than I'm closing this one until we have a reproducible minimal project for it.
