### ISSUE TITLE
cpr::MultiPerform not using the logging interceptor

### ISSUE THREAD

**Issue by GloriousWizard** [libcpr/cpr#862]
### Description

Adding a session with an interceptor to a cpr::MultiPerform does not print out any information to the command line. 

### Example/How to Reproduce

```c++

cpr::Response LoggingInterceptor::intercept(cpr::Session& session)
{
    // Log the request URL
    std::cout << "Request url:  " << session.GetFullRequestUrl() << '\n';

    // Proceed the request and save the response
    cpr::Response response = proceed(session);

    // Log response status code
    std::cout << "Response status code:  " << response.status_code << '\n';

    // Return the stored response
    return response;
}

int main()
{
    cpr::MultiPerform multiPerform;
    std::shared_ptr<cpr::Session> session = std::make_shared<cpr::Session>();

    session->SetUrl("duckduckgo.com");
    session->AddInterceptor(std::make_shared<LoggingInterceptor>());

    multiPerform1.AddSession(session);
    std::vector<cpr::Response> responses = multiPerform.Get();
}
```

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

- OS: Nobara
- Version: 36
- Using commit `1986262ba4e0cb052161e9e7919aef5ef08217f0`

**Comment by COM8** [comment]
Thank you very much for reporting this!
This is an oversight from our side.

I created a PR (https://github.com/libcpr/cpr/pull/863) with a fix for it. Could you please try, if it fulfils your needs?

**Comment by GloriousWizard** [comment]
It solves my issue. You can merge the PR.
