### ISSUE TITLE
cpr dependency using static build : cpack tries to install zlib.a to /usr/local/lib directory 

### ISSUE THREAD

**Issue by boxerab** [libcpr/cpr#866]
I am using cpr in another cmake project, linking as follows:

```
include(FetchContent)
FetchContent_Declare(cpr GIT_REPOSITORY https://github.com/libcpr/cpr.git
                         GIT_TAG a2d35a1cb9f3f7e2f1469d6a189751331dc99f96) # The commit hash for 1.9.0. Replace with the latest from: https://github.com/libcpr/cpr/releases
FetchContent_MakeAvailable(cpr)
```

`BUILD_SHARED` is OFF

When I try to package the parent project with `CPack`, I get the following errors :

```
CMake Error at /home/parent_proj/_deps/zlib-build/cmake_install.cmake:54 (file):
  file INSTALL cannot set permissions on "/usr/local/lib/libz.a": Operation
  not permitted.
```

So, the only way to do it at the moment is to call CPack with sudo, which I would rather avoid doing.

Is there a way of disabling zlib.a installation ?  Persumably this is a libcurl dep.  Thanks!

**Comment by boxerab** [comment]
Solution is to replace

`FetchContent_MakeAvailable(cpr)`

with

```
if(NOT cpr_POPULATED)
    FetchContent_Populate(cpr)
    add_subdirectory(${cpr_SOURCE_DIR} ${cpr_BINARY_DIR} EXCLUDE_FROM_ALL)
endif()
```

**Comment by COM8** [comment]
Hey, thanks for reporting and I'm glad you were able to fix it.

@KingKili Is there something we can/have to fix here on our side with zlib?

**Comment by KingKili** [comment]
I see a couple of semi fixes we can implement. But overall libcurl as a dependency and installing / packing was also problematic for PaperSearch.

1.  Use system curl per default
2.  Disable zlib per default
3. We can probably use the `EXCLUDE_FROM_ALL` fix for zlib
