### ISSUE TITLE
Build error: ‘void curl_formfree(curl_httppost*)’ is deprecated: since 7.56.0. 

### ISSUE THREAD

**Issue by rathnadhar** [libcpr/cpr#870]
### Description

On my Linux OpenSuse TumbleWeed I have :  libcurl 7.87

I built CPR exactly as stated in the landing page:

```
$ git clone https://github.com/libcpr/cpr.git
$ cd cpr && mkdir build && cd build
$ cmake .. -DCPR_USE_SYSTEM_CURL=ON
$ cmake --build .
```

During the build  I get this compilation error:
```
[ 32%] Building CXX object cpr/CMakeFiles/cpr.dir/curlholder.cpp.o
/home/rathnadhar/karyagara/external/software/cpr/build/debug/test/cpr/cpr/curlholder.cpp: In destructor ‘cpr::CurlHolder::~CurlHolder()’:
/home/rathnadhar/karyagara/external/software/cpr/build/debug/test/cpr/cpr/curlholder.cpp:24:18: error: ‘void curl_formfree(curl_httppost*)’ is deprecated: since 7.56.0. Use curl_mime_free() [-Werror=deprecated-declarations]
   24 |     curl_formfree(formpost);
      |     ~~~~~~~~~~~~~^~~~~~~~~~
In file included from /home/rathnadhar/karyagara/external/software/cpr/build/debug/test/cpr/include/cpr/curlholder.h:8,
                 from /home/rathnadhar/karyagara/external/software/cpr/build/debug/test/cpr/cpr/curlholder.cpp:1:
/usr/include/curl/curl.h:2606:1: note: declared here
 2606 | curl_formfree(struct curl_httppost *form);
      | ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
gmake[2]: *** [cpr/CMakeFiles/cpr.dir/build.make:188: cpr/CMakeFiles/cpr.dir/curlholder.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:116: cpr/CMakeFiles/cpr.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

CPR is using a deprecated API.

If I use: `cmake .. -DCPR_USE_SYSTEM_CURL=OFF`

then it builds the libcurl and then libcpr correctly.

CURL provided with cpr is dated. If the above build issue is not fixed, then I am struck with old version of curl for ever.

Its critical that the above build issue is fixed.

### Example/How to Reproduce

$ git clone https://github.com/libcpr/cpr.git
$ cd cpr && mkdir build && cd build
$ cmake .. -DCPR_USE_SYSTEM_CURL=ON
$ cmake --build .

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

- OS: OpenSuSE Tumbleweed Linux
- Version: rolling.
curl is :  7.87

**Comment by COM8** [comment]
@rathnadhar Thanks for reporting!

Sorry for the delayed response, we are currently on vacation until March 01, 2023.

I expected something like this to happen at one point. Arg...
Due to a Windows memory handling bug in curl, we can not update our API accordingly right now. (See: https://github.com/libcpr/cpr/issues/804)

But we can have a look at it once we are back, or do you have time to look into this in the meantime?

**Comment by chenrui333** [comment]
Any update on this thread? I saw there is a new [release 1.10.1 today](https://github.com/Homebrew/homebrew-core/pull/124820), but still have the same build failure.

**Comment by COM8** [comment]
I plan to look into it soon. The 1.10.1 release was a hotfix that needed to go out quickly.

**Comment by tolstenko** [comment]
Just to ping and be involved. 
I am using CPM to manage the packages.
Here goes the cmake I created.
```
CPMAddPackage("gh:Mbed-TLS/mbedtls#v3.3.0")
include_directories(${mbedtls_SOURCE_DIR}/include)
CPMAddPackage(
  GITHUB_REPOSITORY curl/curl
  GIT_TAG curl-7_88_1
  OPTIONS "CURL_USE_MBEDTLS ON" "MBEDTLS_INCLUDE_DIRS ${mbedtls_SOURCE_DIR}/include"
          "MBEDTLS_LIBRARY mbedtls" "MBEDX509_LIBRARY mbedcrypto" "MBEDCRYPTO_LIBRARY mbedx509"
          "BUILD_TESTING OFF"
)
include_directories(${curl_SOURCE_DIR}/include)
CPMAddPackage(
  GITHUB_REPOSITORY libcpr/cpr
  GIT_TAG 1.10.1
  OPTIONS "CPR_ENABLE_SSL ON" "CPR_FORCE_MBEDTLS_BACKEND ON" "CURL_USE_MBEDTLS ON"
)
include_directories(${cpr_SOURCE_DIR}/include)
include_directories(${cpr_BUILD_DIR}/cpr_generated_includes)
```
I am facing this:
```
cpr/curlholder.cpp:24:18: error: ‘void curl_formfree(curl_httppost*)’ is deprecated: since 7.56.0. Use curl_mime_free() [-Werror=deprecated-declarations]
```

**Comment by COM8** [comment]
The branch `curl_formfree_deprecation` contains a fix for it. Could one verify that it fixes it.

Once someone verified it, I will create a new 1.9.x and 1.10.x release for it.

**Comment by COM8** [comment]
https://github.com/libcpr/cpr/pull/890

**Comment by akatran** [comment]
I can verify that I was able to compile the code from this branch without the verification errors.

OS: Arch Linux
Version: Rolling
Curl: 7.88.1
