### ISSUE TITLE
use curl's SMTP component with cpr installed

### ISSUE THREAD

**Issue by christk1** [libcpr/cpr#872]
I need to use this library with cmake on my project to make requests but I also need libcurl SMTP support inside my project. The SMTP is disabled in the curl installed with the cpr lib. Is there any workaround?

**Comment by christk1** [comment]
created a [merge request](https://github.com/libcpr/cpr/pull/873) to make this simple. Please review, setting  CPR_USE_SYSTEM_CURL=OFF is not working and i get the message that I don't have curl installed in my system. I can verify that it exists using ``` curl --version | head -n 1 | awk '{ print $2 }' ```

**Comment by COM8** [comment]
You need to have the curl dev packages installed for your distribution (e.g. `curl-devel` on fedora).
