### ISSUE TITLE
INVALID_URL_FORMAT has no error message

### ISSUE THREAD

**Issue by offa** [libcpr/cpr#882]
### Description

`INVALID_URL_FORMAT` errors don't contain an error message but an empty string.

### Example/How to Reproduce

```cpp
const auto response = cpr::Get(cpr::Url{"an invalid url"});

if (const auto error = response.error; error)
{
    std::cout << "<" << static_cast<int>(response.error.code) << ">: <" << error.message << ">\n";
}
```

#### Output:

```
<5>: <>
```
(5 is `ErrorCode::INVALID_URL_FORMAT`)

### Where did you get it from?

conan

### Additional Context/Your Environment

- OS: Linux (GCC 12 / Clang 15)
- Version: cpr 1.9.3

**Comment by COM8** [comment]
Thanks for reporting but there is nothing we can do about it since this what we get from curl.
