### ISSUE TITLE
[about multi curl]

### ISSUE THREAD

**Issue by babA409866** [libcpr/cpr#895]
### Is your feature request related to a problem?

can u provide some way to set the options of multi curl obj.
base on the libcurl function curl_multi_setopt

### Possible Solution

add function like SetOption to MultiCurl

**Comment by COM8** [comment]
Thanks for opening this feature request @babA409866 .
Do I understand it correctly, you want access to the `CURLM`  object, so you can set options manually there?

If you want to set options on the sessions you are passing, this can be done before (and after) calling `multiperform.AddSession(your_session_object)`.
