### ISSUE TITLE
CPR is stuck and server reports" java.io.IOException: Connection reset by peer"

### ISSUE THREAD

**Issue by HenryChen-CH** [libcpr/cpr#898]
### Description

I have a client that sends  http request to server.
 the program has a thread that consumes the queue and sends a package to the server per item in queue.
I find that sometime the thread stops consuming queue and server reports "java.io.IOException: Connection reset by peer"
I have tried to catch exception but it seems that there isn't any exception

### Example/How to Reproduce

1. Create a `cpr::Session`
2. Set option ...
3. Perform the request

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

- OS:
- Version:
Ubuntu

**Comment by COM8** [comment]
@HenryChen-CH  thank you for reporting this. Is there any way we can reproduce this?
