### ISSUE TITLE
http proxy   fail to work

### ISSUE THREAD

**Issue by khtkiprw** [libcpr/cpr#900]
### Description

With http proxies, authentication is always required
![image](https://user-images.githubusercontent.com/38189984/232835468-8dfb2d5a-7c33-47dc-a293-539b72456d63.png)

Is this header correct?
![image](https://user-images.githubusercontent.com/38189984/232835756-80cb597f-71c0-44c0-8799-2d273c493043.png)

### Example/How to Reproduce

	cpr::Session session;
	session.SetProxies({ {"http","http://44.199.26.89:31112"},{"https","http://44.199.26.89:31112"} });
	session.SetProxyAuth(cpr::ProxyAuthentication({{"http",cpr::EncodedAuthentication("khXXX","PtsIjHXXX")},{"https",cpr::EncodedAuthentication("khtXXX","PtsIjHBYXXX")}}));
	session.SetUrl("https://www.taobao.com/help/getip.php");
	cpr::Response resp = session.Get();
	std::cout << resp.text;

### Where did you get it from?

vcpkg

### Additional Context/Your Environment

- OS:
- Version:

**Comment by khtkiprw** [comment]
proxy authentication I'm sure it's correct
Since I use the Socks5 proxy, it works fine, but trying to use the http proxy results in an error, always returning 407

![image](https://user-images.githubusercontent.com/38189984/232988700-613fb7f7-3cdc-4f66-b460-5ecb13353862.png)

There is also a response header, which should be a combination of a connection proxy response header and a data request response header

**Comment by COM8** [comment]
Hmmm 407 indicates an authentication issue.
We had an other report about this [here](https://github.com/libcpr/cpr/pull/875) with a fix for it that is going to be released in 1.11.0 since it introduces breaking changes. Any chance you can try with a current master build?

**Comment by khtkiprw** [comment]
We tested that the main build http proxy worked. Thank you very much

**Comment by khtkiprw** [comment]
http proxy worked from master build. Thank you very much

**Comment by COM8** [comment]
Awesome!
