### ISSUE TITLE
Could NOT find CURL (missing: HTTP) (found version "7.80.0")

### ISSUE THREAD

**Issue by ronytigo** [libcpr/cpr#907]
### Description

I followed the instructions to install cpr.
when I run `cmake .. -DCPR_USE_SYSTEM_CURL=ON` I get this error:
```
-- Could NOT find CURL (missing: HTTP) (found version "7.80.0")
-- Could NOT find CURL (missing: HTTP) (found version "7.80.0")
CMake Error at CMakeLists.txt:193 (message):
  Curl not found on this system.  To use the built-in version set
  CPR_USE_SYSTEM_CURL to OFF.
```

### Example/How to Reproduce

$ git clone https://github.com/libcpr/cpr.git
$ cd cpr && mkdir build && cd build
$ cmake .. -DCPR_USE_SYSTEM_CURL=ON

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

**Comment by COM8** [comment]
Try `sudo apt install libcurl-dev` since if you set `CPR_USE_SYSTEM_CURL` to `ON` it requires the curl header files on your system.

**Comment by ronytigo** [comment]
This one is not working but I did run `sudo apt install libcurlpp-dev` and it didn't help.

**Comment by ronytigo** [comment]
OK I think I missed on `cd cpr`, but now I get this error:
```
CMake Error at /usr/share/cmake-3.16/Modules/WriteBasicConfigVersionFile.cmake:43 (message):
  No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CMakePackageConfigHelpers.cmake:225 (write_basic_config_version_file)
  CMakeLists.txt:63 (write_basic_package_version_file)
```

**Comment by COM8** [comment]
On a clean `ubuntu:20.04` container for me all works as expected. You are installing the `cpp` bindings for libcurl. But we need the c bindings.

Here is how I did it:
```bash
git clone https://github.com/libcpr/cpr.git
cd cpr
mkdir build && cd build
apt install libssl-dev gcc g++ cmake git libcurl4-openssl-dev
cmake .. -DCPR_USE_SYSTEM_CURL=ON
cmake --build . --parallel
cmake --build . --target install
```
