### ISSUE TITLE
file INSTALL cannot find .../cpr/build/cpr/CMakeFiles/CMakeRelink.dir/libcpr.so.1.11.0

### ISSUE THREAD

**Issue by ronytigo** [libcpr/cpr#908]
### Description

when running `sudo cmake --install .` from the build directory I get:
```
CMake Error at cpr/cmake_install.cmake:46 (file):
  file INSTALL cannot find
  "/home/user/myproject/cpr/build/cpr/CMakeFiles/CMakeRelink.dir/libcpr.so.1.11.0":
  No such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)
```

### Example/How to Reproduce

run `sudo cmake --install .` from the build directory

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

**Comment by ronytigo** [comment]
the `cpr/build/lib` directory is empty

**Comment by COM8** [comment]
@ronytigo thanks for reporting this. I will have a look at it on the weekend.

**Comment by ronytigo** [comment]
OK, adding sudo to the other commands and not just the last one, solved it.
