### ISSUE TITLE
error while loading shared libraries: libcpr.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ronytigo** [libcpr/cpr#910]
### Description

I get this error only when run inside a container.
CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.13)
project(proj)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)
set(SOURCE_FILES main.cpp tags.cpp)
find_package(cpr REQUIRED)
add_executable(proj ${SOURCE_FILES})
target_link_libraries(proj PRIVATE cpr::cpr)
```

### Example/How to Reproduce

1. Create a `cpr::Session`
2. Set option ...
3. Perform the request

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

ubuntu

**Comment by COM8** [comment]
I can not reproduce this issue inside my `ubuntu:20.04` container. It looks like installing cpr failed for you.
I'm compiling with the following `main.cpp`: https://github.com/libcpr/example-cmake-fetch-content/blob/main/main.cpp

Please elaborate. How did you install cpr?

**Comment by COM8** [comment]
Also as a pointer, here you find an other  working cmake example for cpr: https://github.com/libcpr/example-cmake-fetch-content/tree/main

**Comment by ronytigo** [comment]
I had `FROM ubuntu:20.04 as build-deps` and later `FROM ubuntu:20.04`. I didn't install cpr in the second one.
Can I just copy the necessary files from the first installation or I have to install it again?
This is from the DockerFile:
```
WORKDIR /app/proj/deps/cpr
RUN sudo mkdir build
WORKDIR /app/proj/deps/cpr/build
RUN sudo cmake .. -DCPR_USE_SYSTEM_CURL=ON
RUN sudo cmake --build .
RUN sudo cmake --install .
```

**Comment by COM8** [comment]
You have to copy all files to the correct directories. This is the issue.

**Comment by ronytigo** [comment]
just copy all libcpr* files from /usr/loca/lib?

**Comment by COM8** [comment]
Yes, but it depends how you build it. Make sure you make a static build by passing `-DBUILD_SHARED_LIBS=OFF` during configuring.
