### ISSUE TITLE
Doc text outdated

### ISSUE THREAD

**Issue by AndrewHC36** [libcpr/cpr#917]
### Description

An outdated short paragraph under "Other Request Methods" in "Advanced Usage" in the documentation.

### Example/How to Reproduce

1. Go to [https://docs.libcpr.org/advanced-usage.html#other-request-methods](https://docs.libcpr.org/advanced-usage.html#other-request-methods)
2. Last paragraph

### Possible Fix

Remove that entire small paragraph.

### Where did you get it from?

Other (specify in "Additional Context/Your Environment")

### Additional Context/Your Environment

Looking for the DELETE request method, and came across a small, outdated blurb on the bottom. Thought this may cause some lack of clarity, but it shouldn't be a big deal.

**Comment by AndrewHC36** [comment]
The small paragraph regarding the "PATCH" request is going to be added soon.

**Comment by COM8** [comment]
Thanks for reporting! I updated the docs accordingly: https://github.com/libcpr/docs/pull/39
