### ISSUE TITLE
Not working properly with libcurl v8.1.2

### ISSUE THREAD

**Issue by ZACKhdn** [libcpr/cpr#919]
### Description

If I use libcurl v8.1.2，the gzip cannot work.
In session.cpp, I found the following content:
```
#if LIBCURL_VERSION_MAJOR >= 7
#if LIBCURL_VERSION_MINOR >= 21
    if (acceptEncoding_.empty()) {
        /* enable all supported built-in compressions */
        curl_easy_setopt(curl_->handle, CURLOPT_ACCEPT_ENCODING, "");
    } else {
        curl_easy_setopt(curl_->handle, CURLOPT_ACCEPT_ENCODING, acceptEncoding_.getString().c_str());
    }
#endif
#endif
```
Maybe this part needs to be revised

**Comment by COM8** [comment]
I created a fix for it here: https://github.com/libcpr/cpr/pull/922

Could you please validate that it fixes your issues?

**Comment by ZACKhdn** [comment]
> I created a fix for it here: #922
> 
> Could you please validate that it fixes your issues?

Yes, it works properly. I have already modified and used it like this.
I found a macro "__LIBCURL_VERSION_GTE" in ssl_options.h, perhaps you can consider using this macro.

**Comment by COM8** [comment]
Good point! Simplified it even further by using the hex version number.
`__LIBCURL_VERSION_GTE` and `__LIBCURL_VERSION_LTE` will be replaced at one point with this way of comparing versions as well.

**Comment by ZACKhdn** [comment]
> Good point! Simplified it even further by using the hex version number.
> `__LIBCURL_VERSION_GTE` and `__LIBCURL_VERSION_LTE` will be replaced at one point with this way of comparing versions as well.

OK，thank you for your work.
