### ISSUE TITLE
NETWORK_RECEIVE_ERROR (6) appears when calling GET request with header

### ISSUE THREAD

**Issue by MrVolot** [libcpr/cpr#921]
### Description

The issue is with the GET request. When sending, sometimes it passes but usually I get "NETWORK_RECEIVE_ERROR (6)". I checked the server and it works totally fine. Also, I tried creating a python script to run the same request and I didn't face any issues there, so my guess the problem is somewhere in the library. Here is what I tried to do:

```
{
	std::string url = "https://openapi.keycrm.app/v1/products/categories?limit=50";

	const int max_retries = 3;
	const int delay_seconds = 2;

	cpr::Header headers = {
		{"Content-type", "application/json"},
		{"Accept", "application/json"},
		{"Cache-Control", "no-cache"},
		{"Pragma", "no-cache"},
		{"Authorization", "Bearer " + token}
	};
	for (int i = 0; i < max_retries; i++) {
		auto categoriesResponse = cpr::Get(cpr::Url{ url }, headers);
		if (categoriesResponse.error) {
			std::cerr << "Error " << categoriesResponse.error.message << std::endl;
			if (i < max_retries - 1) {  // no need to sleep on last iteration
				std::this_thread::sleep_for(std::chrono::seconds(delay_seconds));
			}
			continue;
		}

		Json::Value value;
		Json::Reader reader;
		if (!reader.parse(categoriesResponse.text, value)) {
			std::cerr << "Failed to parse categories response: " << reader.getFormattedErrorMessages() << std::endl;
			continue;
		}
	}
}
```

As seen here, I implemented the retry logic but sometimes the failure appear more than 3 times in a row.

### Example/How to Reproduce

Write a code which will be something similar to this one:

```
{
	std::string url = "https://openapi.keycrm.app/v1/products/categories?limit=50";

	const int max_retries = 3;
	const int delay_seconds = 2;

	cpr::Header headers = {
		{"Content-type", "application/json"},
		{"Accept", "application/json"},
		{"Cache-Control", "no-cache"},
		{"Pragma", "no-cache"},
		{"Authorization", "Bearer " + token}
	};
	for (int i = 0; i < max_retries; i++) {
		auto categoriesResponse = cpr::Get(cpr::Url{ url }, headers);
		if (categoriesResponse.error) {
			std::cerr << "Error " << categoriesResponse.error.message << std::endl;
			if (i < max_retries - 1) {  // no need to sleep on last iteration
				std::this_thread::sleep_for(std::chrono::seconds(delay_seconds));
			}
			continue;
		}

		Json::Value value;
		Json::Reader reader;
		if (!reader.parse(categoriesResponse.text, value)) {
			std::cerr << "Failed to parse categories response: " << reader.getFormattedErrorMessages() << std::endl;
			continue;
		}
	}
}
```

### Possible Fix

The issue might be with the headers' logic. I tried running other GET requests without including header and it worked fine.

### Where did you get it from?

vcpkg

### Additional Context/Your Environment

- OS: Windows (build: 22621.1848)
- Version: 11 - pro (22H2)

**Comment by COM8** [comment]
Thanks for reporting! Any chance you are behind some kind of firewall?

**Comment by KyryloVolotovskyi** [comment]
> Thanks for reporting! Any chance you are behind some kind of firewall or using a VPN?

It is definitely not a VPN issue, since I do not use any. However, I am not sure about the firewall. Could you suggest what might be wrong and what to look for to understand if that is the issue? Also, why in python it works totally fine? Does python has some way to take over the firewall?

Thanks in a advance!

**Comment by MrVolot** [comment]
@COM8 I also do not use VPN and am not sure about the firewall. Any suggestions on how to verify?

**Comment by COM8** [comment]
Some corporate firewalls might block your request if you try to do too many at once (prevent spamming).

Python might not be triggering this sind it is slower and therefore taking more time between request.

I will look into trying to reproduce your issue.

**Comment by MrVolot** [comment]
@COM8 Thank you!

**Comment by COM8** [comment]
I'm trying now since over an hour to reproduce this (without API key) and I'm failing.
Btw. cpr has build in support for bearer auth: https://docs.libcpr.org/introduction.html#authentication

Any chance you can retry it on a different network?

**Comment by MrVolot** [comment]
@COM8  I see that with another endpoint than I provided everything works fine. So, I assume that there is some blocker from the API server side. Sorry for spending your time on the investigation. I think this issue can be closed since it doesn't seem to be an issue in the library.

**Comment by COM8** [comment]
Awesome and no problem. Thanks for the well formulated Issue!
