### ISSUE TITLE
Build fails when including cpr in project on MacOS

### ISSUE THREAD

**Issue by crazydef** [libcpr/cpr#943]
### Description

Building our product (which uses libcpr) on macOS fails because some cpr internal includes are using angled brackets, while others are using double quotes.

The particular error I'm currently stuck on is this one:

/Users/.../External/MacOS/include/libcpr/cpr/file.h:8:10: error: 'cpr/filesystem.h' file not found with <angled> include; use "quotes" **instead**

### Example/How to Reproduce

1. Include cpr in a MacOS project and try to build.

### Possible Fix

Stop using angled brackets to include your own headers.  And stop prefixing include paths with `cpr/` when those includes are in the same directory as the current include file.

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

macOS Ventura 13.3.1 (22E261)
Apple clang version 14.0.0 (clang-1400.0.29.202)

**Comment by COM8** [comment]
@crazydef  thanks for reporting! I wil try to work on a fix for it tomorrow.

**Comment by COM8** [comment]
To be honest, I don't know why the hell this happened. We are even mixing `<cpr..` and `"cpr..` inside the same file...
Thanks for reporting!

I created a PR for it: https://github.com/libcpr/cpr/pull/946

Could you please validate that it works now as expected?
