### ISSUE TITLE
Cookies can't be not encoded

### ISSUE THREAD

**Issue by Romiro27** [libcpr/cpr#953]
### Description

Sorry for my English, im not a native speaker.

It seems impossible to send cookie without encoding. In session.cpp at Session::SetCookie function cpr dont check a Cookies.encode. Maybe i looks like dumb, but i think i need to send to site not encoded cookies.

https://github.com/libcpr/cpr/blob/253346373575b383a56e2741b8250a6acf6fa50e/cpr/session.cpp#L447-L450

### Example/How to Reproduce

1. Create a `cpr::Session`
2. SetCookies
3. All cookies is encoded.

### Where did you get it from?

Other (specify in "Additional Context/Your Environment")

### Additional Context/Your Environment

- OS: Arch Linux x86_64 linux 6.4.8-arch1-1
- Version: cpr 1.10.4-1

**Comment by COM8** [comment]
@Romiro27 Thanks for reporting!
In theory `` should deal with that.

**Comment by COM8** [comment]
I don't have time to look into it further but I will do so the next few days.

**Comment by COM8** [comment]
I can not reproduce it. I created a test case for it here: https://github.com/libcpr/cpr/pull/955

Could you please provide an end to end example for me so I can reproduce it?

**Comment by COM8** [comment]
Closing for no response.
