### ISSUE TITLE
Expose the global session under the hood

### ISSUE THREAD

**Issue by zuoxinyu** [libcpr/cpr#958]
### Is your feature request related to a problem?

I want perform logging on every request/response emitted by `cpr::Get()` / `cpr::Post()` / `cpr::Put()` etc... , but the interceptor can only attached  to a session.

### Possible Solution

I don't know is there a hidden global session behind global request methods like get/post. 

If there is, it's better to expose it via a method like `cpr::GlobalSession()` so that users can use `AddInterceptor()` or `SetOption()` which performing on each global call, without creating a session.

A simple example:

```c++
auto &session = cpr::GlobalSession();
session.AddInterceptor(logger_interceptor);
session.SetProxies({{"http", "http://proxyserver.com"}});
auto resp = cpr::Get(cpr::Url{"http://example.com"});       // via proxy and perform logging on request/response
resp = cpr::Post(cpr::Url{"http:example.com/resources"})
...
```

**Comment by zuoxinyu** [comment]
Alright I've read the source code for `Get`. In that case, maybe we could add some API to the session class in the same style as `cpr::Get`, which would do the same thing as Global Session.

**Comment by COM8** [comment]
Sorry, but I don't really get what you want. We won't be having a global session since then we would limit/have to deal with concurrency.

If you want to log **everything**, setup your own global `cpr::Session`(s) and insert an `cpr::Interceptor` inside them.

e.g.
```c++
cpr::Session GlobalSession;

class LoggingInterceptor : public cpr::Interceptor {
  public:
    cpr::Response intercept(cpr::Session& session) override {
        // Log the request URL
        std::cout << "Request url: " << session.GetFullRequestUrl() << std::endl;

        // Proceed the request and save the response
        cpr::Response response = proceed(session);

        // Log response status code
        std::cout << "Response status code: " << response.status_code << std::endl;

        // Return the stored response
        return response;
    }
};

int main() {
    GlobalSession.AddInterceptor(std::make_shared<LoggingInterceptor>());
    
    // Do other stuff...
}
```
