### ISSUE TITLE
Dangling reference when moving after SetDebugCallback

### ISSUE THREAD

**Issue by kone-tlammi** [libcpr/cpr#961]
### Description

Moving `cpr::Session` after `SetDebugCallback` is invoked results in a dangling reference:
https://github.com/libcpr/cpr/blob/master/cpr/session.cpp#L279

Other callbacks likely also affected.

### Example/How to Reproduce

```C++
// cprbug.cpp
#include <cpr/cpr.h>

void use_session(cpr::Session s) {
  s.SetUrl("https://github.com/libcpr/cpr");
  s.Get();
}

int main() {
  auto s = cpr::Session();
  s.SetDebugCallback(cpr::DebugCallback([](auto, auto, auto) {}));
  use_session(std::move(s));
}
```
Compiled with GCC 13.2.1:
`g++ -g -std=c++20 ./cprbug.cpp -lcpr`

If the `use_session()` is inlined everything works fine.

### Possible Fix

A couple of possible ways to fix this:

- Change `debugcb_` to `std::unique_ptr<DebugCallback>`
    - Same needed for the other callbacks probably
- Custom move constructor to move the references in libcurl
- Make `cpr::Session` non-movable (breaks API).

### Where did you get it from?

Other (specify in "Additional Context/Your Environment")

### Additional Context/Your Environment

- OS: Manjaro Linux
- Version: rolling
- Reproduced with CPR versions:
    - AUR package: 1.10.4-1
    - Conan package: 1.10.1

**Comment by COM8** [comment]
Whoops, thanks for reporting @kone-tlammi!
In my eyes the custom move ctr is the way to go here.

Any chance you want to look into this since I don't have time for it for the next two weeks or so.

**Comment by kone-tlammi** [comment]
I can if I have a free slot at some point.

I'm thinking something like the snippet below (with a better interface) to avoid missing a move.

```C++

template<class T>
struct CurlCallbackData{
    CurlCallbackData(CurlCallbackData&& other) noexcept:
        h{other.h}, curlopt{other.curlopt}, data{std::move(other.data)}{
        curl_easy_setopt(h, curlopt, &data);
    }
    CURL* h{};
    int curlopt;
    T data;
};
```

**Comment by kone-tlammi** [comment]
Should be fixed by https://github.com/libcpr/cpr/pull/962
