### ISSUE TITLE
2question: is cpr thread safe?, how to change network timeouts?

### ISSUE THREAD

**Issue by elsbiet** [libcpr/cpr#976]
- just want to make sure that i can use the (linux) cpr shared library without any restrictions without analyzing the code.

- as i feel the default network timeout (cpr::Put, cpr::post, ..) is very large, i would like to change it to a smaller value and i wonder how to do this.

thanks for your answer.

rgds, e.

**Comment by COM8** [comment]
* Timeout: https://docs.libcpr.org/advanced-usage.html#setting-a-timeout
* Thread Safety: You can not use/share `cpr::Session` with multiple threads. Either use one `cpr::Session` per thread, or use an async request: https://docs.libcpr.org/advanced-usage.html#asynchronous-requests
