### ISSUE TITLE
Segmentation fault when running the example

### ISSUE THREAD

**Issue by sami7719037** [libcpr/cpr#978]
### Description

I am running the example 
```#include <cpr/cpr.h>
int main(int argc, char** argv) {
    cpr::Response r = cpr::Get(cpr::Url{"https://api.github.com/repos/whoshuu/cpr/contributors"},
                      cpr::Authentication{"user", "pass", cpr::AuthMode::BASIC},
                      cpr::Parameters{{"anon", "true"}, {"key", "value"}});
    r.status_code;                  
    r.header["content-type"];  
    r.text;       
    return 0;
}
```
I compile it using `g++ cprexp.cc -o cprexp -lcpr -lcurl`, which creates a `cprexp`. When I run `cprexp`, using `./cprexp`, it gives me `Segmentation fault (core dumped)`. 
I need the CPR version 1.9.x because my project uses C++11.

### Example/How to Reproduce

1. git clone https://github.com/libcpr/cpr.git
2. cd cpr
3. git switch 1.9.x
4. cd cpr && mkdir build && cd build
5. cmake .. -DCPR_USE_SYSTEM_CURL=ON 
6. cmake --build . –parallel
7. sudo cmake --install .

### Where did you get it from?

GitHub (branch e.g. master)

### Additional Context/Your Environment

- OS and version: Ubuntu 22.04.3 LTS
- Architecture: x86_64
- curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/8.4.0 OpenSSL/3.0.2 zlib/1.2.13.zlib-ng

**Comment by COM8** [comment]
@sami7719037 sorry for the delayed response.

I can not reproduce this. This is what I tried:
```bash
# Enter container
podman run -i -t ubuntu:22.04 /bin/bash

# Inside the container run:
apt update
apt install nano libcurl4-openssl-dev gcc g++ git cmake libssl-dev
git clone https://github.com/libcpr/example-cmake-fetch-content.git
cd example-cmake-fetch-content
mkdir build && cd build
nano CMakeLists.txt # change CMAKE_CXX_STANDARD to 11 and GIT_TAG to 1.9.x
cmake .. -DCPR_FORCE_USE_SYSTEM_CURL=ON # You passed the wrong one -DCPR_USE_SYSTEM_CURL
cmake --build . --parallel
./cpr_example
```

**Comment by COM8** [comment]
Could you please try those steps?

**Comment by COM8** [comment]
Closing for no response....
