### ISSUE TITLE
Unable to perform http request with tor proxy ( ip does not change)

### ISSUE THREAD

**Issue by Conansmith100** [libcpr/cpr#979]
### Description

```c++
#include <cpr/cpr.h>
#include <iostream>
#define SOCKS5_PROXY "socks5h://localhost:9050" //Use socks5h here
#include <curl/curl.h>
using namespace std;
int main(int argc, char** argv) {

CURL *curl = curl_easy_init();


cpr::AsyncResponse fr = cpr::GetAsync(cpr::Url{"https://ident.me"}, cpr::Proxies{{"http", SOCKS5_PROXY}});
fr.wait(); // This waits until the request is complete
cpr::Response r = fr.get(); // Since the request is complete, this returns immediately
std::cout << r.text << std::endl;

}
```

My ip doesn't change. Even though tor is running.

### Example/How to Reproduce

Ip address does not change.

### Where did you get it from?

Other (specify in "Additional Context/Your Environment")

### Additional Context/Your Environment

- OS: Unbuntu-arm
- Version:22

**Comment by COM8** [comment]
You are just setting the proxy for http requests. Not for https requests.

Try the following:
```c++
#include <iostream>
#include <cpr/cpr.h>

#define SOCKS5_PROXY "socks5h://localhost:9050"  //Use socks5h here

int main(int argc, char** argv) {
    cpr::AsyncResponse fr = cpr::GetAsync(cpr::Url{"https://ident.me"}, cpr::Proxies{{"http", SOCKS5_PROXY}, {"https", SOCKS5_PROXY}});
    fr.wait();  // This waits until the request is complete
    cpr::Response r = fr.get();  // Since the request is complete, this returns immediately
    std::cout << r.text << std::endl;
}
```

**Comment by Conansmith100** [comment]
Thanks you these solution work but now i am having these eror:
sudo g++ -o /usr/local/bin/t1 '/home/ubuntu/Desktop/test1.cpp'
I am encountering an error while attempting to compile any cpp file, regardless of which one it is. The error message reads: "as: error while loading shared libraries: libcpr.so.1: cannot open shared object file: No such file or directory."

Initially, I attempted to export the library's location to the environment variable by using the following command: "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/". Although this approach seemed effective at first, it ultimately proved to be unsuccessful.
