### ISSUE TITLE
Incorrect implementation of cpr::Session move constructor and move assignment operator

### ISSUE THREAD

**Issue by Polarhigh** [libcpr/cpr#990]
### Description

When moving a cpr::Session object, the curl options CURLOPT_XFERINFODATA, CURLOPT_DEBUGDATA, CURLOPT_WRITEDATA, and others are not updated. 
As a result, when cpr tries to call, for example, the progress callback function, the progresscb_ of the old cpr::Session object that was moved is accessed.

### Example/How to Reproduce

The sample code below is guaranteed to crash in debug mode. (In release mode, it's a matter of luck)

```c++
#include <iostream>
#include <cpr/cpr.h>

cpr::Session CreateCprSession(const std::string& url)
{
    cpr::Session session;

    session.SetUrl(url);
    session.SetProgressCallback(cpr::ProgressCallback(
        [](cpr::cpr_off_t downloadTotal, cpr::cpr_off_t downloadNow, cpr::cpr_off_t uploadTotal, cpr::cpr_off_t uploadNow, intptr_t userdata) {
            std::cout << "Downloaded: " << downloadTotal << " / " << downloadNow << "\n";
            return true;
        }));

    return session;
}


int main()
{
    cpr::Session session = CreateCprSession("https://httpbin.org/get");
    cpr::Response response = session.Get();

    std::cout << "Response: " << response.text << "\n";
    return 0;
}
```

### Possible Fix

I think it can be fixed by adding support to the constructor and assignment operator so that the necessary curl options are updated.

### Where did you get it from?

Other (specify in "Additional Context/Your Environment")

### Additional Context/Your Environment

- OS: Windows 11 Pro 23H2
- cpr version: 1.10.5
The cpr was obtained from github and added to the project via add_subdirectory.

**Comment by COM8** [comment]
@Polarhigh thanks for reporting! I will try to take a look at this over the next few weeks.

**Comment by COM8** [comment]
I'm keeping #999 open for the next week or so, to ensure there are no other important arguments against this approach.

**Comment by Polarhigh** [comment]
> What should happen in case you copy it in mids of request?

Indeed, nothing good will come of it)



> As a solution I suggest using some kind of a container like `std::shared_ptr`.

Yes, thanks, in my case I decided to use unique_ptr
