### ISSUE TITLE
Linking Error with CPR Library in C++ CMake Project Using VCPKG

### ISSUE THREAD

**Issue by M4cM4rco** [libcpr/cpr#994]
### Description

I'm encountering a linking error in my C++ project when trying to use the cpr library via vcpkg. The issue arises during the linking phase, specifically when creating the executable for my application.
Same error in a new Test project:

**CMakeLists.txt:**
```
cmake_minimum_required(VERSION 3.27)
project(Test2)

set(CMAKE_CXX_STANDARD 17)
find_package(cpr REQUIRED)

add_executable(Test2 main.cpp)

target_link_libraries(Test2 PRIVATE cpr::cpr)

```

**main.cpp:**
```
#include <iostream>
#include <cpr/cpr.h>

int main() {
    cpr::Response r = cpr::Get(cpr::Url{"https://api.github.com/repos/whoshuu/cpr/contributors"},
                               cpr::Authentication{"user", "pass", cpr::AuthMode::BASIC},
                               cpr::Parameters{{"anon", "true"}, {"key", "value"}});
    r.status_code;                  // 200
    r.header["content-type"];       // application/json; charset=utf-8
    r.text;
    std::cout << "Hello, World!" << std::endl;
    return 0;
}

```

**Build output:**

```
[1/1] Linking CXX executable Test2.exe
FAILED: Test2.exe 
cmd.exe /C "cd . && C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin\g++.exe -g  CMakeFiles/Test2.dir/main.cpp.obj -o Test2.exe -Wl,--out-implib,libTest2.dll.a -Wl,--major-image-version,0,--minor-image-version,0  D:/Development/vcpkg/vcpkg/installed/x64-windows/debug/lib/cpr.lib  D:/Development/vcpkg/vcpkg/installed/x64-windows/debug/lib/libcurl-d.lib  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cmd.exe /C "cd /D D:\Development\Project\C++\Test2\cmake-build-debug-mingw_not_qt && C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -executionpolicy Bypass -file D:/Development/vcpkg/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary D:/Development/Project/C++/Test2/cmake-build-debug-mingw_not_qt/Test2.exe -installedDir D:/Development/vcpkg/vcpkg/installed/x64-windows/debug/bin -OutVariable out""
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: CMakeFiles/Test2.dir/main.cpp.obj: in function `main':
D:/Development/Project/C++/Test2/main.cpp:7: undefined reference to `cpr::Parameters::Parameters(std::initializer_list<cpr::Parameter> const&)'
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: D:/Development/Project/C++/Test2/main.cpp:6: undefined reference to `cpr::Authentication::~Authentication()'
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: D:/Development/Project/C++/Test2/main.cpp:6: undefined reference to `cpr::Authentication::~Authentication()'
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: CMakeFiles/Test2.dir/main.cpp.obj: in function `cpr::Response cpr::Get<cpr::Url, cpr::Authentication, cpr::Parameters>(cpr::Url&&, cpr::Authentication&&, cpr::Parameters&&)':
D:/Development/vcpkg/vcpkg/installed/x64-windows/include/cpr/api.h:119: undefined reference to `cpr::Session::Session()'
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: D:/Development/vcpkg/vcpkg/installed/x64-windows/include/cpr/api.h:121: undefined reference to `cpr::Session::Get()'
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: CMakeFiles/Test2.dir/main.cpp.obj: in function `std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cpr::CaseInsensitiveCompare, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)':
C:/Users/marco/AppData/Local/Programs/CLion/bin/mingw/lib/gcc/x86_64-w64-mingw32/13.1.0/include/c++/bits/stl_map.h:529: undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: CMakeFiles/Test2.dir/main.cpp.obj: in function `std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, cpr::CaseInsensitiveCompare, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_get_insert_hint_unique_pos(std::_Rb_tree_const_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
C:/Users/marco/AppData/Local/Programs/CLion/bin/mingw/lib/gcc/x86_64-w64-mingw32/13.1.0/include/c++/bits/stl_tree.h:2221: undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: C:/Users/marco/AppData/Local/Programs/CLion/bin/mingw/lib/gcc/x86_64-w64-mingw32/13.1.0/include/c++/bits/stl_tree.h:2226: undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: C:/Users/marco/AppData/Local/Programs/CLion/bin/mingw/lib/gcc/x86_64-w64-mingw32/13.1.0/include/c++/bits/stl_tree.h:2232: undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: C:/Users/marco/AppData/Local/Programs/CLion/bin/mingw/lib/gcc/x86_64-w64-mingw32/13.1.0/include/c++/bits/stl_tree.h:2242: undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: CMakeFiles/Test2.dir/main.cpp.obj:C:/Users/marco/AppData/Local/Programs/CLion/bin/mingw/lib/gcc/x86_64-w64-mingw32/13.1.0/include/c++/bits/stl_tree.h:2248: more undefined references to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const' follow
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: CMakeFiles/Test2.dir/main.cpp.obj: in function `void cpr::priv::set_option_internal<false, cpr::Url>(cpr::Session&, cpr::Url&&)':
D:/Development/vcpkg/vcpkg/installed/x64-windows/include/cpr/api.h:30: undefined reference to `cpr::Session::SetOption(cpr::Url const&)'
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: CMakeFiles/Test2.dir/main.cpp.obj: in function `std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, cpr::CaseInsensitiveCompare, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_lower_bound(std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, std::_Rb_tree_node_base*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
C:/Users/marco/AppData/Local/Programs/CLion/bin/mingw/lib/gcc/x86_64-w64-mingw32/13.1.0/include/c++/bits/stl_tree.h:1952: undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: CMakeFiles/Test2.dir/main.cpp.obj: in function `std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, cpr::CaseInsensitiveCompare, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_get_insert_unique_pos(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
C:/Users/marco/AppData/Local/Programs/CLion/bin/mingw/lib/gcc/x86_64-w64-mingw32/13.1.0/include/c++/bits/stl_tree.h:2118: undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: C:/Users/marco/AppData/Local/Programs/CLion/bin/mingw/lib/gcc/x86_64-w64-mingw32/13.1.0/include/c++/bits/stl_tree.h:2129: undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: CMakeFiles/Test2.dir/main.cpp.obj: in function `std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, cpr::CaseInsensitiveCompare, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_insert_node(std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*)':
C:/Users/marco/AppData/Local/Programs/CLion/bin/mingw/lib/gcc/x86_64-w64-mingw32/13.1.0/include/c++/bits/stl_tree.h:2382: undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: CMakeFiles/Test2.dir/main.cpp.obj: in function `void cpr::priv::set_option_internal<false, cpr::Authentication>(cpr::Session&, cpr::Authentication&&)':
D:/Development/vcpkg/vcpkg/installed/x64-windows/include/cpr/api.h:30: undefined reference to `cpr::Session::SetOption(cpr::Authentication const&)'
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: CMakeFiles/Test2.dir/main.cpp.obj: in function `void cpr::priv::set_option_internal<false, cpr::Parameters>(cpr::Session&, cpr::Parameters&&)':
D:/Development/vcpkg/vcpkg/installed/x64-windows/include/cpr/api.h:30: undefined reference to `cpr::Session::SetOption(cpr::Parameters&&)'
C:\Users\marco\AppData\Local\Programs\CLion\bin\mingw\bin/ld.exe: CMakeFiles/Test2.dir/main.cpp.obj: in function `std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, cpr::EncodedAuthentication>::~pair()':
C:/Users/marco/AppData/Local/Programs/CLion/bin/mingw/lib/gcc/x86_64-w64-mingw32/13.1.0/include/c++/bits/stl_pair.h:187: undefined reference to `cpr::EncodedAuthentication::~EncodedAuthentication()'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

P.S.: Other libs working fine (tested with nlohmann-json:x64-windows).

### Example/How to Reproduce

1. Create a project with CLion 
2. Setup Vcpkg
3. Edit CMakeLists.txt (find_package & target_link_libraries)
4. include cpr and insert example in main.cpp
5. Edit CMake options: -DCMAKE_TOOLCHAIN_FILE=<vcpkg_dir>/vcpkg.cmake -DCPR_USE_SYSTEM_CURL=ON
6. Build project

### Possible Fix

Using **fetch_content**

### Where did you get it from?

vcpkg

### Additional Context/Your Environment

**OS:** Windows 11
**Compiler:** GCC (MinGW), version 11.2.0
**CMake Version:** 3.28.1 & 3.27.0
**CPR Version:** 1.10.5
**CPR installed triplets:** x64-windows

**Comment by COM8** [comment]
Your compiler does not link against `cpr` (first line of your output).

Try `find_package(cpr CONFIG REQUIRED)` since the CMake file is called `cpr-config.cmake` for setting up libs.

Here is an example of using vcpkg with CMake: https://github.com/miredirex/cmake-vcpkg-example

**Comment by M4cM4rco** [comment]
Thank you for your response. 
I'm still encountering the same error with `find_package(cpr CONFIG REQUIRED)`. 
I've correctly set up `CMake` for `vcpkg` (the `TOOLCHAIN_FILE` was specified as a CMake option, and I've also defined it again in `CMakeLists.txt` with `set(CMAKE_TOOLCHAIN_FILE <path>))`. 
**Since other libraries installed via `vcpkg` are working, I don't think I've made a mistake there...** 

I took the time to create the same project in Visual Studio, and it worked without any errors. 
I also opened and ran the _Test2_ project in Visual Studio, and it worked. It seems the problem lies with CLion... the only difference was which `CMake`, `ninja.exe`, `cc.exe` and `c++.exe` was used. So, I configured CLion to use the same settings as Visual Studio, but I'm still encountering the same error. Even after downloading everything with MSYS2 and using those, the same error persists.

**Comment by COM8** [comment]
Then this to me does not sound like a cpr related issue and instead it's a vcpkg/CLion issue. Sadly I'm not experience with neither of those. We also do not maintain the vcpkg packages.

**Comment by M4cM4rco** [comment]
You're right. After checking the `vcpkg` **triplets**, I realized that there is no **x64-mingw** for `cpr`... that's where the original error came from. 
**Solution:**
After creating a new project in CLion and switching the toolchains to Visual Studio **before** integrating `vcpkg`, everything is now working!

Thanks for your help!

**Comment by Garald-48rus** [comment]
auto r = cpr::Get(
        cpr::Url{"https://jsonplaceholder.typicode.com/todos/1"});

    std::cout << r.status_code << "\n";            // 200
    std::cout << r.header["content-type"] << "\n"; // application/json;charset=utf-8
    std::cout << r.text << "\n";                   // JSON text string

linux mint 
qt creator
:-1: ошибка: main.o: in function `cpr::Response cpr::Get<cpr::Url>(cpr::Url&&)':
/usr/local/include/cpr/api.h:119: ошибка: undefined reference to `cpr::Session::Session()'
:-1: ошибка: /usr/local/include/cpr/api.h:121: undefined reference to `cpr::Session::Get()'
:-1: ошибка: main.o: in function `std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cpr::CaseInsensitiveCompare, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)':
/usr/include/c++/9/bits/stl_map.h:517: ошибка: undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
:-1: ошибка: main.o: in function `void cpr::priv::set_option_internal<false, cpr::Url>(cpr::Session&, cpr::Url&&)':
/usr/local/include/cpr/api.h:30: ошибка: undefined reference to `cpr::Session::SetOption(cpr::Url const&)'
:-1: ошибка: main.o: in function `std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, cpr::CaseInsensitiveCompare, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_get_insert_hint_unique_pos(std::_Rb_tree_const_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/include/c++/9/bits/stl_tree.h:2203: ошибка: undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
:-1: ошибка: /usr/include/c++/9/bits/stl_tree.h:2208: undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
:-1: ошибка: /usr/include/c++/9/bits/stl_tree.h:2214: undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
:-1: ошибка: /usr/include/c++/9/bits/stl_tree.h:2224: undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
:-1: ошибка: /usr/include/c++/9/bits/stl_tree.h:2230: undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
:-1: ошибка: main.o:/usr/include/c++/9/bits/stl_tree.h:2363: more undefined references to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const' follow
:-1: ошибка: main.o: in function `std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, cpr::EncodedAuthentication>::~pair()':
/usr/include/c++/9/bits/stl_pair.h:208: ошибка: undefined reference to `cpr::EncodedAuthentication::~EncodedAuthentication()'
:-1: ошибка: collect2: error: ld returned 1 exit status
:-1: ошибка: [Makefile:237: Test_Code] Error 1

**Comment by Garald-48rus** [comment]
did everything according to this instruction

**Comment by COM8** [comment]
You are not linking against cpr. Please update your linker settings inside QT creator.  Also please take a look at the available markdown syntax in GitHub to better format your comments.
