### ISSUE TITLE
Proxy Problem

### ISSUE THREAD

**Issue by TheHellTower** [libcpr/cpr#995]
### Description

I tried to set a proxy to then get my ip using an host but it failed. I expected it to send the request correctly and so return my IP..

### Example/How to Reproduce

1. Create a Visual Studio project in Release x64 & C++20
2. Code:
```cpp
#include <iostream>
#include <cpr/cpr.h>

using namespace std;

int main()
{
    cpr::Response r = cpr::Get(cpr::Url{ "https://api.ipify.org" }, cpr::Proxies{ {"https", "socks5://p.webshare.io:9999"} });
    cout << r.status_code << endl <<  r.text << endl;
}
```
4. Perform the request
5. See error (status code => 0)

### Where did you get it from?

vcpkg

### Additional Context/Your Environment

- OS: Windows 10
- Version: 19045.3803
- CPR: 1.10.5#1 (`VCPKG`)

I tried multiple ways:

```cpp
cpr::Response r = cpr::Get(cpr::Url{ "https://api.ipify.org" }, cpr::Proxies{ {"http", "socks5://p.webshare.io:9999"} }); //Didn't try it and returned my actual IP
cpr::Response r = cpr::Get(cpr::Url{ "https://api.ipify.org" }, cpr::Proxies{ {"https", "socks5://p.webshare.io:9999"} }); //status_code: 0
cpr::Response r = cpr::Get(cpr::Url{ "https://api.ipify.org" }, cpr::Proxies{ {"https", "http://p.webshare.io:9999"} }); //status_code: 0
cpr::Response r = cpr::Get(cpr::Url{ "https://api.ipify.org" }, cpr::Proxies{ {"https", "https://p.webshare.io:9999"} }); //status_code: 0
cpr::Response r = cpr::Get(cpr::Url{ "https://api.ipify.org" }, cpr::Proxies{ {"socks5", "https://p.webshare.io:9999"} }); //status_code: 0
```

Mutiple ways shown by the proxy provider: 
![](https://i.imgur.com/u7p1UnM.gif)

**Comment by COM8** [comment]
Curl reports a `CURLE_PROXY` error indicating a proxy handshake error.
That's what I get when passing `cpr::Verbose{true}` as additional parameter:
```
* WARNING: failed to open cookie file ""
* Trying 185.183.105.250:9999...
* Connected to p.webshare.io (185.183.105.250) port 9999
* No authentication method was acceptable.
* Closing connection
```

This also happens when executing the provided curl command:
```
curl --proxy "socks5://p.webshare.io:9999" https://api.ipify.org
curl: (97) No authentication method was acceptable.
```

Your Proxy needs authentication information.

**Comment by TheHellTower** [comment]
> curl --proxy "socks5://p.webshare.io:9999" https://api.ipify.org

After having tried I don't even have this issues it says it can't resolve it:
```
> C:\Users\TheHellTower_THT>curl --proxy "socks5://p.webshare.io:9999" https://api.ipify.org
curl: (6) Could not resolve host: p.webshare.io
```

**Comment by TheHellTower** [comment]
Alright I had to use an online tool to ping their subdomain and tet the backend IP with it it's working..
